{
  "hash": "21f6e0486db783af7d2692fb2c4b817c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Problem Set 7 Key\"\nformat: \n  html: \n    engine: knitr\n    embed-resources: true\n  pdf:\n    number-sections: true\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(summarytools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'summarytools'\n\nThe following object is masked from 'package:tibble':\n\n    view\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(lsr)\n```\n:::\n\n\n## Problem 1\n\n1.\tThe data set “acupuncture.csv” includes data from the control group of a randomized controlled trial investigating the effect of acupuncture therapy on headache severity. Each participant was identified using an ID number in the id column. The headache severity was measured for each participant before receiving the treatment and at a 3-month follow-up. The column pk1 includes the baseline headache severity score of the participants while the column pk2 includes the headache severity score after 3 months.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacu <- read.csv(\"datasets/acupuncture.csv\")\nglimpse(acu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 173\nColumns: 5\n$ X     <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1…\n$ id    <int> 112, 113, 114, 130, 131, 137, 138, 141, 149, 150, 161, 169, 184,…\n$ group <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ pk1   <dbl> 9.25, 42.50, 24.25, 21.75, 14.50, 11.75, 56.50, 15.50, 49.25, 9.…\n$ pk2   <dbl> 4.75, 34.50, 16.25, 2.00, 20.00, 11.25, 70.50, 5.75, 9.75, 8.75,…\n```\n\n\n:::\n:::\n\n\n\na.\tWhat test is the most appropriate to test whether there is a difference between the average headache severity scores of the participants before receiving the treatment and the 3-month follow-up? [1pt.]\n\nPaired t-test because these scores were measured from the same participant.\n\nb.\tWhat are the statistical hypotheses for testing whether the average headache severity score in this cohort was lower at the 3-month follow-up compared to the baseline? [2pts.]\n\n$$\nH_0: \\mu_d = 0; H_a: \\mu_d > 0\n$$\n\nwhere $\\mu_d$ is defined as the average difference between baseline and 3-month follow-up. \n\n::: callout-important\nIf \\mu_d is the difference between the treatment between 3-month baseline and follow-up, then the hypothesis should be:\n\n$$\nH_0: \\mu_d = 0; H_a: \\mu_d < 0\n$$\n:::\n\n\nc.\tWhat is the value of the test statistic and the corresponding number of degrees of freedom? [2pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nttest <- t.test(acu$pk1,acu$pk2,paired=T,alternative=\"greater\")\nttest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  acu$pk1 and acu$pk2\nt = 6.9415, df = 172, p-value = 3.799e-11\nalternative hypothesis: true mean difference is greater than 0\n95 percent confidence interval:\n 4.916204      Inf\nsample estimates:\nmean difference \n       6.453757 \n```\n\n\n:::\n:::\n\n\nd.\tWhat is the p-value? [1pt.]\n\nThe p-value is 3.7991629\\times 10^{-11}.\n\ne.\tAt a significance level of 0.001, do we have sufficient evidence that the average headache severity score in this cohort was lower at the 3-month follow-up compared to the baseline? [1pt.]\n\nYes, we have sufficient evidence that the average headache severity score in this cohort was lower at the 3-month follow-up compared to the baseline.\n\n\n## Problem 2\n\nThe file aaqol_subset.csv includes data from the 2015 Asian American Quality of Life survey implemented in Austin, TX. We are interested to test whether there is a difference in average age across the different Asian ethnicities represented in the study.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naaqol <- read.csv(\"datasets/aaqol_subset.csv\")\nglimpse(aaqol)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,000\nColumns: 3\n$ X         <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…\n$ Age       <int> 21, 26, 45, 20, 21, 26, 66, 23, 26, 59, 28, 19, 61, 25, 69, …\n$ Ethnicity <chr> \"Asian Indian\", \"Asian Indian\", \"Korean\", \"Vietnamese\", \"Chi…\n```\n\n\n:::\n:::\n\n\na.\tWhat are the statistical hypotheses for testing whether there is a difference in average age across the different Asian ethnicities represented in the study? [2 pts.]\n\nThe null hypothesis is that the average age across the different Asian ethnicities are equal. The alternative hypothesis is that there is at least one Asian ethnic group with a different average age.\n\nb.\tWhat is the value of the test statistic and the corresponding number of degrees of freedom? Hint: We might need more than one type of degrees of freedom. [3pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_aov<- aov(Age~Ethnicity,data=aaqol)\nsummary(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)   \nEthnicity     4   4361  1090.3   3.664 0.0057 **\nResiduals   995 296109   297.6                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nc.\tWhat is the resulting p-value? [1 pt.]\n\nThe p-value is 0.0057.\n\nd.\tComment on the sufficiency of evidence based on the alternative hypothesis using a significance level of 0.05. Account for the context of the problem. [1 pt.]\n\nAt a significance level of 0.05, there is sufficient evidence that at least one Asian ethnic group has a different average age compared to the others.\n\ne.\tPerform a post-hoc test involving pairwise comparisons between the average age of each Asian ethnic group. Apply the Tukey correction. Which pair/s of Asian ethnic groups yielded evidence of pairwise difference in average ages? Use a significance level of 0.05. [2pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_lm <- lm(Age~Ethnicity,data=aaqol)\nem_mod_lm <- emmeans(mod_lm,~Ethnicity)\nem_mod_lm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Ethnicity    emmean   SE  df lower.CL upper.CL\n Asian Indian   39.6 1.14 995     37.3     41.8\n Chinese        43.6 1.05 995     41.5     45.6\n Filipino       41.0 1.68 995     37.7     44.4\n Korean         45.4 1.23 995     43.0     47.8\n Vietnamese     43.6 1.24 995     41.2     46.1\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(em_mod_lm,method=\"pairwise\",adjust=\"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                  estimate   SE  df t.ratio p.value\n Asian Indian - Chinese     -4.0217 1.55 995  -2.602  0.0706\n Asian Indian - Filipino    -1.4737 2.03 995  -0.725  0.9507\n Asian Indian - Korean      -5.8251 1.67 995  -3.483  0.0047\n Asian Indian - Vietnamese  -4.0620 1.68 995  -2.419  0.1111\n Chinese - Filipino          2.5480 1.98 995   1.286  0.7002\n Chinese - Korean           -1.8034 1.61 995  -1.119  0.7965\n Chinese - Vietnamese       -0.0403 1.62 995  -0.025  1.0000\n Filipino - Korean          -4.3514 2.08 995  -2.089  0.2254\n Filipino - Vietnamese      -2.5883 2.09 995  -1.240  0.7282\n Korean - Vietnamese         1.7631 1.74 995   1.013  0.8494\n\nP value adjustment: tukey method for comparing a family of 5 estimates \n```\n\n\n:::\n:::\n\n\nAt a significance level of 0.05, Asian Indian (39.6) and Korean (45.4) participants yielded evidence of a pairwise difference in average ages, with an estimated difference of -5.82, test statistic of 3.483, and p-value of 0.0047. Other comparisons did not yield any evidence of a difference.\n\n\n## Problem 3\n\nThe data set socmed.csv includes the PHQ-9 scores of freshman and senior students. The students were also asked about their social media use (socmed, levels = low, high) and gaming habits (levels =yes,no) on their electronic devices.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsocmed <- read.csv(\"datasets/socmed.csv\")\nglimpse(socmed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 32\nColumns: 5\n$ X      <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, …\n$ year   <chr> \"F\", \"F\", \"F\", \"F\", \"S\", \"S\", \"S\", \"S\", \"F\", \"F\", \"F\", \"F\", \"S\"…\n$ socmed <chr> \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"High\",…\n$ gaming <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", …\n$ y      <int> 4, 5, 3, 4, 5, 3, 5, 5, 9, 9, 5, 8, 13, 10, 9, 9, 2, 4, 3, 3, 4…\n```\n\n\n:::\n:::\n\n\n\na.\tTest whether there is an interaction between social media use and gaming time on their electronic devices. Use a significance level of 0.05. [2pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_aov <- aov(y~socmed + gaming + socmed:gaming,data=socmed)\nsummary(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Df Sum Sq Mean Sq F value   Pr(>F)    \nsocmed         1  94.53   94.53  43.841 3.50e-07 ***\ngaming         1  57.78   57.78  26.797 1.71e-05 ***\nsocmed:gaming  1  13.78   13.78   6.391   0.0174 *  \nResiduals     28  60.38    2.16                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThere is sufficient evidence of an interaction effect between social media use and gaming habits at the 0.05 significance level. The test statistic was F(1,28)=6.391, and a p-value of 0.0174.\n\n::: callout-note\nOptional: We can also report the partial eta-squared as an effect size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\netaSquared(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  eta.sq eta.sq.part\nsocmed        0.41741410   0.6102481\ngaming        0.25514006   0.4890241\nsocmed:gaming 0.06085277   0.1858407\n```\n\n\n:::\n:::\n\n\nThe partial eta-square for the interaction effect is 0.186.\n\n:::\n\nb.\tProvide the estimate of the group means for each social media*gaming level combination. [2pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_lm <- lm(y~socmed + gaming + socmed:gaming,data=socmed)\nem_mod_lm <- emmeans(mod_lm,~socmed|gaming)\nem_mod_lm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngaming = No:\n socmed emmean    SE df lower.CL upper.CL\n High     5.00 0.519 28     3.94     6.06\n Low      2.88 0.519 28     1.81     3.94\n\ngaming = Yes:\n socmed emmean    SE df lower.CL upper.CL\n High     9.00 0.519 28     7.94    10.06\n Low      4.25 0.519 28     3.19     5.31\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(em_mod_lm)\n```\n\n::: {.cell-output-display}\n![](PS7_key_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n",
    "supporting": [
      "PS7_key_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}