{
  "hash": "d4c6463f1bec67d601ffe37dbb06bb98",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Problem Set 7 Key\"\nformat: \n  html: \n    engine: knitr\n    embed-resources: true\n  pdf:\n    number-sections: true\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --\nv dplyr     1.1.4     v readr     2.1.5\nv forcats   1.0.0     v stringr   1.5.1\nv ggplot2   4.0.0     v tibble    3.3.0\nv lubridate 1.9.4     v tidyr     1.3.1\nv purrr     1.2.1     \n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\ni Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(summarytools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'summarytools'\n\nThe following object is masked from 'package:tibble':\n\n    view\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(effectsize)\n```\n:::\n\n\n\n## Problem 1\nThe file aaqol_subset.csv includes data from the 2015 Asian American Quality of Life survey implemented in Austin, TX. We are interested to test whether there is a difference in average age across the different Asian ethnicities represented in the study.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naaqol <- read.csv(\"datasets/aaqol_subset.csv\")\nglimpse(aaqol)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,000\nColumns: 3\n$ X         <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1~\n$ Age       <int> 21, 26, 45, 20, 21, 26, 66, 23, 26, 59, 28, 19, 61, 25, 69, ~\n$ Ethnicity <chr> \"Asian Indian\", \"Asian Indian\", \"Korean\", \"Vietnamese\", \"Chi~\n```\n\n\n:::\n:::\n\n\na.\tWhat are the statistical hypotheses for testing whether there is a difference in average age across the different Asian ethnicities represented in the study? [2 pts.]\n\nThe null hypothesis is that the average age across the different Asian ethnicities are equal. The alternative hypothesis is that there is at least one Asian ethnic group with a different average age.\n\nb.\tWhat is the value of the test statistic and the corresponding number of degrees of freedom? Hint: We might need more than one type of degrees of freedom. [3pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_aov<- aov(Age~Ethnicity,data=aaqol)\nsummary(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)   \nEthnicity     4   4361  1090.3   3.664 0.0057 **\nResiduals   995 296109   297.6                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nc.\tWhat is the resulting p-value? [1 pt.]\n\nThe p-value is 0.0057.\n\nd.\tWhat is the eta-squared value for the ethnicity effect? [1 pt.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_squared(mod_aov)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFor one-way between subjects designs, partial eta squared is equivalent\n  to eta squared. Returning eta squared.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA\n\nParameter | Eta2 |       95% CI\n-------------------------------\nEthnicity | 0.01 | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\nThe ethnicity effect has an eta squared value of 0.0145.\n\ne.\tComment on the sufficiency of evidence based on the alternative hypothesis using a significance level of 0.05. Account for the context of the problem. [1 pt.]\n\nAt a significance level of 0.05, there is sufficient evidence that at least one Asian ethnic group has a different average age compared to the others.\n\nf.\tPerform a post-hoc test involving pairwise comparisons between the average age of each Asian ethnic group. Apply the Tukey correction. Which pair/s of Asian ethnic groups yielded evidence of pairwise difference in average ages? Use a significance level of 0.05. [2pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_lm <- lm(Age~Ethnicity,data=aaqol)\nem_mod_lm <- emmeans(mod_lm,~Ethnicity)\nem_mod_lm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Ethnicity    emmean   SE  df lower.CL upper.CL\n Asian Indian   39.6 1.14 995     37.3     41.8\n Chinese        43.6 1.05 995     41.5     45.6\n Filipino       41.0 1.68 995     37.7     44.4\n Korean         45.4 1.23 995     43.0     47.8\n Vietnamese     43.6 1.24 995     41.2     46.1\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(em_mod_lm,method=\"pairwise\",adjust=\"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                  estimate   SE  df t.ratio p.value\n Asian Indian - Chinese     -4.0217 1.55 995  -2.602  0.0706\n Asian Indian - Filipino    -1.4737 2.03 995  -0.725  0.9507\n Asian Indian - Korean      -5.8251 1.67 995  -3.483  0.0047\n Asian Indian - Vietnamese  -4.0620 1.68 995  -2.419  0.1111\n Chinese - Filipino          2.5480 1.98 995   1.286  0.7002\n Chinese - Korean           -1.8034 1.61 995  -1.119  0.7965\n Chinese - Vietnamese       -0.0403 1.62 995  -0.025  1.0000\n Filipino - Korean          -4.3514 2.08 995  -2.089  0.2254\n Filipino - Vietnamese      -2.5883 2.09 995  -1.240  0.7282\n Korean - Vietnamese         1.7631 1.74 995   1.013  0.8494\n\nP value adjustment: tukey method for comparing a family of 5 estimates \n```\n\n\n:::\n:::\n\n\nAt a significance level of 0.05, Asian Indian (39.6) and Korean (45.4) participants yielded evidence of a pairwise difference in average ages, with an estimated difference of -5.82, test statistic of 3.483, and p-value of 0.0047. Other comparisons did not yield any evidence of a difference.\n\n## Problem 2\n\nThe data set `Salaries` in the package `carData` includes the 2008-09 nine-month academic salary for Assistant Professors, Associate Professors and Professors in a college in the U.S. Discipline A consists of “theoretical departments”, while Discipline B consists of “applied departments”.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(carData)\nglimpse(Salaries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 397\nColumns: 6\n$ rank          <fct> Prof, Prof, AsstProf, Prof, Prof, AssocProf, Prof, Prof,~\n$ discipline    <fct> B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, A, A,~\n$ yrs.since.phd <int> 19, 20, 4, 45, 40, 6, 30, 45, 21, 18, 12, 7, 1, 2, 20, 1~\n$ yrs.service   <int> 18, 16, 3, 39, 41, 6, 23, 45, 20, 18, 8, 2, 1, 0, 18, 3,~\n$ sex           <fct> Male, Male, Male, Male, Male, Male, Male, Male, Male, Fe~\n$ salary        <int> 139750, 173200, 79750, 115000, 141500, 97000, 175000, 14~\n```\n\n\n:::\n:::\n\n\n\na.\tTest whether there is an interaction between rank (Variable `rank`) and discipline (Variable `discipline`). Use a significance level of 0.05. [2pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_aov <- aov(salary~rank*discipline,data=Salaries)\nsummary(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Df    Sum Sq   Mean Sq F value  Pr(>F)    \nrank              2 1.432e+11 7.162e+10 139.189 < 2e-16 ***\ndiscipline        1 1.843e+10 1.843e+10  35.820 4.9e-09 ***\nrank:discipline   2 4.612e+08 2.306e+08   0.448   0.639    \nResiduals       391 2.012e+11 5.145e+08                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\nAt a significance level of 0.05, there is no evidence of an interaction effect (p=0.639)\n\nb.\tWhat is the partial eta-squared value for the interaction effect? [1 pt.]\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_squared(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type I)\n\nParameter       | Eta2 (partial) |       95% CI\n-----------------------------------------------\nrank            |           0.42 | [0.36, 1.00]\ndiscipline      |           0.08 | [0.05, 1.00]\nrank:discipline |       2.29e-03 | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\nThe interaction effect has a partial eta squared value of 0.0023.\n\nc.\tWhat is the partial eta-squared value for the rank effect? [1 pt.]\n\nThe rank effect has a partial eta squared value of 0.4159.\n\nd.\tWhat is the partial eta-squared value for the discipline effect? [1 pts.]\n\nThe discipline effect has a partial eta squared value of 0.0839.\n\n\n## Problem 3\n\nThe data set socmed.csv includes the PHQ-9 scores of freshman and senior students. The students were also asked about their social media use (socmed, levels = low, high) and gaming habits (levels =yes,no) on their electronic devices.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsocmed <- read.csv(\"datasets/socmed.csv\")\nglimpse(socmed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 32\nColumns: 5\n$ X      <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, ~\n$ year   <chr> \"F\", \"F\", \"F\", \"F\", \"S\", \"S\", \"S\", \"S\", \"F\", \"F\", \"F\", \"F\", \"S\"~\n$ socmed <chr> \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"High\",~\n$ gaming <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", ~\n$ y      <int> 4, 5, 3, 4, 5, 3, 5, 5, 9, 9, 5, 8, 13, 10, 9, 9, 2, 4, 3, 3, 4~\n```\n\n\n:::\n:::\n\n\n\na.\tTest whether there is an interaction between social media use and gaming time on their electronic devices. Use a significance level of 0.05. [2pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_aov <- aov(y~socmed + gaming + socmed:gaming,data=socmed)\nsummary(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Df Sum Sq Mean Sq F value   Pr(>F)    \nsocmed         1  94.53   94.53  43.841 3.50e-07 ***\ngaming         1  57.78   57.78  26.797 1.71e-05 ***\nsocmed:gaming  1  13.78   13.78   6.391   0.0174 *  \nResiduals     28  60.38    2.16                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThere is sufficient evidence of an interaction effect between social media use and gaming habits at the 0.05 significance level. The test statistic was F(1,28)=6.391, and a p-value of 0.0174.\n\nb.\tWhat is the partial eta-squared value for the interaction effect? [1 pt.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_squared(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type I)\n\nParameter     | Eta2 (partial) |       95% CI\n---------------------------------------------\nsocmed        |           0.61 | [0.41, 1.00]\ngaming        |           0.49 | [0.26, 1.00]\nsocmed:gaming |           0.19 | [0.02, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\nThe partial eta-square for the interaction effect is 0.19.\n\n\n\nc.\tAre the partial eta-squared values for `socmed` and `gaming` interpretable? Why or why not? (Hint: Main effects are not interpretable if the null hypothesis for the interaction hypothesis test is rejected). [3 pts.]\n\nThe partial eta-squared for `socmed` and `gaming` represent the main effects. Because we have evidence of an interaction effect, these effect sizes are not interpretable.\n\nd.\tProvide the estimate of the group means for each social media*gaming level combination. [2pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_lm <- lm(y~socmed + gaming + socmed:gaming,data=socmed)\nem_mod_lm <- emmeans(mod_lm,~socmed|gaming)\nem_mod_lm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngaming = No:\n socmed emmean    SE df lower.CL upper.CL\n High     5.00 0.519 28     3.94     6.06\n Low      2.88 0.519 28     1.81     3.94\n\ngaming = Yes:\n socmed emmean    SE df lower.CL upper.CL\n High     9.00 0.519 28     7.94    10.06\n Low      4.25 0.519 28     3.19     5.31\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(em_mod_lm)\n```\n\n::: {.cell-output-display}\n![](PS7_key_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\ne.\tComment on how the estimated group means support your result in (a). [2pts.]\n\nThe difference between the group means of `socmed` is higher in the `Yes` gaming group compared to the `No` gaming group, which supports the alternative hypothesis that there is an interaction between these two factors.\n\n",
    "supporting": [
      "PS7_key_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}