---
title: "Problem Set 2 Key"
format: 
  html: 
    engine: knitr
    embed-resources: true
  pdf:
    number-sections: true
---

1.	Consider a diagnostic test designed to determine whether a piece of medical equipment is faulty. The diagnostic test has a sensitivity of 0.9 and specificity of 0.9. If the estimated percentage of faulty equipment fleet is 1%, what is the probability that a randomly selected piece of equipment is faulty given that it tested positive? [2pts]

::: {.callout-note title="Answer"}
The base rate is 0.01, Sensitivity is 0.9, Specificity is 0.9. The probability that the equipment is faulty given a positive test is a positive predictive value.

$$
PPV = \frac{sens*BR}{sens*BR + (1-spec)(1-BR)}
$$
```{r}
PPV <- (0.9)*(0.01)/((0.9*0.01)+(1-0.9)*(1-0.01))
PPV
```
:::

2.	What is the sample space of a two-sided coin that was tossed three times? [1pt.]

::: {.callout-note title="Answer"}
The answer should include all possible outcomes after tossing a two-sided coin three times. H: Heads, T: Tails

- HHH
- HTT
- THT
- TTH
- THH
- HTH
- HHT
- TTT

Hence the sample space can be written as \{HHH, HTT, THT,TTH,THH,HTH,HHT,TTT\}
:::

3.	An experiment has three possible outcomes, A, B, and C, only one of which can occur at a time. If outcome B is twice as likely as outcome A and if outcome C is thrice as likely as outcome A, what are the marginal probabilities of each outcome (P(A), P(B), P(C))? (Hint: The second axiom of probability states that the sum of the probabilities of the mutually exclusive events is equal to 1.) [3pts]

::: {.callout-note title="Answer"}
From the hint, $P(A)+P(B)+P(C) = 1$. We also know that $P(B) = 2P(A)$ and $P(C) = 3P(A)$. Substituting it to the 2nd axiom of probability,

$$
3P(A) + 2P(A) + P(A) = 1
$$
$$
6P(A) = 1; P(A) = 1/6
$$

It follows that $P(B) = 2P(A) = 2/6 = 1/3$, $P(C) = 3P(A) = 3/6 = 1/2$.
:::

4.	The results of a feasibility study suggest that the probability of randomly selecting an individual who uses AI is 55%. Among those who use AI, the probability of using AI for health-related advice is 23%. What is the probability that a randomly selected individual uses AI for health-related advice? [2pts]

::: {.callout-note title="Answer"}
P(AI and health advice) can be calculated using the multiplication rule with the following values: $P(AI) = 0.55$, $P(HA | AI) = 0.23$. Then,

$$
P(AI \cap HA) = P(HA|AI)P(AI) = (0.55)(0.23)
$$


The resulting value of $P(AI \cap HA) =$ `r 0.55*0.23`

:::

5.	Among 1000 university students, 247 reported to be current smokers, 312 reported to have symptoms of binge drinking, and 59 reported to being current smokers and having symptoms of binge drinking. What is the probability that a randomly selected student out of the 1000 university students is a current smoker or has symptoms of binge drinking? [2pts] 

::: {.callout-note title="Answer"}
We can solve for P(Smoker OR Binge) using the addition rule.

$$
P(S \cup B) = P(S) + P(B) - P(S \cap B) = 247/1000+312/1000 - 59/1000
$$


The resulting value of $P(S \cup B)=$ `r 247/1000+312/1000 - 59/1000`
:::

