{
  "hash": "5dd0863c8298e9426d44627db6ee56b6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Problem Set 5 Key\"\nformat: \n  html: \n    engine: knitr\n    embed-resources: true\n  pdf:\n    number-sections: true\n---\n\n\n\n\n## Problem 1\n\nThe weights of 15 randomly selected girls at birth from a single hospital in New York recorded an average of 3.09 kg and standard deviation of 0.29 kg. \n\na. Which distribution should we use for the reliability coefficient of the confidence interval, the standard normal distribution or the t-distribution? [1pt.]\n\n::: callout-note\nThe t-distribution should be used to calculate the reliability coefficient of the confidence interval because the population variance is unknown.\n:::\n\nb.\tConstruct a 95% confidence interval for the mean birth weight of girls in the population represented by this sample, assuming that the population is Gaussian/normally distributed. [2pts.]\n\nThe confidence interval can be calculated using $\\bar{x} \\pm t_{1-\\alpha/2} s/\\sqrt{n}$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 3.09\nstdev <- 0.29\nsampsize <- 15\ndf <- sampsize-1\nalpha <- 1-0.95\nrelcoeff <- qt(p=1-alpha/2,df=df)\n\nlower <- xbar - relcoeff*stdev/sqrt(sampsize)\nlower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.929403\n```\n\n\n:::\n\n```{.r .cell-code}\nupper <- xbar + relcoeff*stdev/sqrt(sampsize)\nupper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.250597\n```\n\n\n:::\n:::\n\n\n\n\nThe 95% confidence interval for the mean birth weight of girls in the population represented by this sample is (2.93 kg, 3.25 kg)\n\n\nc.\tIs 3 kg a plausible value for the population mean? [1pt.]\n\n::: callout-note\nBecause 3 kg can be found in the interval, it is a plausible value for the population mean.\n:::\n\n\nd.\tIs this result generalizable to all girls born in the United States? Why or why not? [2 pts.]\n\n::: callout-note\nNo, the sample was from a single hospital in New York city, which might not be representative of all girls born in the entire country\n:::\n\n## Problem 2\n\nThe Wechsler’s Adult Intelligence Scale was designed such that the population standard deviation of all IQ scores was maintained at 15.\n\na.\tA random sample of 30 sophomores from a community college recorded an average Wechsler IQ score of 109.5. Construct a 90% confidence interval for the average Wechsler IQ score for the corresponding population. [2 pts.]\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 109.5\nstdev <- 15\nsampsize <- 30\nalpha <- 1-0.9\nrelcoeff <- qnorm(p=1-alpha/2,mean=0,sd=1)\n\nlower <- xbar - relcoeff*stdev/sqrt(sampsize)\nlower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 104.9954\n```\n\n\n:::\n\n```{.r .cell-code}\nupper <- xbar + relcoeff*stdev/sqrt(sampsize)\nupper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 114.0046\n```\n\n\n:::\n:::\n\n\n\n\nThe 95% confidence interval for the mean Wechsler IQ score for the sophomores in the community college is (105, 114)\n\nb.\tSuppose you want to extend your study to calculate the average IQ of all the students from the community college such that the resulting 95% confidence interval has a margin of error of 2 points. How many students do you need to sample from the community college? [2 pts.]\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE <- 2\nalpha <- 1-0.95\nsigma <- 15\nz <- qnorm(p=1-alpha/2)\n\nsampsize <- z^2*sigma^2/E^2\nsampsize\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 216.0821\n```\n\n\n:::\n:::\n\n\n\n\nWe need to sample 217 students from the community college to achieve a margin of error of 2 points in our 95% confidence interval for the average IQ of all the students from the community college\n\n\n\n\n\n## Problem 3\n\nThe file HINTS subset.csv contains a subset of the Health information National Trends Survey 6 (HINTS 6). The households were asked if they used health or wellness apps on their tablet or smartphone (column UsedHealthWellnessApps2) and the type of community they lived in (column PR_RUCA_2010).\n\na.\tConstruct a 95% confidence interval for the long run proportion of individuals who use health or wellness apps on their portable devices based on the whole sample. [2 pts.]\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.5.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   4.0.0     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nhints <- read.csv(\"datasets/HINTS subset.csv\")\nglimpse(hints)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 500\nColumns: 4\n$ X                       <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…\n$ HHID                    <int> 23004900, 23004313, 21011500, 23022289, 210041…\n$ UsedHealthWellnessApps2 <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"No\", \"No\", \"No\", …\n$ PR_RUCA_2010            <chr> \"Metropolitan\", \"Metropolitan\", \"Metropolitan\"…\n```\n\n\n:::\n:::\n\n\n\n\nWe need the proportion of those who reported using health or wellness apps on their portable devices.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(summarytools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'summarytools' was built under R version 4.5.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'summarytools'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:tibble':\n\n    view\n```\n\n\n:::\n\n```{.r .cell-code}\nfreq(hints$UsedHealthWellnessApps2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrequencies  \nhints$UsedHealthWellnessApps2  \nType: Character  \n\n              Freq   % Valid   % Valid Cum.   % Total   % Total Cum.\n----------- ------ --------- -------------- --------- --------------\n         No    186     37.20          37.20     37.20          37.20\n        Yes    314     62.80         100.00     62.80         100.00\n       <NA>      0                               0.00         100.00\n      Total    500    100.00         100.00    100.00         100.00\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsampsize <- 500\nphat <- 314/sampsize\n\nalpha <- 1-0.95\nrelcoeff <- qnorm(p=1-alpha/2)\nse <- sqrt((phat*(1-phat))/sampsize)\n\nlower <- phat - relcoeff*se\nlower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5856343\n```\n\n\n:::\n\n```{.r .cell-code}\nupper <- phat + relcoeff*se\nupper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6703657\n```\n\n\n:::\n:::\n\n\n\nThe 95% confidence interval for the long-run proportion of individuals who use health or wellness apps on their portable devices is (0.59, 0.67).\n\n\nb.\tConstruct a 95% confidence interval with continuity correction to compare the long run proportion of individuals who use health or wellness apps on their portable devices in the metropolitan and micropolitan areas. (Hint: Use count(dataset, PR_RUCA_2010, UsedHealthWellnessApps2) to get conditional counts for each area.) [3pts.]\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(hints, PR_RUCA_2010, UsedHealthWellnessApps2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  PR_RUCA_2010 UsedHealthWellnessApps2   n\n1 Metropolitan                      No 153\n2 Metropolitan                     Yes 289\n3 Micropolitan                      No  20\n4 Micropolitan                     Yes  13\n5        Rural                      No   2\n6        Rural                     Yes   6\n7   Small town                      No  11\n8   Small town                     Yes   6\n```\n\n\n:::\n:::\n\n\n\n\nIn the metropolitan areas, 289 out of 442 used the apps, while in the micropolitan areas, 13 out of 33 used the apps.\n\n::: callout-warning\nThe `prop.test()` can be used to implement the continuity correction. While the `prop.test()` can calculate the confidence intervals, it uses the pooled variance method in confidence intervals. It also uses a different distribution to calculate the reliability coefficient.\n:::\n\nFor this problem, I will use `prop.test()` to implement the continuity correction.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nptest <- prop.test(x=c(289,13), n=c(289+153,33),conf.level=0.95, correct=TRUE)\nptest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(289, 13) out of c(289 + 153, 33)\nX-squared = 7.8708, df = 1, p-value = 0.005024\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.0711144 0.4486991\nsample estimates:\n   prop 1    prop 2 \n0.6538462 0.3939394 \n```\n\n\n:::\n:::\n\n\n\n\nThe resulting 95% confidence interval for the long-run difference in proportion of individuals who use health or wellness apps on their portable devices between the metropolitan and micropolitan areas with the continuity correction is (0.0711, 0.4487).\n\n## Problem 4\n\nThe data set in hflashes.csv contains data from a 14-year cohort study by Freeman et al (2001) that investigated the occurrence of hot flashes in 375 participants. Construct a 95% confidence interval that estimates the difference in average baseline follicle-stimulating hormone (FSH; column: fsh) measurements between those who did and did not experience hotflashes (column: hotflash). Assume unequal variances. [3pts.]\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhflashes <- read.csv(\"datasets/hflashes.csv\")\nglimpse(hflashes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 375\nColumns: 14\n$ pt       <int> 3, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 23, 24…\n$ ageg     <int> 2, 3, 1, 1, 2, 3, 2, 2, 2, 3, 2, 1, 1, 1, 1, 3, 2, 1, 1, 1, 2…\n$ aagrp    <int> 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0…\n$ edu      <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1…\n$ d1       <int> 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0…\n$ f1a      <int> 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1…\n$ pcs12    <dbl> 56.80537, 59.18338, 57.73952, 55.83575, 55.89324, NA, 55.5009…\n$ hotflash <int> 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0…\n$ bmi30    <int> 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0…\n$ estra    <dbl> 106.710, 31.250, 13.410, 10.640, 24.060, 37.305, 26.320, 24.1…\n$ fsh      <dbl> 3.005, 11.195, 14.545, 5.530, 9.780, 10.290, 7.960, 4.775, 7.…\n$ lh       <dbl> 2.980, 5.760, 5.595, 2.260, 2.600, 3.395, 3.570, 2.095, 3.660…\n$ testo    <dbl> 7.680, 11.930, 24.375, 8.280, 4.050, 8.275, 15.995, 12.340, 1…\n$ dheas    <dbl> 61.225, 104.920, 117.450, 36.850, 11.165, 100.360, 76.780, 83…\n```\n\n\n:::\n\n```{.r .cell-code}\nttest <-t.test(hflashes$fsh~hflashes$hotflash,\n       data=hflashes,\n       var.equal=F)\nttest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  hflashes$fsh by hflashes$hotflash\nt = -3.1377, df = 151.77, p-value = 0.002046\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -2.9014940 -0.6593356\nsample estimates:\nmean in group 0 mean in group 1 \n       7.477043        9.257458 \n```\n\n\n:::\n:::\n\n\n\n\nThe 95% confidence interval for the difference in average baseline FSH measurements between those who did and did not experience hot flashes is (-2.9015, -0.6593)\n\n## Problem 5\n\n\nA prior study found that approximately 14.4% of the global population experiences carpal tunnel syndrome. Using this measurement, calculate how many participants you should recruit if you want to estimate the prevalence rate of carpal tunnel syndrome among hospitality workers in Nevada such that the margin of error of a 99% confidence interval estimate is 1%. [2pts.] \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE <- 0.01\npi_hat <-0.144\nalpha <- 1-0.99\nz <- qnorm(p=1-alpha/2)\n\nsampsize <- z^2*pi_hat*(1-pi_hat)/E^2\nsampsize\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8178.439\n```\n\n\n:::\n:::\n\n\n\n\nIt would be recommended to recruit 8179 for the study so that the margin of error of a 99% confidence interval estimate will be approximately 1%.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}