{
  "hash": "f7019d3805ae12a9e5e266e4367643d4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Problem Set 9 Key\"\nformat: \n  html: \n    engine: knitr\n    embed-resources: true\n  pdf:\n    number-sections: true\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --\nv dplyr     1.1.4     v readr     2.1.5\nv forcats   1.0.0     v stringr   1.5.1\nv ggplot2   4.0.0     v tibble    3.3.0\nv lubridate 1.9.4     v tidyr     1.3.1\nv purrr     1.1.0     \n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\ni Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(epitools)\n```\n:::\n\n\n## Problem 1\n\nSuppose a newly developed statistics class was implemented across the different teaching modalities: asynchronous online, web-based, hybrid, and in-person. A researcher claims that the expected number of students who will fail the class when taught as an asynchronous online course is double that of other modalities, which are assumed to have similar failing rates. 2680 students were randomly assigned to the different class modalities (n=670 each).  90 students failed the asynchronous online course, 45 failed the web-based course, 30 students failed the hybrid course, and 38 failed the in-person course. Use the goodness-of-fit to test the researcher’s claim.\n\na.\tWhat are the expected probabilities of failure for each modality? [1pt.]\n\nIf $p$ is the probability of failure for other modalities, asynchronous online course is $2p$. The expected probabilities can then be calculated as $2p + p + p + p = 1$, $p=0.2, 2p=0.4$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- c(0.4,0.2,0.2,0.2)\n```\n:::\n\n\nb.\tWhat are the null and alternative hypotheses for this problem? [1pt.]\n\nNull hypothesis: The observed distribution of the number of failed students follows the expected distribution (twice as much for asynchronous online course compared to others).\n\nAlternative hypothesis: The observed distribution of the number of failed students does not follow the expected distribution (twice as much for asynchronous online course compared to others).\n\nc.\tImplement the goodness-of-fit test. What is the value of the test statistic and the number of degrees of freedom for the corresponding chi-squared distribution? [1 pt.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctest <- chisq.test(c(90,45,30,38),p=p)\nctest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  c(90, 45, 30, 38)\nX-squared = 4.3645, df = 3, p-value = 0.2247\n```\n\n\n:::\n:::\n\n\n\nd.\tUsing 0.05 as the significance level, do we reject or fail to reject the null hypothesis? [1pt.]\n\nFail to reject the null hypothesis.\n\ne.\tComment on the sufficiency of evidence against the null hypothesis. [1 pt.]\n\nWe have insufficient evidence to claim that the observed distribution of the number of failed students does not follow the expected distribution.\n\n\nf.\tDoes the chi-squared assumption hold for this problem? [1pt.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctest$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 81.2 40.6 40.6 40.6\n```\n\n\n:::\n:::\n\n\nThe expected number for each cell is above 5, hence the chi-squared assumption holds.\n\n## Problem 2\n\nThe data set HINTS_smoking.csv contains a subset of the HINTS 6 data set. The columns included are the reported feelings about the participant’s household income (variable IncomeFeelings) and current e-cigarette use for those who have history reporting e-cigarette use (variable UseECigNow).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmoke <- read.csv(\"datasets/HINTS_smoking.csv\")\nglimpse(smoke)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 814\nColumns: 2\n$ IncomeFeelings <chr> \"Getting by on present income\", \"Finding it difficult o~\n$ UseECigNow     <chr> \"Not at all\", \"Not at all\", \"Not at all\", \"Not at all\",~\n```\n\n\n:::\n:::\n\n\na.\tUse the test of independence to determine whether there is evidence that income feelings and current e-cigarette use are not independent. What are the null and alternative hypotheses? [1pt.]\n\nNull hypothesis: Income feelings and current e-cigarette use are independent.\n\nAlternative hypothesis: Income feelings and current e-cigarette use are not independent.\n\nb.\tImplement the test of independence. What is the value of the test statistic and the number of degrees of freedom for the corresponding chi-squared distribution? [1 pt.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctest <- chisq.test(smoke$IncomeFeelings,smoke$UseECigNow)\nctest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  smoke$IncomeFeelings and smoke$UseECigNow\nX-squared = 8.4758, df = 6, p-value = 0.2053\n```\n\n\n:::\n:::\n\n\nThe test statistic is $\\chi^2=$ 8.475813 with 6 degrees of freedom.\n\nc.\tUsing 0.05 as the significance level, do we reject or fail to reject the null hypothesis?\n\nThe p-value is 0.205274. We fail to reject the null hypothesis.\n\n\nd.\tComment on the sufficiency of evidence against the null hypothesis. [1pt.]\n\nInsufficient evidence that the income feelings and current e-cigarette use is not independent.\n\ne.\tDoes the chi-squared assumption hold for this problem? Why? [1pt.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctest$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                             smoke$UseECigNow\nsmoke$IncomeFeelings                           Everyday Not at all Some days\n  Finding it difficult on present income      18.915233  134.31941 19.765356\n  Finding it very difficult on present income  9.074939   64.44226  9.482801\n  Getting by on present income                34.331695  243.79361 35.874693\n  Living comfortably on present income        26.678133  189.44472 27.877150\n```\n\n\n:::\n:::\n\n\nThe chi-squared assumption holds (expected numbers all greater than 5).\n\n## Problem 3\n\nSuppose researchers wanted to investigate the prospective careers of graduating seniors from three different high schools. 200 graduating seniors were sampled from each school, and the results of the survey are given below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseniors <- data.frame(School= rep(c(\"A\",\"B\",\"C\"),each=6),\n                      Track = rep(c(\"STEM\",\"Trade\",\"Healthcare\",\"Business\", \"SS\",\"Others\"),times=3),\n                      Count=c(57,42,17,21,13,50,45,29,30,30,23,43,50,35,25,34,26,30))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrosstabs <- xtabs(Count~School+Track,data=seniors)\ncrosstabs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Track\nSchool Business Healthcare Others SS STEM Trade\n     A       21         17     50 13   57    42\n     B       30         30     43 23   45    29\n     C       34         25     30 26   50    35\n```\n\n\n:::\n:::\n\n\na.\tUse the test of homogeneity to determine whether the probabilities of pursuing a prospective track is homogeneous across the different schools. What are the null and alternative hypotheses? [1pt.]\n\nNull hypothesis: The marginal probabilities are homogeneous across the different schools.\n\nAlternative hypothesis: The marginal probabilities are not homogeneous across the different schools.\n\nb.\tImplement the test of independence. What is the value of the test statistic and the number of degrees of freedom for the corresponding chi-squared distribution? [1 pt.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctest <- chisq.test(crosstabs)\nctest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  crosstabs\nX-squared = 20.051, df = 10, p-value = 0.02877\n```\n\n\n:::\n:::\n\n\nc.\tUsing 0.05 as the significance level, do we reject or fail to reject the null hypothesis? [1pt.]\n\nReject the null hypothesis.\n\nd.\tComment on the sufficiency of evidence against the null hypothesis. [1pt.]\n\nThere is sufficient evidence that the marginal probabilities of being chosen as prospective career tracks are not homogeneous.\n\ne.\tDoes the chi-squared assumption hold for this problem? Why? [1pt.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctest$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Track\nSchool Business Healthcare Others       SS     STEM    Trade\n     A 28.33333         24     41 20.66667 50.66667 35.33333\n     B 28.33333         24     41 20.66667 50.66667 35.33333\n     C 28.33333         24     41 20.66667 50.66667 35.33333\n```\n\n\n:::\n:::\n\n\nChi-squared assumption holds (all expected counts > 5)\n\n4.\tA randomized controlled trial was used to test the efficacy of a novel intervention to curb excessive recreational cannabis use. 100 participants were randomly assigned equally to two groups (n=50 each group): the treatment group that will receive the newly developed intervention, and a control group that will receive a knowledge-based intervention. The participants received treatment and were evaluated at the midpoint of the study. At this time, 19 participants in the treatment group and 7 participants in the control group reported improvement in controlling the urge to use cannabis recreationally.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrct <- expand.grid(Treatment = c(\"Control\",\"Intervention\"),Outcome=c(\"Improvement\",\"NoImprovement\"))\n\nrct$Count <- c(7,19,50-7,50-19)\n\ncrosstabs <- xtabs(Count~Treatment+Outcome,data=rct)\ncrosstabs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Outcome\nTreatment      Improvement NoImprovement\n  Control                7            43\n  Intervention          19            31\n```\n\n\n:::\n:::\n\n\n\n\na.\tIs this a retrospective study or a prospective study? Why? [2pts.]\n\n\nProspective study. The risk was assigned at the start of the study. The two cohorts were followed up to the outcome measurement.\n\nb.\tCalculate the appropriate measure of association with the 95% confidence interval. [2pts.]\n\n::: callout-note\nThe appropriate measure of association is the relative risk.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepitab(crosstabs,method=\"riskratio\",rev=\"columns\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$tab\n              Outcome\nTreatment      NoImprovement   p0 Improvement   p1 riskratio    lower    upper\n  Control                 43 0.86           7 0.14  1.000000       NA       NA\n  Intervention            31 0.62          19 0.38  2.714286 1.253168 5.878978\n              Outcome\nTreatment         p.value\n  Control              NA\n  Intervention 0.01129646\n\n$measure\n[1] \"wald\"\n\n$conf.level\n[1] 0.95\n\n$pvalue\n[1] \"fisher.exact\"\n```\n\n\n:::\n:::\n\n\nThe risk ratio is 2.71, with 95% CI: (1.24, 5.88).\n\n5.\tResearchers studied the effect of cranberry juice in the treatment and prevention of Helicobacter pylori infection in mice. Researchers compared treatment with cranberry juice to “triple therapy (amoxicillin, bismuth subcitrate, and metronidazole) in mice infected with Helicobacter pylori. After 4 weeks, they examined the mice to determine the frequency of eradication of the bacterium in the two treatment groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrct <- expand.grid(Treatment = c(\"Triple\",\"Cranberry\"),Outcome=c(\"Yes\",\"No\"))\n\nrct$Count <- c(8,2,2,8)\n\ncrosstabs <- xtabs(Count~Treatment+Outcome,data=rct)\ncrosstabs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Outcome\nTreatment   Yes No\n  Triple      8  2\n  Cranberry   2  8\n```\n\n\n:::\n:::\n\n\n \na.\tCalculate the expected values based on the assumption of homogeneity. [2pts.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctest <- chisq.test(crosstabs)\nctest$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Outcome\nTreatment   Yes No\n  Triple      5  5\n  Cranberry   5  5\n```\n\n\n:::\n:::\n\n\nb.\tDoes the chi-squared assumption hold? [1pt.]\n\nThe expected values of each cell is equal to 5, which is a boundary case. The expected values are not greater than 5, hence the chi-squared distribution assumption might not hold. \n\nc.\tPerform the appropriate test to test for an association between treatment and the outcome. [2pts.] Hint: Exact tests are used for small expected counts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfishtest <- fisher.test(crosstabs)\nfishtest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  crosstabs\np-value = 0.02301\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n   1.309537 239.395560\nsample estimates:\nodds ratio \n  13.25038 \n```\n\n\n:::\n:::\n\nThe p-value is 0.0230141, which is lower than 0.05. We reject the null hypothesis. There is sufficient evidence of an association between treatment and eradication of *H. pylori*.\n\n\n\n",
    "supporting": [
      "PS9_key_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}