{
  "hash": "1d32481be6ee1a96bad431a3692249d1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Selected Nonparametric Methods\"\nsubtitle: Lecture 11\nformat:\n  revealjs:\n    theme: clean.scss\n    scrollable: true\n    footer: \"Lecture 11 - [Back to home](https://madfudolig.quarto.pub/introtobiostats/)\"\n    code-block-bg: true\n    code-block-border-left: \"#31BAE9\"\n    slide-number: true\n    menu: true\n    code-annotations: hover\n    chalkboard: true\n    engine: knitr\n    echo: true\n    code-fold: false\n    \n  pdf: \n    number-sections: true\n    geometry:\n      - landscape\n      - margin=1in\n    include-in-header:\n      text: |\n        \\usepackage{titlesec}\n        \\titleformat{\\section}{\\normalfont\\large\\bfseries}{\\thesection}{1em}{}\n        \\titleformat{\\subsection}{\\normalfont\\large\\bfseries}{\\thesubsection}{1em}{}\n        \\titleformat{\\subsubsection}{\\normalfont\\normalsize\\bfseries}{\\thesubsubsection}{1em}{}\n        \n        % Syntax: \\titlespacing{command}{left-sep}{before-sep}{after-sep}\n        \\titlespacing{\\section}{0pt}{12pt}{12pt}\n        % \\titlespacing{\\subsection}{0pt}{3in}{12pt}\n        \\titlespacing{\\subsubsection}{0pt}{3in}{10pt}\n        \n        % This forces a clearpage before every subsection\n        \\let\\oldsubsection\\subsection\n        \\renewcommand{\\subsection}{\\clearpage\\oldsubsection}\n        \nbibliography: references.bib\n---\n\n# Outline\n\n- Nonparametric Statistics\n- Test for Normality\n- One-Sample Wilcoxon Test\n- Paired-Sample Test\n- Two-Sample  Test\n- Kruskal-Wallis Test\n- Spearman Correlation\n\n# Nonparametric Statistics\n\n## What is Non-Parametric Statistics?\n\nMost of the inferential statistical procedures we have discussed so far can be classified as *parametric methods*.\n\n::: callout-note\nParametric methods are based on statistical parameters like the mean, proportion, or variance.\n\nAn examle of a test that did not use any statistical parameter assumption are the chi-square tests.\n:::\n\n## Nonparametric Tests\n\n:::: panel-tabset\n### Advantages\n\n::: callout-note\n## Unknown form of sampled population\nNonparametric tests allow us to develop tests that do not involve parameters. Hence, they may be used when the form of the sampled population is unknown.\n:::\n\n::: callout-note\n## Small Sample Size\nNonparametric tests can be applied to small data sets and are generally easy to do computationally.\n:::\n\n### Disadvantages\n\n::: callout-note\n## Lower power\nNonparametric tests may have less power compared to some parametric tests.\n:::\n\n::: callout-note\n## Economics of Scale\nNonparametric tests may be tedious to apply to large data sets.\n:::\n\n::: callout-note\n## Ties\nFor rank-based tests, some methods assume that there are no \"ties\" in ranking, hence adjustments need to be performed if ties are present.\n:::\n::::\n\n# Tests for Normality\n\n## Formal Tests for Normality\n\nThere are nonparametric tests that can be used to test if a variable measured in a data set follow a Gaussian distribution.\n\n::: callout-note\nThe Shapiro-Wilks test is a common test for normality. \n\nThe Kolgomorov-Smirnov (K-S),Anderson-Darling and Lilliefors tests are also used.\n:::\n\n::: panel-tabset\n### Notes about K-S\n\nThe K-S test can be used for any given reference probability distribution or to compare if two samples came from the same distribution.\n\n### Lilliefors Test\n\nThe Lilliefors test is an improvement on the K-S test for the normality assumption.\n:::\n\n\n## Statistical Hypotheses\n::: callout-important\n\nFor all these tests, the null hypothesis is that the data follow the normal distribution. The alternative hypothesis is that the data does not follow the normal distribution.\n\nRejecting the null hypothesis means we have sufficient evidence of a deviation from the normal distribution.\n:::\n\n## `R` implementation\n\nThe Kolgomorov-Smirnov test can be implemented using the `ks.test()` function in `R`.\n\n# One-Sample tests\n\n## Wilcoxon Signed-Rank Test for Location\n\nThe Wilcoxon Signed-Rank Test for Location is used when we want to test a mean, but neither $z$ or $t$ are appropriate.\n\n::: callout-note\n## Assumptions\n\nThe Wilcoxon test assumes the following about the data:\n\n- The sample is random\n- The random variable is continuous\n- The population is symmetric about its mean.\n- The measurement scale is at least interval.\n:::\n\n## Statistical Hypotheses\n\nUnlike the one-sample t-test or z-test that hypothesize about the mean, the hypothesis of the one-sample Wilcoxon test involves the median (assuming the symmetry assumption holds).\n\nThe null hypothesis is that the median of the data set, $\\tilde{\\mu}$ is equal to a null value $\\tilde{\\mu}_0$.\n\n$$\nH_0: \\tilde{\\mu}=\\tilde{\\mu}_0\n$$\n\nThe alternative can be one-sided ($\\tilde{\\mu}> \\tilde{\\mu}_0$ or $\\tilde{\\mu}< \\tilde{\\mu}_0$) or two-sided ($\\tilde{\\mu}\\neq \\tilde{\\mu}_0$).\n\n## How it Works\n\n- The difference between the data points and the null value are calculated\n- These differences are then ranked from highest to lowest. If the difference is zero, it is ignored.\n- Reapply the original signs to these ranks\n- Sum the positive and negative ranks to obtain the test statistic.\n- The test statistic is the lower value between the absolute value of the sums of the positive and negative ranks.\n\n## `R` Implementation\n\nThe `wilcox.test()` function can be used to perform a one-sample Wilcoxon-test in `R`. For a vector x in a data frame `df` and a null value `m0`, an example code of a two-sided test can be written as\n\n\n```{.r}\nwilcox.test(df$x,mu=mu0,alternative=\"two.sided\")\n```\n\n## Example\n\nConsider the sleep health data set in `SleepHealthData.csv`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --\nv dplyr     1.1.4     v readr     2.1.5\nv forcats   1.0.0     v stringr   1.5.1\nv ggplot2   4.0.0     v tibble    3.3.0\nv lubridate 1.9.4     v tidyr     1.3.1\nv purrr     1.1.0     \n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\ni Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nsleep <- read.csv(\"SleepHealthData.csv\")\nglimpse(sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 374\nColumns: 13\n$ person_id               <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,~\n$ gender                  <chr> \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"Male\"~\n$ age                     <int> 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29~\n$ occupation              <chr> \"Software Engineer\", \"Doctor\", \"Doctor\", \"Sale~\n$ sleep_duration          <dbl> 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7~\n$ quality_of_sleep        <int> 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6~\n$ physical_activity_level <int> 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75~\n$ stress_level            <int> 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8~\n$ bmi_category            <chr> \"Overweight\", \"Normal\", \"Normal\", \"Obese\", \"Ob~\n$ blood_pressure          <chr> \"126/83\", \"125/80\", \"125/80\", \"140/90\", \"140/9~\n$ heart_rate              <int> 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70~\n$ daily_steps             <int> 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80~\n$ sleep_disorder          <chr> \"None\", \"None\", \"None\", \"Sleep Apnea\", \"Sleep ~\n```\n\n\n:::\n:::\n\n::: panel-tabset\n### Question\nUse the one-sample Wilcoxon test to test whether the median \nstress level for the sampled population is higher than 4.5. \n\n### Answer\n\nThe statistical hypothesis can be written as:\n\n$$\nH_0: \\tilde{\\mu}=4.5; H_a: \\tilde{\\mu}> 4.5\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwtest <- wilcox.test(sleep$stress_level,mu=4.5,alternative = \"greater\")\nwtest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  sleep$stress_level\nV = 51379, p-value = 1.556e-15\nalternative hypothesis: true location is greater than 4.5\n```\n\n\n:::\n:::\n\nThe p-value is \\ensuremath{1.5555249\\times 10^{-15}}, which is less than 0.05. We reject the null hypothesis. We have sufficient evidence that the median stress level of the sampled population is greater than 4.5.\n\nWe can also visually check if this makes sense using a box plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=sleep,aes(x=NULL,y=stress_level)) + \n  geom_boxplot() + \n  geom_hline(aes(yintercept=4.5),color=\"red\")+\n  theme_bw() + \n  labs(y=\"Stress Level\")\n```\n\n::: {.cell-output-display}\n![](lecture11_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n:::\n\n## Notes\n\nIf the assumption about the symmetry of the data set is not satisfied, the Wilcoxon test might have faulty results about the inference involving medians.\n\n:::: panel-tabset\n### Warning\n::: callout-warning\nNote that the test statistic is based on the ranked differences and that zero differences are ignored. This means that if the data is asymmetric and the assumed median is part of the data set, it might lead to a significant result even if the medians are the same.\n\nIf we are interested in a pure test of medians for a skewed sample, the **sign test** might be a better alternative.\n:::\n### Sign test\n\nThe `BSDA` package includes the `SIGN.test()` function that can be used to run the sign test.\n::::\n\n## Exercise\n\nConsider the sleep health data set in `SleepHealthData.csv`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nsleep <- read.csv(\"SleepHealthData.csv\")\nglimpse(sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 374\nColumns: 13\n$ person_id               <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,~\n$ gender                  <chr> \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"Male\"~\n$ age                     <int> 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29~\n$ occupation              <chr> \"Software Engineer\", \"Doctor\", \"Doctor\", \"Sale~\n$ sleep_duration          <dbl> 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7~\n$ quality_of_sleep        <int> 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6~\n$ physical_activity_level <int> 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75~\n$ stress_level            <int> 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8~\n$ bmi_category            <chr> \"Overweight\", \"Normal\", \"Normal\", \"Obese\", \"Ob~\n$ blood_pressure          <chr> \"126/83\", \"125/80\", \"125/80\", \"140/90\", \"140/9~\n$ heart_rate              <int> 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70~\n$ daily_steps             <int> 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80~\n$ sleep_disorder          <chr> \"None\", \"None\", \"None\", \"Sleep Apnea\", \"Sleep ~\n```\n\n\n:::\n:::\n\n::: panel-tabset\n### Question\nUse the one-sample Wilcoxon test to test whether the median \nphysical activity level for the sampled population is not equal to 60.\n\n### Answer\n\nThe statistical hypothesis can be written as:\n\n$$\nH_0: \\tilde{\\mu}=60; H_a: \\tilde{\\mu}\\neq 60\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwtest <- wilcox.test(sleep$physical_activity_level,mu=60,alternative = \"two.sided\")\nwtest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  sleep$physical_activity_level\nV = 22196, p-value = 0.5121\nalternative hypothesis: true location is not equal to 60\n```\n\n\n:::\n:::\n\nWe can also visually check if this makes sense using a box plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=sleep,aes(x=NULL,y=physical_activity_level)) + \n  geom_boxplot() + \n  geom_hline(aes(yintercept=60),color=\"red\")+\n  theme_bw() +\n  labs(y=\"Physical Activity Level\")\n```\n\n::: {.cell-output-display}\n![](lecture11_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n# Paired-Samples Test\n\n## Paired-Samples Test\n\nthe Wilcoxon signed-rank test can be used to test for a difference between paired samples. \n\n::: callout-note\nThis is the non-parametric equivalent of a paired t-test.\n:::\n\n## Statistical Hypotheses\n\nThe hypothesis of the paired-sample Wilcoxon signed rank test involves the median of the paired difference.\n\nThe null hypothesis is that the median of the data set, $\\tilde{\\mu}_d$ is equal to a null value $\\tilde{\\mu}_{d,0}$.\n\n$$\nH_0: \\tilde{\\mu}_d=\\tilde{\\mu}_{d,0}\n$$\n\nThe alternative can be one-sided ($\\tilde{\\mu}_d>\\tilde{\\mu}_{d,0}$ or $\\tilde{\\mu}_d<\\tilde{\\mu}_{d,0}$) or two-sided ($\\tilde{\\mu}_d\\neq\\tilde{\\mu}_{d,0}$).\n\n::: callout-tip\nThe null value commonly used is 0 (null hypothesis of equality).\n:::\n\n## `R` Implementation\n\nThe `wilcox.test()` can also be used for paired data. For a data frame `df` with paired data `x1` and `x2` and a one-sided \"less\" alternative hypothesis , the sample code would look like:\n\n```{.r}\nwilcox.test(x=df$x1,y=df$x2,paired=T,alternative=\"less\")\n```\n\n## Example\n\nThe following data set `example` shows data from research that investigated the possible beneficial effects of singing on wellbeing during a single singing lesson. One of the variables of interest was the change in cortisol as a result of the singing lesson. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nexample <- data.frame(\n  before=c(214,362,202,158,403,219,307,331),\n  after=c(232,276,224,412,562,203,340,313)\n)\nglimpse(example)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8\nColumns: 2\n$ before <dbl> 214, 362, 202, 158, 403, 219, 307, 331\n$ after  <dbl> 232, 276, 224, 412, 562, 203, 340, 313\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### Question\n\nUse the Wilcoxon Signed-Rank Test to test whether the cortisol levels increased after singing.\n\n### Answer\n\nThe alternative hypothesis is one-sided because of the direction assumed in the problem. We assume that $\\tilde{\\mu}_d$ is calculated as `before`-`after` Hence, the hypotheses can be written as:\n\n$$\nH_0: \\tilde{\\mu}_d=0;H_0: \\tilde{\\mu}_d>0\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwtest <- wilcox.test(x=example$before,y=example$after,paired=T,alternative=\"less\",correct=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = example$before, y = example$after, paired =\nT, : cannot compute exact p-value with ties\n```\n\n\n:::\n\n```{.r .cell-code}\nwtest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  example$before and example$after\nV = 9.5, p-value = 0.131\nalternative hypothesis: true location shift is less than 0\n```\n\n\n:::\n:::\n\nThe resulting Wilcoxon test p-value is 0.1310164. We fail to reject the null hypothesis at the significance level of 0.05. We have insufficient evidence to claim that the cortisol levels increased after singing.\n\n\n:::\n\n## Exercise\n\nThe data set `anorexia` from the package `MASS` contains weight change data for young female anorexia patients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'MASS'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    select\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\nglimpse(anorexia)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 72\nColumns: 3\n$ Treat  <fct> Cont, Cont, Cont, Cont, Cont, Cont, Cont, Cont, Cont, Cont, Con~\n$ Prewt  <dbl> 80.7, 89.4, 91.8, 74.0, 78.1, 88.3, 87.3, 75.1, 80.6, 78.4, 77.~\n$ Postwt <dbl> 80.2, 80.1, 86.4, 86.3, 76.1, 78.1, 75.1, 86.7, 73.5, 84.6, 77.~\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### Question\n\nPerform a paired-sample non-parametric test to test whether there is a difference between the preweight `prewt` and `postwt` for all patients, disregarding the type of treatment. Use a significance level of 0.05.\n\n### Answer\n\nThe alternative hypothesis is two-sided. We assume that $\\tilde{\\mu}_d$ is calculated as `Postwt`-`Prewt` Hence, the hypotheses can be written as:\n\n$$\nH_0: \\tilde{\\mu}_d=0;H_0: \\tilde{\\mu}_d\\neq 0\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwtest <- wilcox.test(x=anorexia$Postwt,y=anorexia$Prewt,paired=T,alternative=\"two.sided\")\nwtest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  anorexia$Postwt and anorexia$Prewt\nV = 1724.5, p-value = 0.0106\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nThe p-value is 0.0106022. We reject the null hypothesis at the 0.05 level of significance. There is sufficient evidence to conclude that there is a difference in post-weight and pre-weight scores across the sample.\n:::\n\n\n# Two-Sample Test\n\n## Mann-Whitney U Test\n\nThe Mann-Whitney U Test is equivalent to the two-sample Wilcoxon test. \n\n::: callout-note\n## Assumptions\n\nThe Mann-Whitney test assumes the following:\n\n- The two samples are independent and randomly drawn from their respective populations\n- The measurement scale is at least ordinal\n- The variable of interest is continuous\n- If the populations differ at all, they differ only with respect to their medians.\n:::\n\n## Statistical Hypotheses\n\nThe null hypothesis for the Mann-Whitney U test is that there is no difference between the distribution of the two independent groups. \n\n::: callout-note\nThe distribution can be measured using the median or sometimes, the mean of the ranks.\n\n:::\n\nThe alternative hypotheses can be:\n\n- One-sided: One group tends to have higher or lower values than the other\n- Two-sided: There is a difference between the distributions of the two groups.\n\n## The $U$ Statistic\n\nTo calculate the test statistic: \n\n- Assign ranks to the values from the two groups pooled together in order from smallest to largest.\n- Sum the ranks of each group.\n- Calculate the $U_j$ value as:\n\n$$\nU_1 = n_1n_2 + n_1(n_1+1)/2 - \\sum_iR_{i1}\n$$\n\n$$\nU_2 = n_1n_2 + n_2(n_2+1)/2 - \\sum_iR_{i2}\n$$\n\n- The test statistic is the lower value between $U_1$ and $U_2$.\n\n## `R` implementation\n\nThe `wilcox.test()` function can implement the Mann-Whitney U test for independent groups. The syntax is similar to the paired-samples test but specifying that `paired=FALSE`.\n\n```{.r}\nwilcox.test(x=df$x1,y=df$x2,alternative=\"less\")\n```\n\nIf the grouping variable and the response variables are defined as two distinct columns, we can use the formula notation as well.\n\n```{.r}\nwilcox.test(response~grouping,data=df,alternative=\"less\")\n```\n\n## Example\n\nConsider the data set `SleepHealthData.csv`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep <- read.csv(\"SleepHealthData.csv\")\nglimpse(sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 374\nColumns: 13\n$ person_id               <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,~\n$ gender                  <chr> \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"Male\"~\n$ age                     <int> 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29~\n$ occupation              <chr> \"Software Engineer\", \"Doctor\", \"Doctor\", \"Sale~\n$ sleep_duration          <dbl> 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7~\n$ quality_of_sleep        <int> 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6~\n$ physical_activity_level <int> 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75~\n$ stress_level            <int> 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8~\n$ bmi_category            <chr> \"Overweight\", \"Normal\", \"Normal\", \"Obese\", \"Ob~\n$ blood_pressure          <chr> \"126/83\", \"125/80\", \"125/80\", \"140/90\", \"140/9~\n$ heart_rate              <int> 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70~\n$ daily_steps             <int> 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80~\n$ sleep_disorder          <chr> \"None\", \"None\", \"None\", \"Sleep Apnea\", \"Sleep ~\n```\n\n\n:::\n:::\n\n::: panel-tabset\n### Question\n\nUse the Mann-Whitney U test to determine if there is a difference in quality of sleep between males and females.\n\n### Answer\n\nThe alternative hypothesis should be two-sided because of the lack of directionality specified in the difference that we want to detect.\n\nThe null hypothesis is that there is no difference in quality of sleep between males and females, while the alternative hypothesis is that there is a difference in quality of sleep between males and females.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwtest<- wilcox.test(quality_of_sleep~gender,data=sleep,alternative=\"two.sided\")\nwtest \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  quality_of_sleep by gender\nW = 23369, p-value = 6.048e-09\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\nThe resulting p-value is \\ensuremath{6.0476062\\times 10^{-9}}. We reject the null hypothesis. We have sufficient evidence to conclude that there is a difference in quality of sleep between males and females.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=sleep,aes(x=gender,y=quality_of_sleep))+\n  geom_boxplot() + \n  theme_bw() + \n  labs(y=\"Quality of Sleep\",x=\"Gender\")\n```\n\n::: {.cell-output-display}\n![](lecture11_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n### Violin Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=sleep,aes(x=gender,y=quality_of_sleep))+\n  geom_violin() + \n  theme_bw() + \n  labs(y=\"Quality of Sleep\",x=\"Gender\")\n```\n\n::: {.cell-output-display}\n![](lecture11_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n:::\n\n## Exercise\n\nConsider the sleep health data set `SleepHealthData.csv`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep <- read.csv(\"SleepHealthData.csv\")\nglimpse(sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 374\nColumns: 13\n$ person_id               <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,~\n$ gender                  <chr> \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"Male\"~\n$ age                     <int> 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29~\n$ occupation              <chr> \"Software Engineer\", \"Doctor\", \"Doctor\", \"Sale~\n$ sleep_duration          <dbl> 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7~\n$ quality_of_sleep        <int> 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6~\n$ physical_activity_level <int> 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75~\n$ stress_level            <int> 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8~\n$ bmi_category            <chr> \"Overweight\", \"Normal\", \"Normal\", \"Obese\", \"Ob~\n$ blood_pressure          <chr> \"126/83\", \"125/80\", \"125/80\", \"140/90\", \"140/9~\n$ heart_rate              <int> 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70~\n$ daily_steps             <int> 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80~\n$ sleep_disorder          <chr> \"None\", \"None\", \"None\", \"Sleep Apnea\", \"Sleep ~\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### Question\n\nUse the Mann-Whitney U test to determine if there is a difference in daily steps between males and females.\n\n### Answer\n\nThe alternative hypothesis should be two-sided because of the lack of directionality specified in the difference that we want to detect.\n\nThe null hypothesis is that there is no difference in daily number of steps between males and females, while the alternative hypothesis is that there is a difference in daily number of steps between males and females.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwtest<- wilcox.test(daily_steps~gender,data=sleep,alternative=\"two.sided\")\nwtest \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  daily_steps by gender\nW = 15890, p-value = 0.1203\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nThe resulting p-value is 0.1203365. We fail to reject the null hypothesis at the 0.05 level of significance. We have insufficient evidence to conclude that there is a difference in number of daily steps between males and females.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=sleep,aes(x=gender,y=daily_steps))+\n  geom_boxplot() + \n  theme_bw() + \n  labs(y=\"Number of Steps (Daily)\",x=\"Gender\")\n```\n\n::: {.cell-output-display}\n![](lecture11_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n### Violin Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=sleep,aes(x=gender,y=daily_steps))+\n  geom_violin() + \n  theme_bw() + \n  labs(y=\"Number of Steps (Daily)\",x=\"Gender\")\n```\n\n::: {.cell-output-display}\n![](lecture11_files/figure-pdf/unnamed-chunk-18-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n:::\n\n# ANOVA-like Tests\n\n## ANOVA-like tests\n\nThere are non-parametric tests that compare the distributions of more than two groups.\n\n::: callout-important\nThe Kruskal-Wallis Rank Sum test works similarly to the one-way ANOVA, while the Friedman's test works similarly to the two-way ANOVA. Both use assumptions that are the same as the Mann-Whitney test for two independent samples.\n:::\n\n## Statistical Hypotheses: Kruskal-Wallis Test\n\nThe null hypothesis of the Kruskal-Wallis Rank Sum Test states that there is no difference in the distribution of the response variable across the different groups. \n\nThe alternative hypothesis states that there is at least one group that has a different distribution of the response variable across the different groups.\n\n::: callout-note\nThis can be stated in terms of medians, similar to how ANOVA was stated in terms of means.\n:::\n\n## `R` implementation\n\nThe `kruskal.test()` function implements the Kruskal-Wallis test. The function works best with the formula notation.\n\n```{.r}\nkruskal.test(response~group,data=df)\n```\n\n## Example\n\nConsider the `penguins` data set in `R`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 344\nColumns: 8\n$ species     <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Ad~\n$ island      <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Tor~\n$ bill_len    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, 42.0, ~\n$ bill_dep    <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, 20.2, ~\n$ flipper_len <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186, 180,~\n$ body_mass   <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, 4250, ~\n$ sex         <fct> male, female, female, NA, female, male, female, male, NA, ~\n$ year        <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007~\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### Question\n\nUse the Kruskal-Wallis test to test for a difference between the body mass across the different years (2007,2008,2009).\n\n### Answer\n\nThe null hypothesis is that there is no difference in the distribution of body mass of the penguins across the different years. The alternative is that at least one year is different from the others.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nktest <- kruskal.test(body_mass~as.factor(year),data=penguins)\nktest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  body_mass by as.factor(year)\nKruskal-Wallis chi-squared = 2.5523, df = 2, p-value = 0.2791\n```\n\n\n:::\n:::\n\nThe resulting p-value is 0.279111. At 0.05 level of significance, we fail to reject the null hypothesis. We have insufficient evidence that there is at least one year with a different distribution of body mass compared to the others.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=penguins,aes(x=as.factor(year),y=body_mass)) + \n  geom_boxplot() + \n  theme_bw() + \n  labs(x=\"Year\",y=\"Body Mass of Penguins\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lecture11_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Violin Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=penguins,aes(x=as.factor(year),y=body_mass)) + \n  geom_boxplot() +\n  geom_violin(aes(fill=as.factor(year)),alpha=0.5) + \n  theme_bw() + \n  labs(x=\"Year\",y=\"Body Mass of Penguins\",fill=\"Year\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite outside the scale range\n(`stat_ydensity()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lecture11_files/figure-pdf/unnamed-chunk-22-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n## Exercise\n\nConsider the `iris` data set in `R`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 150\nColumns: 5\n$ Sepal.Length <dbl> 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.~\n$ Sepal.Width  <dbl> 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.~\n$ Petal.Length <dbl> 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.~\n$ Petal.Width  <dbl> 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.~\n$ Species      <fct> setosa, setosa, setosa, setosa, setosa, setosa, setosa, s~\n```\n\n\n:::\n:::\n\n::: panel-tabset\n### Question\n\nUse the Kruskal-Wallis test to test for a difference between the petal widths of the species of iris.\n\n### Answer\n\nThe null hypothesis is that there is no difference in petal widths of the species of iris. the alternative hypothesis is that there is at least one species that has a different distribution of petal widths compared to the others.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nktest <- kruskal.test(Petal.Width~Species,data=iris)\nktest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  Petal.Width by Species\nKruskal-Wallis chi-squared = 131.19, df = 2, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe p-value is \\ensuremath{3.2617956\\times 10^{-29}}. At the 0.05 level of significance, we reject the null hypothesis. We have sufficient evidence that at least one species has a different distribution of petal widths compared to the others.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=iris,aes(x=Species,y=Petal.Width)) + \n  geom_boxplot() + \n  theme_bw() + \n  labs(x=\"Species\",y=\"Petal Width\")\n```\n\n::: {.cell-output-display}\n![](lecture11_files/figure-pdf/unnamed-chunk-25-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Violin Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=iris,aes(x=Species,y=Petal.Width)) + \n  geom_boxplot() +\n  geom_violin(aes(fill=Species),alpha=0.5) + \n  scale_fill_discrete(palette=\"viridis\") +\n  theme_bw() + \n  labs(x=\"Species\",y=\"Petal Width\",fill=\"Species\")\n```\n\n::: {.cell-output-display}\n![](lecture11_files/figure-pdf/unnamed-chunk-26-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n# Non-Parametric Correlation Tests\n\n## Spearman Correlation\n\nRecall Lecture 9: The Spearman correlation coefficient is a measure of association that measures monotonic correlation between the two variables.\n\n::: callout-important\nThe Spearman correlation coefficient is based on the data ranks, and can be used if the Pearson correlation assumptions are not met.\n:::\n\n## Statistical Hypotheses\n\nThe null hypothesis is that there is no association between the two variables. The alternative hypothesis can be one-sided (negative or positive association) or two-sided (there is an association).\n\n## `R` Implementation\n\nThe function `cor.test()` can perform a test for the Spearman correlation, as long as the method is specified.\n\n::: callout-warning\nIf the method (`method=\"spearman\"`) is unspecified, `cor.test()` defaults to the Pearson correlation coefficient.\n:::\n\n```{.r}\ncor.test(df$x,df$y,alternative=\"two.sided\",method=\"spearman\")\n```\n\n## Example\n\nConsider the sleep health data set `SleepHealthData.csv`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nsleep <- read.csv(\"SleepHealthData.csv\")\nglimpse(sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 374\nColumns: 13\n$ person_id               <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,~\n$ gender                  <chr> \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"Male\"~\n$ age                     <int> 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29~\n$ occupation              <chr> \"Software Engineer\", \"Doctor\", \"Doctor\", \"Sale~\n$ sleep_duration          <dbl> 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7~\n$ quality_of_sleep        <int> 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6~\n$ physical_activity_level <int> 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75~\n$ stress_level            <int> 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8~\n$ bmi_category            <chr> \"Overweight\", \"Normal\", \"Normal\", \"Obese\", \"Ob~\n$ blood_pressure          <chr> \"126/83\", \"125/80\", \"125/80\", \"140/90\", \"140/9~\n$ heart_rate              <int> 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70~\n$ daily_steps             <int> 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80~\n$ sleep_disorder          <chr> \"None\", \"None\", \"None\", \"Sleep Apnea\", \"Sleep ~\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### Question\n\nCalculate the Spearman correlation coefficient between the daily steps and sleep duration. Test for an association at the 0.01 level of significance.\n\n### Answer\n\nThe null hypothesis is that there is no association between daily steps and sleep duration, while the alternative hypothesis is that there is an association between daily steps and sleep duration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctest <- cor.test(sleep$daily_steps,sleep$sleep_duration,alternative=\"two.sided\",method=\"spearman\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in cor.test.default(sleep$daily_steps, sleep$sleep_duration,\nalternative = \"two.sided\", : Cannot compute exact p-value with ties\n```\n\n\n:::\n\n```{.r .cell-code}\nctest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  sleep$daily_steps and sleep$sleep_duration\nS = 8630931, p-value = 0.8458\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n0.01008658 \n```\n\n\n:::\n:::\n\n\nThe estimate of the Spearman correlation coefficient is 0.0101, corresponding to a p-value of 0.8458492. We fail to reject the null hypothesis. There is insufficient evidence of an association between the daily number of steps and sleep duration.\n\n:::\n\n## Exercise\n\nConsider the sleep health data set `SleepHealthData.csv`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nsleep <- read.csv(\"SleepHealthData.csv\")\nglimpse(sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 374\nColumns: 13\n$ person_id               <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,~\n$ gender                  <chr> \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"Male\"~\n$ age                     <int> 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29~\n$ occupation              <chr> \"Software Engineer\", \"Doctor\", \"Doctor\", \"Sale~\n$ sleep_duration          <dbl> 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7~\n$ quality_of_sleep        <int> 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6~\n$ physical_activity_level <int> 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75~\n$ stress_level            <int> 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8~\n$ bmi_category            <chr> \"Overweight\", \"Normal\", \"Normal\", \"Obese\", \"Ob~\n$ blood_pressure          <chr> \"126/83\", \"125/80\", \"125/80\", \"140/90\", \"140/9~\n$ heart_rate              <int> 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70~\n$ daily_steps             <int> 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80~\n$ sleep_disorder          <chr> \"None\", \"None\", \"None\", \"Sleep Apnea\", \"Sleep ~\n```\n\n\n:::\n:::\n\n\n\n::: panel-tabset\n### Question\n\nCalculate the Spearman correlation coefficient between the daily steps and quality of sleep. Test for an association at the 0.01 level of significance.\n\n### Answer\n\n\nThe null hypothesis is that there is no association between daily steps and quality of sleep, while the alternative hypothesis is that there is an association between daily steps and quality of sleep\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctest <- cor.test(sleep$daily_steps,sleep$quality_of_sleep,alternative=\"two.sided\",method=\"spearman\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in cor.test.default(sleep$daily_steps, sleep$quality_of_sleep,\nalternative = \"two.sided\", : Cannot compute exact p-value with ties\n```\n\n\n:::\n\n```{.r .cell-code}\nctest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  sleep$daily_steps and sleep$quality_of_sleep\nS = 8520266, p-value = 0.6606\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n0.02277921 \n```\n\n\n:::\n:::\n\n\nThe estimate of the Spearman correlation coefficient is 0.0228, corresponding to a p-value of 0.6605808. We fail to reject the null hypothesis. There is insufficient evidence of an association between the daily number of steps and quality of sleep.\n:::\n",
    "supporting": [
      "lecture11_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}