<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>EAB 703-1002: Biostatistical Methods for the Health Sciences – Analysis of Frequencies</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-12873a65cf666e61daa4b3cf91a98e13.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Analysis of Frequencies</h1>
  <p class="subtitle">Lecture 10</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="outline" class="title-slide slide level1 center">
<h1>Outline</h1>
<ul>
<li>Introduction to Categorical Data</li>
<li>Goodness-of-Fit Tests</li>
<li>Test of Homogeneity</li>
<li>Test of Independence</li>
<li>Fisher’s Exact Test</li>
<li>Symmetry Tests</li>
<li>Measures of Association</li>
</ul>
</section>

<section>
<section id="categorical-data" class="title-slide slide level1 center">
<h1>Categorical Data</h1>

</section>
<section id="associations-between-categorical-data" class="slide level2">
<h2>Associations between Categorical Data</h2>
<p>Often, we are interested in testing for association between categorical data. These variables can be nominal or ordinal.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Suppose we want to test whether there is an association between the type of hospital a patient is admitted to and their diagnosed conditions.</p>
</div>
</div>
</div>
</section>
<section id="contingency-tables" class="slide level2">
<h2>Contingency Tables</h2>
<p>A contingency table is a table of frequencies or counts for each possible combination of the variables.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Example</strong></p>
</div>
<div class="callout-content">
<p>The hair and eye color of male statistics students were measured. The findings were summarized in the following contingency table.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       Eye
Hair    Brown Blue Hazel Green
  Black    32   11    10     3
  Brown    53   50    25    15
  Red      10   10     7     7
  Blond     3   30     5     8</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="contingency-tables-in-r" class="slide level2">
<h2>Contingency tables in <code>R</code></h2>
<p>You can use <code>xtabs()</code> to produce contingency tables in <code>R</code>. The data should be formatted such that the two variables are defined by two columns. If these columns are <code>x</code> and <code>y</code> from a data frame <code>df</code>, the sample code would look like:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">xtabs</span>(<span class="sc">~</span>x<span class="sc">+</span>y,<span class="at">data=</span>df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>x</code> will be assigned as the row variable, <code>y</code> will be assigned as the column variable.</p>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<p>The data set <code>penguins</code> preloaded in <code>R</code> includes data from penguins at the Palmer Archipelago in Antarctica.</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Question</a></li><li><a href="#tabset-1-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<p>Create a contingency table for this data that summarizes the number of penguins belonging to each species and sex.</p>
</div>
<div id="tabset-1-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">xtabs</span>(<span class="sc">~</span>species<span class="sc">+</span>sex,<span class="at">data=</span>penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           sex
species     female male
  Adelie        73   73
  Chinstrap     34   34
  Gentoo        58   61</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="chi-squared-distribution" class="slide level2">
<h2>Chi-Squared Distribution</h2>
<p>Tests involving categorical data use the chi-squared distribution to approximate the distribution of the test statistics.</p>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Support</a></li><li><a href="#tabset-2-2">Parameter</a></li><li><a href="#tabset-2-3">Relation to Gaussian Distribution</a></li><li><a href="#tabset-2-4">Mean and Variance</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p>The chi-squared distribution is defined for non-negative values <span class="math inline">\((0,\infty)\)</span>.</p>
</div>
<div id="tabset-2-2">
<p>The chi-squared distribution can be defined by the degrees of freedom <span class="math inline">\(\nu\)</span> or <span class="math inline">\(df\)</span>.</p>
<p>Like the t-distribution, we only need one value for the degree of freedom.</p>
</div>
<div id="tabset-2-3">
<p>Suppose <span class="math inline">\(Z\)</span> follows the standard Gaussian distribution N(0,1). Then <span class="math inline">\(Z^2\)</span> follows a chi-square distribution with 1 degree of freedom.</p>
</div>
<div id="tabset-2-4">
<p>The mean of the chi-squared distribution is <span class="math inline">\(k\)</span>, and the variance of the chi-squared distribution is <span class="math inline">\(2k\)</span>.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="goodness-of-fit-tests" class="title-slide slide level1 center">
<h1>Goodness-of-Fit Tests</h1>

</section>
<section id="goodness-of-fit" class="slide level2">
<h2>Goodness of Fit</h2>
<p>Suppose we want to test if the data follows a specified distribution.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Example</strong></p>
</div>
<div class="callout-content">
<p>Suppose we want to know if a six-sided die is fair. We would expect to roll the numbers uniformly after a large number of throws. However, there will be variability due to randomness. The goodness-of-fit test will provide information if we have evidence of deviating from the pre-specified uniform distribution.</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-test" class="slide level2">
<h2>Hypothesis Test</h2>
<p>The null hypothesis of the goodness-of-fit test is that <strong>the observed data follows the specified distribution</strong>, while the alternative is that it does not follow the specified distribution.</p>
</section>
<section id="test-statistic" class="slide level2">
<h2>Test Statistic</h2>
<p>Suppose there are <span class="math inline">\(k\)</span> bins separating the data and that the distribution provides an expected number/counts of events <span class="math inline">\(E_i\)</span> for <span class="math inline">\(i=1,2,...k\)</span>. If the observed number/counts in the data is <span class="math inline">\(O_i\)</span>, we define the test statistics <span class="math inline">\(Q\)</span> such that</p>
<p><span class="math display">\[
Q = \sum_{i=1}^k \frac{(O_i - E_i)^2}{E_i}
\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Q approximately follows the chi-squared distribution with <span class="math inline">\(k-1\)</span> degrees of freedom, denoted by <span class="math inline">\(\chi^2_{k-1}\)</span>.</p>
<p>For the chi-squared distribution assumption to be valid, the expected value of each bin should be greater than 5.</p>
</div>
</div>
</div>
</section>
<section id="p-value-calculation" class="slide level2">
<h2>p-value calculation</h2>
<p>The p-values can be calculated using the chi-squared distribution such that:</p>
<p><span class="math display">\[
p-value = P(\chi^2_{k-1} \geq Q)
\]</span></p>
</section>
<section id="r-implementation" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>There are two ways to check for goodness of fit: formal statistical analysis and exploratory data visualization.</p>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Expected Values</a></li><li><a href="#tabset-3-2">Formal Statistical Analysis</a></li><li><a href="#tabset-3-3">Visualization</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p>For discrete distributions, the expected values can be calculated using the PDF functions ( <code>dpois</code>, <code>dbinom</code>) for discrete distributions, and CDF functions (<code>pnorm</code>,<code>punif</code>, <code>pt</code>).</p>
</div>
<div id="tabset-3-2">
<p>The <code>chisq.test</code> function performs the chi-squared test of goodness of fit. The function needs a vector of the observed variables, <code>x_observed</code> and a vector of probabilities <code>p</code>.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">chisq.test</span>(<span class="at">x=</span>x_observed, <span class="at">p=</span>p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The <code>chisq.test()</code> function includes a continuity correction in calculating the test statistic and the corresponding p-value. If we want the uncorrected statistic and p-value, we need to specify <code>correct=FALSE</code>.</p>
</div>
</div>
</div>
</div>
<div id="tabset-3-3">
<p>Once the expected values are calculated, we can plot these values using <code>ggplot()</code>.</p>
</div>
</div>
</div>
</section>
<section id="example-3" class="slide level2">
<h2>Example</h2>
<p>Electronic integrated circuits are produced from thin wafers that are cut from some material. The wafers produced sometimes have tiny flaws on them that make part of the wafer unusable. Suppose we produce 1000 wafers and for each we determine the number of flaws.</p>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Data</a></li><li><a href="#tabset-4-2">Question</a></li><li><a href="#tabset-4-3">Answer</a></li><li><a href="#tabset-4-4">Plot</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<table class="caption-top">
<thead>
<tr class="header">
<th>Number of Flaws</th>
<th>Observed Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>10</td>
</tr>
<tr class="even">
<td>1</td>
<td>220</td>
</tr>
<tr class="odd">
<td>2</td>
<td>130</td>
</tr>
<tr class="even">
<td>3</td>
<td>80</td>
</tr>
<tr class="odd">
<td>4</td>
<td>60</td>
</tr>
<tr class="even">
<td>5 or more</td>
<td>90</td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-4-2">
<p>Test whether these data follow a Poisson distribution with <span class="math inline">\(\lambda=1.44\)</span>. Visualize the observed and expected counts to support the results of the test.</p>
</div>
<div id="tabset-4-3">
<p>We specify the observed variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>observed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">220</span>,<span class="dv">130</span>,<span class="dv">80</span>,<span class="dv">60</span>,<span class="dv">90</span>)</span>
<span id="cb6-2"><a></a>observed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  10 220 130  80  60  90</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>total <span class="ot">&lt;-</span> <span class="fu">sum</span>(observed)</span>
<span id="cb8-2"><a></a>total</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 590</code></pre>
</div>
</div>
<p>The specified distribution is the Poisson distribution. We can then calculate the expected probabilities using <code>dpois</code> and <code>ppois</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>expected <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb10-2"><a></a><span class="fu">dpois</span>(<span class="dv">0</span>,<span class="at">lambda=</span><span class="fl">1.44</span>),</span>
<span id="cb10-3"><a></a><span class="fu">dpois</span>(<span class="dv">1</span>,<span class="at">lambda=</span><span class="fl">1.44</span>),</span>
<span id="cb10-4"><a></a><span class="fu">dpois</span>(<span class="dv">2</span>,<span class="at">lambda=</span><span class="fl">1.44</span>),</span>
<span id="cb10-5"><a></a><span class="fu">dpois</span>(<span class="dv">3</span>,<span class="at">lambda=</span><span class="fl">1.44</span>),</span>
<span id="cb10-6"><a></a><span class="fu">dpois</span>(<span class="dv">4</span>,<span class="at">lambda=</span><span class="fl">1.44</span>),</span>
<span id="cb10-7"><a></a><span class="dv">1</span><span class="sc">-</span><span class="fu">ppois</span>(<span class="dv">4</span>,<span class="at">lambda=</span><span class="fl">1.44</span>)</span>
<span id="cb10-8"><a></a>)</span>
<span id="cb10-9"><a></a>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.23692776 0.34117597 0.24564670 0.11791042 0.04244775 0.01589140</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">sum</span>(expected) <span class="co"># must be 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a>total<span class="sc">*</span>expected <span class="co"># there should not be more than 1.5 bins that have less than 5 expected counts</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 139.787378 201.293824 144.931553  69.567145  25.044172   9.375928</code></pre>
</div>
</div>
<p>All expected counts are above 5. We can now use the chi-square approximation for the p-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a>chisqtest <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(<span class="at">x=</span>observed,<span class="at">p=</span>expected)</span>
<span id="cb16-2"><a></a>chisqtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  observed
X-squared = 867.42, df = 5, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The test statistic is 867.4246622 with a p-value &lt; 2.2e-16. We reject the null hypothesis. We have sufficient evidence to conclude that the observed data does not follow the Poisson distribution.</p>
</div>
<div id="tabset-4-4">
<p>The function <code>bind_rows</code> appends the expected data frame to the observed data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb18-2"><a></a>df_observed <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">bin =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="st">"5 or more"</span>),<span class="at">y=</span>observed,<span class="at">type=</span><span class="st">"Observed"</span>)</span>
<span id="cb18-3"><a></a>df_expected <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">bin =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="st">"5 or more"</span>),<span class="at">y=</span>total<span class="sc">*</span>expected,<span class="at">type=</span><span class="st">"Expected"</span>)</span>
<span id="cb18-4"><a></a>df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(df_observed,df_expected)</span>
<span id="cb18-5"><a></a></span>
<span id="cb18-6"><a></a><span class="fu">ggplot</span>(df,<span class="fu">aes</span>(<span class="at">x=</span>bin,<span class="at">y=</span>y,<span class="at">group=</span>type,<span class="at">fill=</span>type)) <span class="sc">+</span></span>
<span id="cb18-7"><a></a>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="st">"dodge"</span>,<span class="at">stat=</span><span class="st">"identity"</span>) <span class="sc">+</span> </span>
<span id="cb18-8"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb18-9"><a></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Number of failures"</span>, <span class="at">y=</span><span class="st">"Count"</span>,<span class="at">fill=</span><span class="st">"Observed vs. Expected"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture10_files/figure-revealjs/unnamed-chunk-6-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise" class="slide level2">
<h2>Exercise</h2>
<p>In the “nighttime” lottery run by the state of Texas, three numbers are selected from the digits 0 through 9. The frequencies of the first digit selected over a period of almost 30 years (from 1993 to 2023) are shown below for each of the 9,215 days.</p>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Data Set</a></li><li><a href="#tabset-5-2">Question</a></li><li><a href="#tabset-5-3">Answer</a></li><li><a href="#tabset-5-4">Plot</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<table class="caption-top">
<thead>
<tr class="header">
<th>Digit</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>918</td>
</tr>
<tr class="even">
<td>1</td>
<td>905</td>
</tr>
<tr class="odd">
<td>2</td>
<td>908</td>
</tr>
<tr class="even">
<td>3</td>
<td>916</td>
</tr>
<tr class="odd">
<td>4</td>
<td>900</td>
</tr>
<tr class="even">
<td>5</td>
<td>911</td>
</tr>
<tr class="odd">
<td>6</td>
<td>963</td>
</tr>
<tr class="even">
<td>7</td>
<td>948</td>
</tr>
<tr class="odd">
<td>8</td>
<td>937</td>
</tr>
<tr class="even">
<td>9</td>
<td>909</td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-5-2">
<p>Test whether each digit is equally likely to have been selected in the Texas “nighttime” lottery.</p>
</div>
<div id="tabset-5-3">
<p>We specify the observed variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>observed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">918</span>,<span class="dv">905</span>,<span class="dv">908</span>,<span class="dv">916</span>,<span class="dv">900</span>,<span class="dv">911</span>,<span class="dv">963</span>,<span class="dv">948</span>,<span class="dv">937</span>,<span class="dv">909</span>)</span>
<span id="cb19-2"><a></a>observed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 918 905 908 916 900 911 963 948 937 909</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>total <span class="ot">&lt;-</span> <span class="fu">sum</span>(observed)</span>
<span id="cb21-2"><a></a>total</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9215</code></pre>
</div>
</div>
<p>The specified distribution is the discrete uniform distribution. We can then calculate the uniform probabilities as 1/10 (10 bins).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>expected <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span></span>
<span id="cb23-2"><a></a>)</span>
<span id="cb23-3"><a></a>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a><span class="fu">sum</span>(expected) <span class="co"># must be 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a>total<span class="sc">*</span>expected <span class="co"># there should not be more than 1.5 bins that have less than 5 expected counts</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 921.5 921.5 921.5 921.5 921.5 921.5 921.5 921.5 921.5 921.5</code></pre>
</div>
</div>
<p>All expected counts are above 5. We can now use the chi-square approximation for the p-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>chisqtest <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(<span class="at">x=</span>observed,<span class="at">p=</span>expected)</span>
<span id="cb29-2"><a></a>chisqtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  observed
X-squared = 4.2219, df = 9, p-value = 0.8962</code></pre>
</div>
</div>
<p>The test statistic is 4.2219208 with a p-value 0.8962084. We fail to reject the null hypothesis. We have insufficient evidence to conclude that the digits are not equally likely to be chosen for the “nighttime” lottery.</p>
</div>
<div id="tabset-5-4">
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb31-2"><a></a>df_observed <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">bin =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>,<span class="at">y=</span>observed,<span class="at">type=</span><span class="st">"Observed"</span>)</span>
<span id="cb31-3"><a></a>df_expected <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">bin =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>,<span class="at">y=</span>total<span class="sc">*</span>expected,<span class="at">type=</span><span class="st">"Expected"</span>)</span>
<span id="cb31-4"><a></a>df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(df_observed,df_expected)</span>
<span id="cb31-5"><a></a></span>
<span id="cb31-6"><a></a><span class="fu">ggplot</span>(df,<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">as.factor</span>(bin),<span class="at">y=</span>y,<span class="at">group=</span>type,<span class="at">fill=</span>type)) <span class="sc">+</span></span>
<span id="cb31-7"><a></a>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="st">"dodge"</span>,<span class="at">stat=</span><span class="st">"identity"</span>) <span class="sc">+</span> </span>
<span id="cb31-8"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb31-9"><a></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Number of failures"</span>, <span class="at">y=</span><span class="st">"Count"</span>,<span class="at">fill=</span><span class="st">"Observed vs. Expected"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture10_files/figure-revealjs/unnamed-chunk-10-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="test-of-independence" class="title-slide slide level1 center">
<h1>Test of Independence</h1>

</section>
<section id="test-of-independence-1" class="slide level2">
<h2>Test of Independence</h2>
<p>Suppose we are interested in a contingency table made from two distinct categorical variables.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions</strong></p>
</div>
<div class="callout-content">
<p>Suppose the row variables has <span class="math inline">\(r\)</span> levels and the column variables has <span class="math inline">\(c\)</span> levels. This implies that any unit/subject can fall in any of the <span class="math inline">\(rc\)</span> categories.</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-test-1" class="slide level2">
<h2>Hypothesis Test</h2>
<p>The null hypothesis for the test of independence is that <strong>the row and column variables are independent of each other</strong>, while the alternative hypothesis is that the row and column variables are not independent.</p>
</section>
<section id="null-hypothesis-assumption" class="slide level2">
<h2>Null Hypothesis Assumption</h2>
<p>Suppose we define <span class="math inline">\(p_{ij}\)</span> as the probability of a unit to be found at row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span>, denoted by <span class="math inline">\((i,j)\)</span>. We also define <span class="math inline">\(p_{i\cdot}\)</span> and <span class="math inline">\(p_{\cdot j}\)</span> as the respective probabilities of finding the unit at row <span class="math inline">\(i\)</span> and finding the unit at row <span class="math inline">\(j\)</span>. The assumption of independence implies that for all <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>,</p>
<p><span class="math display">\[
p_{ij} = p_{i\cdot} p_{\cdot j}
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Under the assumption that the null hypothesis is true, the expected counts for each cell can be calculated as:</p>
<p><span class="math display">\[
E_{ij} = r_ic_j/n
\]</span></p>
<p>where <span class="math inline">\(r_i\)</span> is the row total for row <span class="math inline">\(i\)</span>, <span class="math inline">\(c_j\)</span> is the column total for column <span class="math inline">\(j\)</span>, and <span class="math inline">\(n\)</span> is the total sample size.</p>
</div>
</div>
</div>
</section>
<section id="test-statistic-1" class="slide level2">
<h2>Test Statistic</h2>
<p>The test statistic compares the deviation of the observed data to the expected data similar to the goodness-of-fit.</p>
<p><span class="math display">\[
Q = \sum_{i=1}^r \sum_{j=1}^c \frac{(O_{ij}-E_{ij})^2}{E_{ij}}
\]</span></p>
<p>The test statistic approximately follows a chi-squared distribution with degrees of freedom <span class="math inline">\((r-1)(c-1)\)</span>, <span class="math inline">\(\chi^2_{(r-1)(c-1)}\)</span> where <span class="math inline">\(r\)</span> and <span class="math inline">\(c\)</span> are the total numbers of rows and columns, respectively.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>It is important to check the expected number of events for each cell. If the expected number of events is less than 5 for 25% of the cells, the chi-square distribution does not hold.</p>
</div>
</div>
</div>
</section>
<section id="p-value" class="slide level2">
<h2>p-value</h2>
<p>The p-value can be calculated using the probability <span class="math inline">\(P(\chi^2_{(r-1)(c-1)} \geq Q)\)</span>.</p>
</section>
<section id="r-implementation-1" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The <code>chisq.test()</code> can also be used to perform tests of independence.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>When dealing with data sets, it would be beneficial to create a contingency table with <code>xtabs()</code> first to check for data sparsity (low cell counts) before using it as an input in <code>chisq.test()</code>.</p>
</div>
</div>
</div>
<div class="sourceCode" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">xtabs</span>(<span class="sc">~</span>x<span class="sc">+</span>y, <span class="at">data=</span>df)</span>
<span id="cb32-2"><a></a>chisq <span class="ot">&lt;-</span><span class="fu">chisq.test</span>(df<span class="sc">$</span>x,df<span class="sc">$</span>y)</span>
<span id="cb32-3"><a></a>chisq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><code>chisq.test()</code> calculates the expected values using the <code>chisq$expected</code> option.</p>
</div>
</div>
</div>
</section>
<section id="example-4" class="slide level2">
<h2>Example</h2>
<p>Consider the sleep health data, <code>SleepHealthData.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Question</a></li><li><a href="#tabset-6-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p>Test whether gender (variable <code>gender</code>) is associated with reported sleep disorders (variable <code>sleep_disorder</code>. Use a significance level of 0.01.</p>
</div>
<div id="tabset-6-2">
<p>Check for sparsity of data first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="fu">xtabs</span>(<span class="sc">~</span>gender<span class="sc">+</span>sleep_disorder,<span class="at">data=</span>sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        sleep_disorder
gender   Insomnia None Sleep Apnea
  Female       36   82          67
  Male         41  137          11</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a>chisqtest <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(sleep<span class="sc">$</span>gender,sleep<span class="sc">$</span>sleep_disorder)</span>
<span id="cb36-2"><a></a>chisqtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  sleep$gender and sleep$sleep_disorder
X-squared = 54.306, df = 2, p-value = 1.613e-12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a>chisqtest<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            sleep$sleep_disorder
sleep$gender Insomnia     None Sleep Apnea
      Female 38.08824 108.3289    38.58289
      Male   38.91176 110.6711    39.41711</code></pre>
</div>
</div>
<p>All expected values are above 5, which means the chi-squared assumption is valid. The p-value is 1.6128634^{-12}, the test statistic is 54.3060201 with 2 degrees of freedom. At a significance level of 0.01, we reject the null hypothesis. We have sufficient evidence to conclude that the gender and occurrence of sleep disorder are not independent.</p>
</div>
</div>
</div>
</section>
<section id="exercise-1" class="slide level2">
<h2>Exercise</h2>
<p>Consider the sleep health data, <code>SleepHealthData.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Question</a></li><li><a href="#tabset-7-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<p>Test whether stress level (variable <code>stress_level</code>) is associated with reported sleep disorders (variable <code>sleep_disorder</code>). Treat stress level as an ordinal categorical variable. Use a significance level of 0.01.</p>
</div>
<div id="tabset-7-2">
<p>Check for sparsity of data first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a><span class="fu">xtabs</span>(<span class="sc">~</span>stress_level<span class="sc">+</span>sleep_disorder,<span class="at">data=</span>sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            sleep_disorder
stress_level Insomnia None Sleep Apnea
           3        1   40          30
           4       24   43           3
           5        6   57           4
           6        2   43           1
           7       41    3           6
           8        3   33          34</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a>chisqtest <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(sleep<span class="sc">$</span>stress_level,sleep<span class="sc">$</span>sleep_disorder)</span>
<span id="cb43-2"><a></a>chisqtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  sleep$stress_level and sleep$sleep_disorder
X-squared = 240.2, df = 10, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a>chisqtest<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  sleep$sleep_disorder
sleep$stress_level  Insomnia     None Sleep Apnea
                 3 14.617647 41.57487   14.807487
                 4 14.411765 40.98930   14.598930
                 5 13.794118 39.23262   13.973262
                 6  9.470588 26.93583    9.593583
                 7 10.294118 29.27807   10.427807
                 8 14.411765 40.98930   14.598930</code></pre>
</div>
</div>
<p>All expected values are above 5, which means the chi-squared assumption is valid. The p-value is 6.2217174^{-46}, the test statistic is 240.1993685 with 10 degrees of freedom. At a significance level of 0.01, we reject the null hypothesis. We have sufficient evidence to conclude that the stress level and occurrence of sleep disorder are not independent.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="test-of-homogeneity" class="title-slide slide level1 center">
<h1>Test of Homogeneity</h1>

</section>
<section id="test-of-homogeneity-1" class="slide level2">
<h2>Test of Homogeneity</h2>
<p>Suppose the sampling strategy was to select a fixed sample size per group, and measure the response for each unit/individual.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>If the samples are stratified per group, the groups are not random. The response remains random. The margins for the grouping variable, typically assigned in the rows, are fixed in advance.</p>
</div>
</div>
</div>
</section>
<section id="homogeneity-vs.-independence" class="slide level2">
<h2>Homogeneity vs.&nbsp;Independence</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Because people assigned to/sampled from groups are no longer random, there is no sense to test for independence. Instead, we test whether the probability of being in each of the outcome groups is the same across all treatments.</p>
<p>Hence, the test is referred to as the <strong>test of homogeneity</strong>.</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-test-2" class="slide level2">
<h2>Hypothesis Test</h2>
<p>The null hypothesis is that the marginal probability of the outcome variable is the same across all the groups/populations/treatments considered in the study.</p>
<p>The alternative hypothesis is that at least one marginal probability is not equal to the others.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>This test is similar to comparing the difference of two proportions for a 2x2 contingency table.</p>
</div>
</div>
</div>
</section>
<section id="null-hypothesis-assumption-1" class="slide level2">
<h2>Null Hypothesis Assumption</h2>
<p>Suppose we define <span class="math inline">\(p_{ij}\)</span> as the probability of a unit to be found at row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span>, denoted by <span class="math inline">\((i,j)\)</span>. The assumption of homogeneity assumes that the marginal probability across the columns are the same. Hence,</p>
<p><span class="math display">\[
p_{ij} = c_j/n
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Under the assumption that the null hypothesis is true, the expected counts for each cell can be calculated as:</p>
<p><span class="math display">\[
E_{ij} = r_ip_{ij} = r_i(c_j/n)
\]</span></p>
<p>where <span class="math inline">\(r_i\)</span> is the row total for row <span class="math inline">\(i\)</span>, <span class="math inline">\(c_j\)</span> is the column total for column <span class="math inline">\(j\)</span>, and <span class="math inline">\(n\)</span> is the total sample size.</p>
</div>
</div>
</div>
</section>
<section id="test-statistic-2" class="slide level2">
<h2>Test Statistic</h2>
<p>The test statistic compares the deviation of the observed data to the expected data similar to the goodness-of-fit.</p>
<p><span class="math display">\[
Q = \sum_{i=1}^r \sum_{j=1}^c \frac{(O_{ij}-E_{ij})^2}{E_{ij}}
\]</span></p>
<p>The test statistic approximately follows a chi-squared distribution with degrees of freedom <span class="math inline">\((r-1)(c-1)\)</span>, <span class="math inline">\(\chi^2_{(r-1)(c-1)}\)</span> where <span class="math inline">\(r\)</span> and <span class="math inline">\(c\)</span> are the total numbers of rows and columns, respectively.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Note that the test statistic is the same for independence and homogeneity tests, but the assumptions and hypotheses are different.</p>
<p>It is important to check the expected number of events for each cell. If the expected number of events is less than 5 for 25% of the cells, the chi-square distribution does not hold.</p>
</div>
</div>
</div>
</section>
<section id="p-value-calculation-1" class="slide level2">
<h2>p-value Calculation</h2>
<p>The p-value can be calculated using the probability <span class="math inline">\(P(\chi^2_{(r-1)(c-1)} \geq Q)\)</span>.</p>
</section>
<section id="r-implementation-2" class="slide level2">
<h2><code>R</code> Implementation</h2>
<p>The <code>R</code> implementation of the homogeneity test is similar to that of the independence test.</p>
</section>
<section id="example-5" class="slide level2">
<h2>Example</h2>
<p>The data set <code>covid.csv</code> includes data from a clinical trial for treatments of COVID-19. Suppose that subjects are randomly assigned to one of two treatments: an experimental drug and a placebo (best available treatment).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb47-2"><a></a>covid <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/covid.csv"</span>)</span>
<span id="cb47-3"><a></a><span class="fu">glimpse</span>(covid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,297
Columns: 3
$ ID        &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
$ Treatment &lt;chr&gt; "Experimental", "Experimental", "Experimental", "Experimenta…
$ Outcome   &lt;chr&gt; "Not Hospitalized", "Not Hospitalized", "Not Hospitalized", …</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Question</a></li><li><a href="#tabset-8-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p>We want to test whether the marginal probabilities of each outcome (not hospitalized, hospitalized, and died) are the same across each treatment. Use a significance level of 0.05.</p>
</div>
<div id="tabset-8-2">
<p>Create a contingency table first to test whether there are sparse counts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a></a>contingency <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span>Treatment<span class="sc">+</span>Outcome,<span class="at">data=</span>covid)</span>
<span id="cb49-2"><a></a>contingency</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Outcome
Treatment      Died Hospitalized Not Hospitalized
  Experimental   11           67              572
  Placebo        23           81              543</code></pre>
</div>
</div>
<p>We implement the chi-squared test using <code>chisq.test()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a>chisqtest <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(covid<span class="sc">$</span>Treatment,covid<span class="sc">$</span>Outcome)</span>
<span id="cb51-2"><a></a>chisqtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  covid$Treatment and covid$Outcome
X-squared = 6.307, df = 2, p-value = 0.0427</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a>chisqtest<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               covid$Outcome
covid$Treatment     Died Hospitalized Not Hospitalized
   Experimental 17.03932     74.17116         558.7895
   Placebo      16.96068     73.82884         556.2105</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a><span class="co"># OR</span></span>
<span id="cb55-2"><a></a></span>
<span id="cb55-3"><a></a>chisqtest <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(contingency)</span>
<span id="cb55-4"><a></a>chisqtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  contingency
X-squared = 6.307, df = 2, p-value = 0.0427</code></pre>
</div>
</div>
<p>All expected values are above 5, which means the chi-squared assumption is valid. The p-value is 0.042703, the test statistic is 6.3069732 with 2 degrees of freedom. At a significance level of 0.05, we reject the null hypothesis. We have sufficient evidence to conclude that the marginal probabilities of the outcome variable differ across treatments.</p>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="slide level2">
<h2>Exercise</h2>
<p>The following data is from a study investigating the sources of health information from 200 urban young adults and 150 rural young adults.</p>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Data</a></li><li><a href="#tabset-9-2">Question</a></li><li><a href="#tabset-9-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<p>This is how to input aggregated data in <code>R</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a></a>source_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb57-2"><a></a>  <span class="at">Location =</span> <span class="fu">c</span>(<span class="st">"Urban"</span>, <span class="st">"Urban"</span>,<span class="st">"Urban"</span>, <span class="st">"Rural"</span>, <span class="st">"Rural"</span>,<span class="st">"Rural"</span>),</span>
<span id="cb57-3"><a></a>  <span class="at">Source =</span> <span class="fu">c</span>(<span class="st">"Social Media"</span>, <span class="st">"Medical Professionals"</span>, <span class="st">"Others"</span>, <span class="st">"Social Media"</span>, <span class="st">"Medical Professionals"</span>, <span class="st">"Others"</span>),</span>
<span id="cb57-4"><a></a>  <span class="at">Count =</span> <span class="fu">c</span>(<span class="dv">84</span>,<span class="dv">96</span>,<span class="dv">20</span>,<span class="dv">17</span>,<span class="dv">31</span>,<span class="dv">53</span>)</span>
<span id="cb57-5"><a></a>)</span>
<span id="cb57-6"><a></a></span>
<span id="cb57-7"><a></a><span class="co"># Create a cross-table using xtabs</span></span>
<span id="cb57-8"><a></a>cross_table_xtabs <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count <span class="sc">~</span> Location <span class="sc">+</span> Source, <span class="at">data =</span> source_data)</span>
<span id="cb57-9"><a></a>cross_table_xtabs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Source
Location Medical Professionals Others Social Media
   Rural                    31     53           17
   Urban                    96     20           84</code></pre>
</div>
</div>
</div>
<div id="tabset-9-2">
<p>Test whether the marginal probabilities are homogeneous across the urban and rural participants.</p>
</div>
<div id="tabset-9-3">
<p>We can use the contingency table <code>cross_table_xtabs</code> in the function <code>chisq.test()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a></a>chisqtest<span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(cross_table_xtabs)</span>
<span id="cb59-2"><a></a>chisqtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  cross_table_xtabs
X-squared = 67.356, df = 2, p-value = 2.365e-15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a></a>chisqtest<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Source
Location Medical Professionals   Others Social Media
   Rural              42.61462 24.49502     33.89037
   Urban              84.38538 48.50498     67.10963</code></pre>
</div>
</div>
<p>All expected counts are above 5, hence we can use the chi-squared assumption. All expected values are above 5, which means the chi-squared assumption is valid. The p-value is 2.3649711^{-15}, the test statistic is 67.3560212 with 2 degrees of freedom. At a significance level of 0.05, we reject the null hypothesis. We have sufficient evidence to conclude that the marginal probabilities are not homogeneous across the rurality of residence of the participants.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="fisher-exact-test" class="title-slide slide level1 center">
<h1>Fisher Exact Test</h1>

</section>
<section id="chi-squared-tests-small-sample-size" class="slide level2">
<h2>Chi-Squared Tests: Small Sample Size</h2>
<p>For small sample sizes, the expected values for the cells might be less than 5 for most cells. The chi-squared assumption might not be valid for these cases.</p>
</section>
<section id="fisher-exact-test-1" class="slide level2">
<h2>Fisher Exact Test</h2>
<p>The Fisher Exact Test calculates an <em>exact</em> p-value using the hypergeometric distribution.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Because the Fisher Exact Test does not rely on any asymptotic (long-run) behavior of the random variables, there is no requirement for a minimum sample size.</p>
<p>The Fisher Exact Test is used primarily for 2x2 tables with small cell counts.</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-test-3" class="slide level2">
<h2>Hypothesis Test</h2>
<p>The hypothesis tests for the test of independence and homogeneity still hold.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Unlike the chi-squared tests, the alternative hypothesis can be one-sided.</p>
<ul>
<li>One sided <span class="math inline">\(H_a\)</span>: There is a positive/negative association between the row and column variables. OR One combination of the row and column variable levels is more favored compared to the others.</li>
<li>Two-sided <span class="math inline">\(H_a\)</span>: there is an association between the row and column variables.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="test-statistic-and-p-value" class="slide level2">
<h2>Test statistic and p-value</h2>
<p>The p-value is calculated based on the probability of the configuration of the contingency table. The test assumes that the row and column totals are fixed.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The test statistic used is the upper left cell of the contingency table, <span class="math inline">\(X\)</span>.</p>
<p>The hypergeometric distribution is used to determine which numbers are more extreme than what was observed.</p>
<p>Once the values are established, we sum the probabilities of all the values that are as extreme or more extreme than what was observed.</p>
</div>
</div>
</div>
</section>
<section id="r-implementation-3" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The function <code>fisher.test()</code> can be used to perform the Fisher Exact Test. It can use the data frame or a cross table to calculate the exact p-values.</p>
<h3 id="sample-code">Sample Code</h3>
<div class="sourceCode" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a></a><span class="fu">fisher.test</span>(df,<span class="at">alternative=</span><span class="st">"greater"</span>)</span>
<span id="cb63-2"><a></a></span>
<span id="cb63-3"><a></a><span class="co"># OR</span></span>
<span id="cb63-4"><a></a></span>
<span id="cb63-5"><a></a><span class="fu">fisher.test</span>(contingency,<span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="example-6" class="slide level2">
<h2>Example</h2>
<p>The table shown shows data from a study on treatments for healing severe infections.</p>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Data</a></li><li><a href="#tabset-10-2">Question</a></li><li><a href="#tabset-10-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a></a>aggregated_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb64-2"><a></a>  <span class="at">Treatment =</span> <span class="fu">c</span>(<span class="st">"A_Test"</span>, <span class="st">"A_Test"</span>, <span class="st">"B_Control"</span>, <span class="st">"B_Control"</span>),</span>
<span id="cb64-3"><a></a>  <span class="at">Outcome =</span> <span class="fu">c</span>(<span class="st">"Favorable"</span>, <span class="st">"Unfavorable"</span>, <span class="st">"Favorable"</span>, <span class="st">"Unfavorable"</span>),</span>
<span id="cb64-4"><a></a>  <span class="at">Count =</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">2</span>,<span class="dv">2</span>, <span class="dv">4</span>)</span>
<span id="cb64-5"><a></a>)</span>
<span id="cb64-6"><a></a></span>
<span id="cb64-7"><a></a><span class="co"># Create a cross-table using xtabs</span></span>
<span id="cb64-8"><a></a>cross_table_xtabs <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count <span class="sc">~</span> Treatment <span class="sc">+</span> Outcome, <span class="at">data =</span> aggregated_data)</span>
<span id="cb64-9"><a></a>cross_table_xtabs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Outcome
Treatment   Favorable Unfavorable
  A_Test           10           2
  B_Control         2           4</code></pre>
</div>
</div>
</div>
<div id="tabset-10-2">
<p>Use the Fisher’s Exact Test to see if there is a positive association between the presence of the test treatment and the outcome. Use a significance level of 0.10.</p>
</div>
<div id="tabset-10-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a></a>fisher<span class="ot">&lt;-</span> <span class="fu">fisher.test</span>(cross_table_xtabs,<span class="at">alternative=</span><span class="st">"greater"</span>)</span>
<span id="cb66-2"><a></a>fisher</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  cross_table_xtabs
p-value = 0.05726
alternative hypothesis: true odds ratio is greater than 1
95 percent confidence interval:
 0.9374086       Inf
sample estimates:
odds ratio 
  8.457238 </code></pre>
</div>
</div>
<p>Compare the result to asymptotic chi-squared tests.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a></a><span class="fu">chisq.test</span>(cross_table_xtabs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  cross_table_xtabs
X-squared = 2.5312, df = 1, p-value = 0.1116</code></pre>
</div>
</div>
<p>The resulting p-value from the Fisher exact test is 0.0572614. At a significance level of 0.10, we reject the null hypothesis. We have sufficient evidence to claim that there is a positive association between the treatment and the outcome.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Note that the chi-squared assumption will yield a different decision for the hypothesis test, but this should be discarded because the chi-squared assumption does not hold (expected value less than 5).</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="symmetry-tests" class="title-slide slide level1 center">
<h1>Symmetry Tests</h1>

</section>
<section id="mcnemars-test" class="slide level2">
<h2>McNemar’s Test</h2>
<p>McNemar’s test is a nonparametric test for homogeneity between two paired dichotomous variables.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The usual test of homogeneity assumes each cell count is independent, which would not be the case when the column and row variables are paired.</p>
<p>The McNemar’s test is designed for a 2x2 contingency table. For larger nxn tables, we use the McNemar-Bowker Test.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Example</strong></p>
</div>
<div class="callout-content">
<p>Suppose we are interested in the racial identity concordance of provider and patients at a certain region. The column variable could be assigned to describe the provider identity, while the row column could be assigned to describe the patient identity. The counts will not be independent of each other.</p>
</div>
</div>
</div>
</section>
<section id="r-implementation-4" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The McNemar’s test can be performed using <code>mcnemar.test()</code> in <code>R</code>. Like <code>chisq.test()</code> and <code>fisher.test()</code>, it can take individual columns or a contingency table as input.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The chi-squared distribution is used as the distribution of the test-statistic.</p>
</div>
</div>
</div>
</section>
<section id="example-8" class="slide level2">
<h2>Example</h2>
<p>Consider the data in this table where patients were observed at Time 1 for the presence of a rash and then were observed at Time 2 for the presence of the rash. Each patient with a rash was provided a homeopathic treatment between Time 1 and Time 2.</p>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">Data</a></li><li><a href="#tabset-11-2">Question</a></li><li><a href="#tabset-11-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a></a>source_data<span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb70-2"><a></a>  <span class="at">T1_Presence=</span> <span class="fu">c</span>(<span class="st">"T1_Presence"</span>, <span class="st">"T1_Presence"</span>, <span class="st">"T1_Absence"</span>, <span class="st">"T1_Absence"</span>),</span>
<span id="cb70-3"><a></a>  <span class="at">T2_Presence =</span> <span class="fu">c</span>(<span class="st">"T2_Presence"</span>, <span class="st">"T2_Absence"</span>, <span class="st">"T2_Presence"</span>, <span class="st">"T2_Absence"</span>),</span>
<span id="cb70-4"><a></a>  <span class="at">Count =</span> <span class="fu">c</span>(<span class="dv">38</span>, <span class="dv">12</span>, <span class="dv">5</span>, <span class="dv">45</span>)</span>
<span id="cb70-5"><a></a>)</span>
<span id="cb70-6"><a></a></span>
<span id="cb70-7"><a></a><span class="co"># Create a cross-table using xtabs</span></span>
<span id="cb70-8"><a></a>cross_table_xtabs <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count <span class="sc">~</span> T1_Presence<span class="sc">+</span>T2_Presence, <span class="at">data =</span> source_data)</span>
<span id="cb70-9"><a></a>cross_table_xtabs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             T2_Presence
T1_Presence   T2_Absence T2_Presence
  T1_Absence          45           5
  T1_Presence         12          38</code></pre>
</div>
</div>
</div>
<div id="tabset-11-2">
<p>Use McNemar’s test to see if there is a difference in proportion for those with the rash and without the rash before and after treatment. Use a significance level of 0.05.</p>
</div>
<div id="tabset-11-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a></a>mcn <span class="ot">&lt;-</span> <span class="fu">mcnemar.test</span>(cross_table_xtabs)</span>
<span id="cb72-2"><a></a>mcn</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    McNemar's Chi-squared test with continuity correction

data:  cross_table_xtabs
McNemar's chi-squared = 2.1176, df = 1, p-value = 0.1456</code></pre>
</div>
</div>
<p>The resulting p-value is 0.1456101. At a significance level of 0.05, we fail to reject the null hypothesis. We have insufficient evidence to claim that there is a difference in proportion for those with the rash and without the rash before and after treatment.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="measures-of-association" class="title-slide slide level1 center">
<h1>Measures of Association</h1>

</section>
<section id="epidemiological-concepts" class="slide level2">
<h2>Epidemiological Concepts</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Observational Study</strong></p>
</div>
<div class="callout-content">
<p>A research method where researchers observe and collect information without manipulation.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Risk Factor</strong></p>
</div>
<div class="callout-content">
<p>A variable that is thought to be related to some outcome variable.</p>
</div>
</div>
</div>
</section>
<section id="prospective-vs.-retrospective-study" class="slide level2">
<h2>Prospective vs.&nbsp;Retrospective Study</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Prospective Study</strong></p>
</div>
<div class="callout-content">
<p>In a prospective study, two samples of subjects are selected: a group with the risk factor, and a group without the risk factor. These subjects are followed prospectively and outcomes are observed in the future.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Retrospective Study</strong></p>
</div>
<div class="callout-content">
<p>In a retrospective study, two samples of subjects are selected: a group with the outcome of interest(cases), and a group without (control). These subjects are examined retrospectively to check if they have the risk factor.</p>
</div>
</div>
</div>
</section>
<section id="measures-of-association-1" class="slide level2">
<h2>Measures of Association</h2>
<p>For prospective studies, the measure of association between the risk factor and outcome is the <strong>relative risk</strong>.</p>
<p>For retrospective studies, the measure of association between the risk factor and outcome is the <strong>odds ratio</strong>.</p>
</section>
<section id="relative-risk" class="slide level2">
<h2>Relative Risk</h2>

<img data-src="figs/10-contingency.png" style="width:5in" class="r-stretch"><p>The relative risk (RR) is the ratio of the risk of being a case among subjects with the risk factor to the risk of developing the disease among subjects without the risk factor. The RR can be calculated using the following equation:</p>
<p><span class="math display">\[
RR = \frac{a/(a+b)}{c/(c+d)}
\]</span></p>
</section>
<section id="odds-ratio" class="slide level2">
<h2>Odds Ratio</h2>
<p>Recall: Logistic Regression. The odds ratio is the ratio of the odds of developing into a case between those with and without the risk factor.</p>
<p><span class="math display">\[
OR = \frac{a/b}{c/d}=ad/bc
\]</span></p>
</section>
<section id="r-implementation-5" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>While the best estimate of the odds ratios and relative risk can easily be calculated using the values in the contingency table, the package <code>epitools</code> contains the <code>epitab()</code> function that calculates both relative risk/odds ratio and their corresponding intervals.</p>
<h3 id="sample-code-1">Sample Code</h3>
<div class="sourceCode" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a></a><span class="co">#install.packages("epitools")</span></span>
<span id="cb74-2"><a></a><span class="fu">library</span>(epitools)</span>
<span id="cb74-3"><a></a><span class="fu">epitab</span>(contingency,<span class="at">method=</span><span class="st">"oddsratio"</span>)</span>
<span id="cb74-4"><a></a></span>
<span id="cb74-5"><a></a><span class="co"># OR</span></span>
<span id="cb74-6"><a></a></span>
<span id="cb74-7"><a></a><span class="fu">epitab</span>(contingency,<span class="at">method=</span><span class="st">"riskratio"</span>,<span class="at">pvalue=</span><span class="st">"chi2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The contingency table should be given in this particular format:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a></a>                 Disease</span>
<span id="cb75-2"><a></a>  Exposure       <span class="fu">No</span> (ref)  Yes</span>
<span id="cb75-3"><a></a>   Level <span class="dv">1</span> (ref)  a         b</span>
<span id="cb75-4"><a></a>   Level <span class="dv">2</span>        c         d</span>
<span id="cb75-5"><a></a>   Level <span class="dv">3</span>        e         f </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="example-9" class="slide level2">
<h2>Example</h2>
<p>The data below includes data from a prospective study on low-risk pregnant women. A group of 217 women did no voluntary or mandatory exercise during the pregnancy while 238 exercised extensively. One outcome variable of interest was experiencing preterm labor.</p>
<div class="panel-tabset">
<ul id="tabset-12" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-12-1">Data</a></li><li><a href="#tabset-12-2">Question</a></li><li><a href="#tabset-12-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1">
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a></a>source_data<span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb76-2"><a></a>  <span class="at">Risk=</span> <span class="fu">c</span>(<span class="st">"Treatment"</span>,<span class="st">"Treatment"</span>,<span class="st">"Control"</span>,<span class="st">"Control"</span>),</span>
<span id="cb76-3"><a></a>  <span class="at">Outcome =</span> <span class="fu">c</span>(<span class="st">"Case"</span>, <span class="st">"Control"</span>, <span class="st">"Case"</span>, <span class="st">"Control"</span>),</span>
<span id="cb76-4"><a></a>  <span class="at">Count =</span> <span class="fu">c</span>(<span class="dv">22</span>,<span class="dv">216</span>,<span class="dv">18</span>,<span class="dv">199</span>)</span>
<span id="cb76-5"><a></a>)</span>
<span id="cb76-6"><a></a></span>
<span id="cb76-7"><a></a><span class="co"># Create a cross-table using xtabs</span></span>
<span id="cb76-8"><a></a>cross_table_xtabs <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count <span class="sc">~</span> Risk<span class="sc">+</span>Outcome, <span class="at">data =</span> source_data)</span>
<span id="cb76-9"><a></a>cross_table_xtabs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Outcome
Risk        Case Control
  Control     18     199
  Treatment   22     216</code></pre>
</div>
</div>
</div>
<div id="tabset-12-2">
<p>Calculate the relevant measure of association and provide a 95% confidence interval.</p>
</div>
<div id="tabset-12-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a></a><span class="fu">library</span>(epitools)</span>
<span id="cb78-2"><a></a><span class="fu">epitab</span>(cross_table_xtabs,<span class="at">method=</span><span class="st">"riskratio"</span>,<span class="at">pvalue=</span><span class="st">"chi2"</span>,<span class="at">rev=</span><span class="st">"columns"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$tab
           Outcome
Risk        Control        p0 Case         p1 riskratio     lower    upper
  Control       199 0.9170507   18 0.08294931  1.000000        NA       NA
  Treatment     216 0.9075630   22 0.09243697  1.114379 0.6145682 2.020672
           Outcome
Risk          p.value
  Control          NA
  Treatment 0.7211157

$measure
[1] "wald"

$conf.level
[1] 0.95

$pvalue
[1] "chi2"</code></pre>
</div>
</div>
<p>The relative risk is 1.114 with a 95% confidence interval: (0.615,2.021). The resulting p-value from the chi-squared approximation is 0.72. At a significance level of 0.05, we fail to reject the null hypothesis. We have insufficient evidence to conclude that there is a difference in risk of experiencing preterm labor between those who exercise extensively and those who did not.</p>
</div>
</div>
</div>
</section>
<section id="exercise-3" class="slide level2">
<h2>Exercise</h2>
<p>The table shows 3970 subjects classified as cases or noncases of obesity and also classified according to smoking status of the mother during pregnancy (the risk factor).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a></a>source_data<span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb80-2"><a></a>  <span class="at">Risk=</span> <span class="fu">c</span>(<span class="st">"Present"</span>,<span class="st">"Present"</span>,<span class="st">"Absent"</span>,<span class="st">"Absent"</span>),</span>
<span id="cb80-3"><a></a>  <span class="at">Outcome =</span> <span class="fu">c</span>(<span class="st">"Case"</span>, <span class="st">"Control"</span>, <span class="st">"Case"</span>, <span class="st">"Control"</span>),</span>
<span id="cb80-4"><a></a>  <span class="at">Count =</span> <span class="fu">c</span>(<span class="dv">64</span>,<span class="dv">342</span>,<span class="dv">68</span>,<span class="dv">3496</span>)</span>
<span id="cb80-5"><a></a>)</span>
<span id="cb80-6"><a></a></span>
<span id="cb80-7"><a></a><span class="co"># Create a cross-table using xtabs</span></span>
<span id="cb80-8"><a></a>cross_table_xtabs <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count <span class="sc">~</span> Risk<span class="sc">+</span>Outcome, <span class="at">data =</span> source_data)</span>
<span id="cb80-9"><a></a>cross_table_xtabs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Risk      Case Control
  Absent    68    3496
  Present   64     342</code></pre>
</div>
</div>
<h3 id="question-10">Question</h3>
<ul>
<li>Is this study a prospective or a retrospective study?</li>
<li>Calculate the appropriate measure of association to report for this study. Provide a 95% confidence interval.</li>
</ul>
<h3 id="answer-10">Answer</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a></a><span class="fu">epitab</span>(cross_table_xtabs,<span class="at">method=</span><span class="st">"oddsratio"</span>,<span class="at">rev=</span><span class="st">"columns"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$tab
         Outcome
Risk      Control         p0 Case        p1 oddsratio    lower    upper
  Absent     3496 0.91089109   68 0.5151515  1.000000       NA       NA
  Present     342 0.08910891   64 0.4848485  9.620915 6.719328 13.77549
         Outcome
Risk           p.value
  Absent            NA
  Present 2.709464e-30

$measure
[1] "wald"

$conf.level
[1] 0.95

$pvalue
[1] "fisher.exact"</code></pre>
</div>
</div>
<p>This is a retrospective study. The appropriate measure of association is the odds ratio. The estimated odds ratio is 9.62, with a 95% confidence interval: (6.72,13.78). The confidence interval shows that children with obesity are more likely to have had mothers who smoked than those without obesity.</p>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Lecture 10 - <a href="https://madfudolig.quarto.pub/introtobiostats/">Back to home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/madfudolig\.quarto\.pub\/introtobiostats");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
            for (let i=0; i<annoteTargets.length; i++) {
              const annoteTarget = annoteTargets[i];
              const targetCell = annoteTarget.getAttribute("data-target-cell");
              const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
              const contentFn = () => {
                const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
                if (content) {
                  const tipContent = content.cloneNode(true);
                  tipContent.classList.add("code-annotation-tip-content");
                  return tipContent.outerHTML;
                }
              }
              const config = {
                allowHTML: true,
                content: contentFn,
                onShow: (instance) => {
                  selectCodeLines(instance.reference);
                  instance.reference.classList.add('code-annotation-active');
                  window.tippy.hideAll();
                },
                onHide: (instance) => {
                  unselectCodeLines();
                  instance.reference.classList.remove('code-annotation-active');
                },
                maxWidth: 300,
                delay: [50, 0],
                duration: [200, 0],
                offset: [5, 10],
                arrow: true,
                appendTo: function(el) {
                  return el.parentElement.parentElement.parentElement;
                },
                interactive: true,
                interactiveBorder: 10,
                theme: 'light-border',
                placement: 'right',
                popperOptions: {
                  modifiers: [
                  {
                    name: 'flip',
                    options: {
                      flipVariations: false, // true by default
                      allowedAutoPlacements: ['right'],
                      fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                    },
                  },
                  {
                    name: 'preventOverflow',
                    options: {
                      mainAxis: false,
                      altAxis: false
                    }
                  }
                  ]        
                }      
              };
              window.tippy(annoteTarget, config); 
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>