<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <title>EAB 703-1002: Biostatistical Methods for the Health Sciences – Analysis of Variance</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-5225a0b03738627c8390147651eb7bbf.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Analysis of Variance</h1>
  <p class="subtitle">Lecture 8</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="outline" class="title-slide slide level1 center">
<h1>Outline</h1>
<ul>
<li><p>Linear Models</p></li>
<li><p>Single Factor Analysis of Variance (ANOVA)</p>
<ul>
<li>Hypotheses</li>
<li>Test Statistic</li>
</ul></li>
<li><p>Two Factor ANOVA</p>
<ul>
<li>Interaction Term</li>
</ul></li>
</ul>
</section>

<section>
<section id="linear-models" class="title-slide slide level1 center">
<h1>Linear Models</h1>

</section>
<section id="what-are-linear-models" class="slide level2">
<h2>What are Linear Models?</h2>
<p>Linear models are very generalized models that allow us to investigate phenomena from many perspectives.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>In this course we will focus on three important applications of linear models:</p>
<ul>
<li>Analysis of Variance (ANOVA)</li>
<li>Linear Regression</li>
<li>Correlation</li>
</ul>
</div>
</div>
</div>
</section>
<section id="definition-of-terms" class="slide level2">
<h2>Definition of Terms</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The dependent variable is also referred to as the response variable, outcome variable, or measured variable.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The independent variable is also referred to as the explanatory variable, predictor variable, or <em>factor</em></p>
</div>
</div>
</div>
</section>
<section id="general-form-of-linear-models" class="slide level2">
<h2>General Form of Linear Models</h2>
<p>The general form of the linear model is given by</p>
<p><span class="math display">\[
Y_j = \beta_0 + \beta_1X_{1j} + \beta_2X_{2j} +... + \beta_k X_{kj} + \varepsilon_j
\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The terms are coefficients, with <span class="math inline">\(\beta_0\)</span> known as the intercept of the model. <span class="math inline">\(X_{1j}\)</span> are predictor variables or covariates, also known as confounding variables. These terms constitute a partition that estimates the mean of <span class="math inline">\(Y_j\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The term <span class="math inline">\(\varepsilon_j\)</span> corresponds to the noise term of the model. This term does not contribute to the mean, rather this partition captures the variability in the data.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="analysis-of-variance-anova" class="title-slide slide level1 center">
<h1>Analysis of Variance (ANOVA)</h1>

</section>
<section id="single-factor-anova" class="slide level2">
<h2>Single Factor ANOVA</h2>
<p>In Chapter 7, we compared the statistics of samples from two populations. Often, we want to compare more than two groups.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Suppose we want to compare more than two species or more than two treatment groups.</p>
</div>
</div>
</div>
</section>
<section id="statistical-hypotheses" class="slide level2">
<h2>Statistical Hypotheses</h2>
<p>In single-factor ANOVAs (also referred to as one-way ANOVAs), we would like to compare <strong>the means of multiple groups</strong>. Suppose we have <span class="math inline">\(k\)</span> groups defined by an explanatory variable. The null and alternative hypotheses can be expressed as:</p>
<p><span class="math display">\[
H_0: \mu_1 = \mu_2 = ... = \mu_k
\]</span></p>
<p><span class="math inline">\(H_a:\)</span> At least one group mean is not equal to others.</p>
</section>
<section id="one-way-anova-linear-model" class="slide level2">
<h2>One-way ANOVA: Linear Model</h2>
<p>The linear model for the ANOVA can be written as:</p>
<p><span class="math display">\[
Y_{ij} = \mu_{i} + \varepsilon_{ij}
\]</span> where <span class="math inline">\(Y_{ij}\)</span> is the value of the response variable for the <span class="math inline">\(j^{th}\)</span> subject in the <span class="math inline">\(i^{th}\)</span> group, <span class="math inline">\(\mu_i\)</span> is the group mean of the <span class="math inline">\(i^{th}\)</span> group, and <span class="math inline">\(\varepsilon_{ij}\)</span> is the error term.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The group mean of the <span class="math inline">\(i^{th}\)</span> group can be decomposed into <span class="math inline">\(\mu_i = \mu + \tau_i\)</span> where <span class="math inline">\(\mu\)</span> is referred to as the grand mean, and <span class="math inline">\(\tau_i\)</span> is the treatment effect.</p>
</div>
</div>
</div>
</section>
<section id="why-anova" class="slide level2">
<h2>Why ANOVA?</h2>
<p>While it is referred to as an analysis of variance, it can be used to compare group means.</p>

<img data-src="figs/8-anova-squares-graph.png" class="r-stretch quarto-figure-center"><p class="caption">Compare the purple squares to the yellow squares.</p><div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>We need to estimate the variability within groups and between groups. If the variability between groups is larger than the variability within groups, then there is evidence that the group means are different from each other.</p>
</div>
</div>
</div>
</section>
<section id="sum-of-squares" class="slide level2">
<h2>Sum of Squares</h2>
<p>The areas of the squares in the previous slide can be calculated using the <em>sum of squares</em>.</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Terms</a></li><li><a href="#tabset-1-2">Factor Sum of Squares</a></li><li><a href="#tabset-1-3">Error Sum of Squares</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<div title="Group Means">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Group Means</strong></p>
</div>
<div class="callout-content">
<p>The mean of group <span class="math inline">\(i\)</span> with size <span class="math inline">\(n_i\)</span> is expressed as <span class="math inline">\(\bar{y}_{i\cdot}\)</span> which can be written as:</p>
<p><span class="math display">\[
\bar{y}_{i\cdot} = \sum_{j=1}^{n_i}y_{ij}/n_i
\]</span></p>
</div>
</div>
</div>
</div>
<div title="Overall Mean">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Overall Mean</strong></p>
</div>
<div class="callout-content">
<p>The overall mean <span class="math inline">\(\bar{y}_{\cdot\cdot}\)</span> can be expressed as:</p>
<p><span class="math display">\[
\bar{y}_{i\cdot} = \left(\frac{1}{N}\right) \sum_{i=1}^k\sum_{j=1}^{n_i}y_{ij}
\]</span></p>
</div>
</div>
</div>
</div>
<p>where <span class="math inline">\(N\)</span> is the total sample size (sum of all <span class="math inline">\(n_i\)</span>).</p>
</div>
<div id="tabset-1-2">
<div title="Sum of Squares due to Factor A">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Sum of Squares due to Factor A</strong></p>
</div>
<div class="callout-content">
<p>Suppose the groups are dictated by a factor <span class="math inline">\(A\)</span> with <span class="math inline">\(k\)</span> levels. We define the sum of squares due to the factor <span class="math inline">\(A\)</span> as <span class="math inline">\(SSA\)</span> given by,</p>
<p><span class="math display">\[
SSA = \sum_{i=1}^k n_i(y_{i\cdot} - \bar{y}_{\cdot \cdot})^2
\]</span></p>
<p>This sum of squares measures the variability of the sample means from the overall mean.</p>
</div>
</div>
</div>
</div>
</div>
<div id="tabset-1-3">
<div title="Sum of Squares due to Error">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Sum of Squares due to Error</strong></p>
</div>
<div class="callout-content">
<p>The sum of squares due to error, denoted as SSE can be expressed as:</p>
<p><span class="math display">\[
SSE = \sum_{i=1}^k \sum_{j=1}^{n_i} (y_{ij} - \bar{y}_{i\cdot})^2
\]</span></p>
<p>This sum of squares measures the variability of each measurement to their respective group mean.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="total-sum-of-squares" class="slide level2">
<h2>Total Sum of Squares</h2>
<p>The total sum of squares, <span class="math inline">\(SST\)</span> can then be expressed as:</p>
<p><span class="math display">\[
SST = SSA + SSE
\]</span></p>
</section>
<section id="mean-squares" class="slide level2">
<h2>Mean Squares</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Factor Mean Squares</a></li><li><a href="#tabset-2-2">Error Sum of Squares</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<div title="Mean Squares due to Factor A">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mean Squares due to Factor A</strong></p>
</div>
<div class="callout-content">
<p>Suppose the groups are dictated by a factor <span class="math inline">\(A\)</span> with <span class="math inline">\(k\)</span> levels. We define the mean squares of factor <span class="math inline">\(A\)</span> as <span class="math inline">\(MSA\)</span> given by,</p>
<p><span class="math display">\[
MSA = \frac{SSA}{k-1}
\]</span></p>
<p>This sum of squares is an estimate of the variance between groups.</p>
</div>
</div>
</div>
</div>
</div>
<div id="tabset-2-2">
<div title="Mean Squares due to Error">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mean Squares due to Error</strong></p>
</div>
<div class="callout-content">
<p>We define the mean squares error as <span class="math inline">\(MSE\)</span> as,</p>
<p><span class="math display">\[
MSE = \frac{SSE}{N-k}
\]</span></p>
<p>where <span class="math inline">\(N\)</span> is the total number of samples.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="variance-ratio" class="slide level2">
<h2>Variance Ratio</h2>
<p>Recall that we want to compare the variability between groups and within groups. We do this by computing the following variance ratio, which we will use as our test statistic.</p>
<p><span class="math display">\[
VR = F = MSA/MSW
\]</span></p>
<p>This test statistic follows an F-distribution where the numerator degrees of freedom <span class="math inline">\(df_1 = k-1\)</span> and denominator degrees of freedom <span class="math inline">\(df_2 = N-k\)</span>.</p>
</section>
<section id="anova-table" class="slide level2">
<h2>ANOVA table</h2>
<p>The Analysis of Variance metrics can be summarized in an ANOVA table:</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Source of Variation</th>
<th>Sum of Squares</th>
<th>Degrees of Freedom</th>
<th>Mean Square</th>
<th>Variance Ratio or F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Factor A</td>
<td>SSA</td>
<td>(k-1)</td>
<td>MSA = SSA/(k-1)</td>
<td>MSA/MSE</td>
</tr>
<tr class="even">
<td>Error</td>
<td>SSE</td>
<td>(N-k)</td>
<td>MSE = SSE/(N-k)</td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>SST</td>
<td>(N-1)</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="r-implementation" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The rejection region can be determined using the F-statistic. In <code>R</code>, we can use the following functions to perform hypothesis testing, estimating linear model coefficients, and estimate group means.</p>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1"><code>aov()</code></a></li><li><a href="#tabset-3-2"><code>lm()</code></a></li><li><a href="#tabset-3-3"><code>emmeans()</code></a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p>The package <code>aov(formula,data)</code> in <code>R</code> works with the <code>summary</code> function to perform the single-factor ANOVA. For a response variable in column <code>y</code> and group variable in column <code>x</code> in a data set <code>df</code>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(y<span class="sc">~</span>x,<span class="at">data=</span>df)</span>
<span id="cb1-2"><a></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>It is recommended that the group variable <span class="math inline">\(x\)</span> is expressed as a factor.</p>
</div>
</div>
</div>
</div>
<div id="tabset-3-2">
<p>To view the estimates of the coefficients of the corresponding linear model, we use <code>lm(formula,data)</code> to estimate the linear model. These coefficients can be viewed using the <code>summary</code> function.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>df)</span>
<span id="cb2-2"><a></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>It is recommended that the group variable <span class="math inline">\(x\)</span> is expressed as a factor.</p>
</div>
</div>
</div>
</div>
<div id="tabset-3-3">
<p>The package <code>emmeans</code> contains the function <code>emmeans()</code> that calculates the group means based on the estimates of the linear models in <code>lm()</code></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb3-2"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>df)</span>
<span id="cb3-3"><a></a><span class="fu">emmeans</span>(mod1,<span class="sc">~</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="interpretation-of-null-hypothesis-rejection" class="slide level2">
<h2>Interpretation of Null Hypothesis Rejection</h2>
<p>The rejection of the null hypothesis implies sufficient evidence that not all population means are equal. However, there is no information on which groups have the different means.</p>
<p>Failure to reject the null hypothesis implies insufficient evidence that not all population means are equal.</p>
</section>
<section id="assumptions-of-anova" class="slide level2">
<h2>Assumptions of ANOVA</h2>
<p>ANOVA assumes the following:</p>
<ul>
<li>The data follows the Gaussian distribution</li>
<li>Groups have equal variances</li>
<li>Observations are independent of each other</li>
</ul>
</section>
<section id="effect-size" class="slide level2">
<h2>Effect Size</h2>
<p>A commonly reported effect size for ANOVA is the partial eta-squared (<span class="math inline">\(\eta^2_p\)</span>).</p>
<p><span class="math display">\[
\eta^2 = \frac{SSA}{SSA+SSE}
\]</span></p>
<p>This could also be calculated using the <code>effectsize</code> function in the <code>lsr</code> package in <code>R</code>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(\eta^2_p=0.01\)</span> is considered small, 0.06 is considered medium, and 0.14 is large.</p>
</div>
</div>
</div>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>
<p>Consider the <code>iris</code> data set loaded in <code>R</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a></a><span class="fu">glimpse</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 5
$ Sepal.Length &lt;dbl&gt; 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.…
$ Sepal.Width  &lt;dbl&gt; 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.…
$ Petal.Length &lt;dbl&gt; 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.…
$ Petal.Width  &lt;dbl&gt; 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.…
$ Species      &lt;fct&gt; setosa, setosa, setosa, setosa, setosa, setosa, setosa, s…</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Question</a></li><li><a href="#tabset-4-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<p>Use ANOVA to test if three species have different population average sepal length. Use a significance level of 0.05. Calculate the partial eta-squared value for the species effect.</p>
</div>
<div id="tabset-4-2">
<p>There are three species (“setosa”, “versicolor”, and “virginica”). The hypotheses are <span class="math inline">\(H_0:\)</span> The population average sepal length is equal for all three species. and <span class="math inline">\(H_a:\)</span> At least one population has a different average sepal length.</p>
<p>We now implement the ANOVA using <code>R</code>. To calculate the ANOVA table, we use <code>aov()</code></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="fu">install.packages</span>(<span class="st">"lsr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">library</span>(lsr)</span>
<span id="cb7-2"><a></a>mod_aov <span class="ot">&lt;-</span><span class="fu">aov</span>(Sepal.Length<span class="sc">~</span>Species,<span class="at">data=</span>iris)</span>
<span id="cb7-3"><a></a><span class="fu">summary</span>(mod_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
Species       2  63.21  31.606   119.3 &lt;2e-16 ***
Residuals   147  38.96   0.265                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="fu">etaSquared</span>(mod_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           eta.sq eta.sq.part
Species 0.6187057   0.6187057</code></pre>
</div>
</div>
<p>The p-value is &lt;2e-16, which is less than 0.05. We reject the null hypothesis and therefore there is sufficient evidence that at least one species has a different population average sepal length compared to the others. The effect size is 0.6187057</p>
<p>We examine the group means to see how much the group means differ using <code>emmeans()</code>. To use <code>emmeans()</code>, we need to create a linear model for the problem using <code>lm()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="co">#install emmeans first if not installed yet: </span></span>
<span id="cb11-2"><a></a><span class="co">#install.packages("emmeans")</span></span>
<span id="cb11-3"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb11-4"><a></a></span>
<span id="cb11-5"><a></a>mod_lm <span class="ot">&lt;-</span><span class="fu">lm</span>(Sepal.Length<span class="sc">~</span>Species,<span class="at">data=</span>iris)</span>
<span id="cb11-6"><a></a><span class="fu">summary</span>(mod_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Length ~ Species, data = iris)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6880 -0.3285 -0.0060  0.3120  1.3120 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         5.0060     0.0728  68.762  &lt; 2e-16 ***
Speciesversicolor   0.9300     0.1030   9.033 8.77e-16 ***
Speciesvirginica    1.5820     0.1030  15.366  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5148 on 147 degrees of freedom
Multiple R-squared:  0.6187,    Adjusted R-squared:  0.6135 
F-statistic: 119.3 on 2 and 147 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="fu">emmeans</span>(mod_lm,<span class="sc">~</span>Species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Species    emmean     SE  df lower.CL upper.CL
 setosa       5.01 0.0728 147     4.86     5.15
 versicolor   5.94 0.0728 147     5.79     6.08
 virginica    6.59 0.0728 147     6.44     6.73

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>We see that Setosa has the lowest average sepal length and Virginica has the highest average sepal length.</p>
</div>
</div>
</div>
</section>
<section id="exercise" class="slide level2">
<h2>Exercise</h2>
<p>The data set <code>penguins</code> from the <code>datasets</code> package in <code>R</code> includes data on adult penguins covering three species found on three islands in the Palmer Archipelago, Antarctica.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="fu">library</span>(datasets)</span>
<span id="cb15-2"><a></a><span class="fu">glimpse</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 344
Columns: 8
$ species     &lt;fct&gt; Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Ad…
$ island      &lt;fct&gt; Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Tor…
$ bill_len    &lt;dbl&gt; 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, 42.0, …
$ bill_dep    &lt;dbl&gt; 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, 20.2, …
$ flipper_len &lt;int&gt; 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186, 180,…
$ body_mass   &lt;int&gt; 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, 4250, …
$ sex         &lt;fct&gt; male, female, female, NA, female, male, female, male, NA, …
$ year        &lt;int&gt; 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="co"># disregard missing data:</span></span>
<span id="cb17-2"><a></a></span>
<span id="cb17-3"><a></a>penguins <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(penguins,bill_len)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Question</a></li><li><a href="#tabset-5-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<p>Test for a difference in average bill length (bill_len) between the species. Use a significance level of 0.05. Calculate the partial eta-squared for the species effect.</p>
</div>
<div id="tabset-5-2">
<p>The hypotheses are <span class="math inline">\(H_0:\)</span> The population average bill length is equal for all three species. and <span class="math inline">\(H_a:\)</span> At least one population has a different average bill length.</p>
<p>We now implement the ANOVA using <code>R</code>. To calculate the ANOVA table, we use <code>aov()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">library</span>(lsr)</span>
<span id="cb18-2"><a></a>mod_aov <span class="ot">&lt;-</span><span class="fu">aov</span>(bill_len<span class="sc">~</span>species,<span class="at">data=</span>penguins)</span>
<span id="cb18-3"><a></a><span class="fu">summary</span>(mod_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
species       2   7194    3597   410.6 &lt;2e-16 ***
Residuals   339   2970       9                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">etaSquared</span>(mod_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           eta.sq eta.sq.part
species 0.7078091   0.7078091</code></pre>
</div>
</div>
<p>The p-value is &lt;2e-16, which is less than 0.05. We reject the null hypothesis and therefore there is sufficient evidence that at least one species has a different population average bill length compared to the others. The effect size is 0.7078091</p>
<p>We examine the group means to see how much the group means differ using <code>emmeans()</code>. To use <code>emmeans()</code>, we need to create a linear model for the problem using <code>lm()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="co">#install emmeans first if not installed yet: </span></span>
<span id="cb22-2"><a></a><span class="co">#install.packages("emmeans")</span></span>
<span id="cb22-3"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb22-4"><a></a></span>
<span id="cb22-5"><a></a>mod_lm <span class="ot">&lt;-</span><span class="fu">lm</span>(bill_len<span class="sc">~</span>species,<span class="at">data=</span>penguins)</span>
<span id="cb22-6"><a></a><span class="fu">summary</span>(mod_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bill_len ~ species, data = penguins)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.9338 -2.2049  0.0086  2.0662 12.0951 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       38.7914     0.2409  161.05   &lt;2e-16 ***
speciesChinstrap  10.0424     0.4323   23.23   &lt;2e-16 ***
speciesGentoo      8.7135     0.3595   24.24   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.96 on 339 degrees of freedom
Multiple R-squared:  0.7078,    Adjusted R-squared:  0.7061 
F-statistic: 410.6 on 2 and 339 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="fu">emmeans</span>(mod_lm,<span class="sc">~</span>species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> species   emmean    SE  df lower.CL upper.CL
 Adelie      38.8 0.241 339     38.3     39.3
 Chinstrap   48.8 0.359 339     48.1     49.5
 Gentoo      47.5 0.267 339     47.0     48.0

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>We see that Adelie has the shortest average bill length, while Chinstrap and Gentoo have comparable average bill lengths.</p>
</div>
</div>
</div>
</section>
<section id="pairwise-comparisons-and-post-hoc-analysis" class="slide level2">
<h2>Pairwise Comparisons and Post-hoc Analysis</h2>
<p>Suppose we want to examine the means further to determine which groups are different when compared pairwise, i.e.&nbsp;A vs.&nbsp;B, A vs.&nbsp;C, B vs.&nbsp;C, etc. after rejecting the null hypothesis in ANOVA. This analysis is considered a post-hoc analysis.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Performing multiple pairwise t-tests and making inferences simultaneously can lead to multiplicity, which increases the chance of making a Type I error. We have to control for this when performing comparisons across the groups.</p>
</div>
</div>
</div>
</section>
<section id="multiplicity-corrections" class="slide level2">
<h2>Multiplicity corrections</h2>
<p>Two of the popular corrections to account for the Type I error inflation are:</p>
<ul>
<li>Bonferroni correction: for planned comparisons, i.e.&nbsp;These comparisons are planned before the study was implemented.</li>
<li>Tukey correction: for post-hoc comparisons, i.e.&nbsp;Comparisons done to examine which groups are different from each other after the rejection of an ANOVA hypothesis.</li>
</ul>
</section>
<section id="r-implementation-1" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The function <code>contrast</code> is applied to the <code>emmeans</code> function to estimate pairwise comparisons. Using previous examples,</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb26-2"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>df)</span>
<span id="cb26-3"><a></a>em_mod1 <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod1,<span class="sc">~</span>x)</span>
<span id="cb26-4"><a></a><span class="fu">contrast</span>(em_mod1,<span class="at">method=</span><span class="st">"pairwise"</span>,<span class="at">adjust=</span><span class="st">"tukey"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The Tukey correction can be applied by setting <code>adjust=tukey</code>, while the Bonferroni correction can be applied by setting <code>adjust="bon"</code>.</p>
</div>
</div>
</div>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<p>Consider the <code>iris</code> data set loaded in <code>R</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb27-2"><a></a><span class="fu">glimpse</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 5
$ Sepal.Length &lt;dbl&gt; 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.…
$ Sepal.Width  &lt;dbl&gt; 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.…
$ Petal.Length &lt;dbl&gt; 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.…
$ Petal.Width  &lt;dbl&gt; 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.…
$ Species      &lt;fct&gt; setosa, setosa, setosa, setosa, setosa, setosa, setosa, s…</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Question</a></li><li><a href="#tabset-6-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p>Recall that you rejected the null hypothesis after performing ANOVA. Perform pairwise comparisons to determine which groups have different sepal lengths. Use a significance level of 0.05 and the Tukey correction.</p>
</div>
<div id="tabset-6-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>mod_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Length<span class="sc">~</span>Species,<span class="at">data=</span>iris)</span>
<span id="cb29-2"><a></a>em_mod_lm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_lm,<span class="sc">~</span>Species)</span>
<span id="cb29-3"><a></a><span class="fu">contrast</span>(em_mod_lm,<span class="at">method=</span><span class="st">"pairwise"</span>,<span class="at">adjust=</span><span class="st">"tukey"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast               estimate    SE  df t.ratio p.value
 setosa - versicolor      -0.930 0.103 147  -9.033  &lt;.0001
 setosa - virginica       -1.582 0.103 147 -15.366  &lt;.0001
 versicolor - virginica   -0.652 0.103 147  -6.333  &lt;.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>The p-values are all less than 0.0001, which means we have sufficient evidence that all means are different from each other. Setosa sepal length was estimated to be 0.930 units lower than Versicolor and 1.58 units lower than Virginica. Versicolor sepal length was estimated to be 0.65 units lower than Virginica.</p>
</div>
</div>
</div>
</section>
<section id="exercise-1" class="slide level2">
<h2>Exercise</h2>
<p>The data set <code>penguins</code> from the <code>datasets</code> package in <code>R</code> includes data on adult penguins covering three species found on three islands in the Palmer Archipelago, Antarctica.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a><span class="fu">library</span>(datasets)</span>
<span id="cb31-2"><a></a><span class="fu">glimpse</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 342
Columns: 8
$ species     &lt;fct&gt; Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Ad…
$ island      &lt;fct&gt; Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Tor…
$ bill_len    &lt;dbl&gt; 39.1, 39.5, 40.3, 36.7, 39.3, 38.9, 39.2, 34.1, 42.0, 37.8…
$ bill_dep    &lt;dbl&gt; 18.7, 17.4, 18.0, 19.3, 20.6, 17.8, 19.6, 18.1, 20.2, 17.1…
$ flipper_len &lt;int&gt; 181, 186, 195, 193, 190, 181, 195, 193, 190, 186, 180, 182…
$ body_mass   &lt;int&gt; 3750, 3800, 3250, 3450, 3650, 3625, 4675, 3475, 4250, 3300…
$ sex         &lt;fct&gt; male, female, female, female, male, female, male, NA, NA, …
$ year        &lt;int&gt; 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a><span class="co"># disregard missing data:</span></span>
<span id="cb33-2"><a></a></span>
<span id="cb33-3"><a></a>penguins <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(penguins,bill_len)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Question</a></li><li><a href="#tabset-7-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<p>Perform pairwise comparisons of average bill length (in mm) across the three species. Use the Bonferroni correction and a significance level of 0.001.</p>
</div>
<div id="tabset-7-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="co">#install emmeans first if not installed yet: </span></span>
<span id="cb34-2"><a></a><span class="co">#install.packages("emmeans")</span></span>
<span id="cb34-3"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb34-4"><a></a></span>
<span id="cb34-5"><a></a>mod_lm <span class="ot">&lt;-</span><span class="fu">lm</span>(bill_len<span class="sc">~</span>species,<span class="at">data=</span>penguins)</span>
<span id="cb34-6"><a></a></span>
<span id="cb34-7"><a></a>em_mod_lm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_lm,<span class="sc">~</span>species)</span>
<span id="cb34-8"><a></a><span class="fu">contrast</span>(em_mod_lm,<span class="at">method=</span><span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast           estimate    SE  df t.ratio p.value
 Adelie - Chinstrap   -10.04 0.432 339 -23.232  &lt;.0001
 Adelie - Gentoo       -8.71 0.360 339 -24.237  &lt;.0001
 Chinstrap - Gentoo     1.33 0.447 339   2.971  0.0089

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>At significance level of 0.001, we have sufficient evidence that the average bill length of Adelie penguins is different from Chinstrap and Gentoo penguins by 10 mm and 8.7 mm, respectively. The difference between the average bill length of Chinstrap and Gentoo is 1.33, where we have insufficient evidence of a difference with p=0.0089.</p>
</div>
</div>
</div>
</section>
<section id="two-way-anova" class="slide level2">
<h2>Two-Way ANOVA</h2>
<p>Suppose we want to study the effect of two factors.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Suppose we want to investigate the interplay of pain relief and blood thinners on patient comfort level, We can perform separate analyses using single factor (or one-way) ANOVAs, but it will fail to capture the interplay between the two groups.</p>
</div>
</div>
</div>
</section>
<section id="interaction-effect" class="slide level2">
<h2>Interaction Effect</h2>
<p>Aside from the factor effects, we have to consider the interaction effect.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The interaction effect is defined as the difference in effect of one factor between the levels of the other factor. Consider two factors <span class="math inline">\(A\)</span> (levels: <span class="math inline">\(A_1\)</span> and <span class="math inline">\(A_2\)</span>) and <span class="math inline">\(B\)</span> (levels: <span class="math inline">\(B_1\)</span> and <span class="math inline">\(B_2\)</span>). The interaction effect can be interpreted as:</p>
<p><span class="math display">\[
\mu_{A1B1} - \mu_{A1B2} -(\mu_{A2B1} - \mu_{A2B2})
\]</span></p>
</div>
</div>
</div>
</section>
<section id="linear-model" class="slide level2">
<h2>Linear Model</h2>
<p>The linear model of the two-way ANOVA can be written as:</p>
<p><span class="math display">\[
Y_{ijk} = \mu + \alpha_i + \beta_j + (\alpha\beta)_{ij} + \varepsilon_{ijk}
\]</span> where <span class="math inline">\(\alpha\)</span> is the main effect of Factor A, <span class="math inline">\(\beta\)</span> is the main effect of Factor B, and <span class="math inline">\((\alpha\beta)\)</span> is the interaction effect between Factors A and B.</p>
</section>
<section id="anova-table-1" class="slide level2">
<h2>ANOVA Table</h2>
<p>If Factor A has <span class="math inline">\(a\)</span> levels and Factor B has <span class="math inline">\(b\)</span> levels and total sample size <span class="math inline">\(N\)</span>, the ANOVA table can be expressed as:</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Source of Variation</th>
<th>Sum of Squares</th>
<th>Degrees of Freedom</th>
<th>Mean Square</th>
<th>Variance Ratio or F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Factor A</td>
<td>SSA</td>
<td>(a-1)</td>
<td>MSA = SSA/(a-1)</td>
<td>MSA/MSE</td>
</tr>
<tr class="even">
<td>Factor B</td>
<td>SSB</td>
<td>(b-1)</td>
<td>MSA = SSB/(b-1)</td>
<td>MSB/MSE</td>
</tr>
<tr class="odd">
<td>Interaction A*B</td>
<td>SSAB</td>
<td>(a-1)(b-1)</td>
<td>MSA = SSAB/((a-1)(b-1))</td>
<td>MSAB/MSE</td>
</tr>
<tr class="even">
<td>Error</td>
<td>SSE</td>
<td>N-ab</td>
<td>MSE = SSE/(N-k)</td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>SST</td>
<td>N-1</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="analysis" class="slide level2">
<h2>Analysis</h2>
<p>Here is a guide on how to perform a two-way ANOVA:</p>
<ul>
<li>Check if we have sufficient evidence of an interaction effect.</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>If there is evidence of an interaction effect, the main effects are NOT interpretable. You must compare the levels of A under all levels of B and vice versa. Interaction effects are slightly different from effect modification analysis, where we are only concerned with the effect of one factor in the levels of the other, e.g.&nbsp;effect of drugs for all levels of sex.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>If there is no evidence of an interaction effect, the main effects can be interpreted similar to the result of a one-way/single-factor ANOVA.</p>
</div>
</div>
</div>
</section>
<section id="r-implementation-2" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The same functions used in the single factor ANOVA are used to perform a two-way ANOVA. However, the model specification is slightly different.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb36-2"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>A<span class="sc">+</span>B<span class="sc">+</span>A<span class="sc">:</span>B,<span class="at">data=</span>df)</span>
<span id="cb36-3"><a></a><span class="fu">emmeans</span>(mod1,<span class="sc">~</span>A<span class="sc">*</span>B)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="example-2" class="slide level2">
<h2>Example</h2>
<p>The data set <code>lec8_example.csv</code> includes simulated data from a study that randomly sampled 20 individuals with and without family history of hypertension. These individuals were randomly assigned to two treatments for hypertension, A and B. The systolic blood pressure was measured for each participant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a>systolic <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"lec8_example.csv"</span>)</span>
<span id="cb37-2"><a></a><span class="fu">glimpse</span>(systolic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 40
Columns: 3
$ Treatment &lt;chr&gt; "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B", "B", …
$ History   &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes…
$ Systolic  &lt;int&gt; 141, 137, 136, 131, 133, 141, 129, 134, 134, 141, 132, 127, …</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Question</a></li><li><a href="#tabset-8-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p>Test for an interaction effect between family history and hypertension. Provide the estimated group means for each group.</p>
</div>
<div id="tabset-8-2">
<p>The null hypothesis is <span class="math inline">\(H_0:\)</span> there is no interaction between family history and hypertension and the alternative hypothesis is <span class="math inline">\(H_a\)</span>: there is an interaction between family history and hypertension.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a>mod_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Systolic<span class="sc">~</span>Treatment <span class="sc">+</span> History <span class="sc">+</span> Treatment<span class="sc">:</span>History,<span class="at">data=</span>systolic)</span>
<span id="cb39-2"><a></a><span class="fu">summary</span>(mod_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Treatment          1  330.6   330.6   13.27 0.000841 ***
History            1 1729.2  1729.2   69.42  6.4e-10 ***
Treatment:History  1  442.2   442.2   17.75 0.000161 ***
Residuals         36  896.7    24.9                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a><span class="fu">etaSquared</span>(mod_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     eta.sq eta.sq.part
Treatment         0.0972777   0.2693867
History           0.5087789   0.6585203
Treatment:History 0.1301131   0.3302836</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb43-2"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Systolic<span class="sc">~</span>Treatment <span class="sc">+</span> History <span class="sc">+</span> Treatment<span class="sc">:</span>History,<span class="at">data=</span>systolic)</span>
<span id="cb43-3"><a></a><span class="fu">emmeans</span>(mod1,<span class="sc">~</span>Treatment<span class="sc">:</span>History)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Treatment History emmean   SE df lower.CL upper.CL
 A         No         116 1.58 36      113      119
 B         No         117 1.58 36      114      120
 A         Yes        136 1.58 36      132      139
 B         Yes        123 1.58 36      120      127

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a><span class="fu">plot</span>(<span class="fu">emmeans</span>(mod1,<span class="sc">~</span>Treatment<span class="sc">|</span>History))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture8_files/figure-revealjs/unnamed-chunk-12-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p>There is evidence of an interaction between treatment and family history ($^2_p=0.33,p=0.0002). Based on the calculated means, the difference between the treatments was higher for those with family history of hypertension compared to those without.</p>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="slide level2">
<h2>Exercise</h2>
<p>The data set <code>COVID-Zinc-AscorbicAcid.csv</code> contains data from a clinical trial that tested the efficacy of using high doses of zinc and/or ascorbic acid (vitamin C) on the recovery time for COVID-19. They studied a number of outcome variables, including the time to 50% reduction in symptoms. Those marked with <code>1</code> for Zinc and Ascorbic Acid received the treatment, while those marked with <code>-1</code> did not.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a>covid <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"COVID-Zinc-AscorbicAcid.csv"</span>)</span>
<span id="cb46-2"><a></a><span class="fu">glimpse</span>(covid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 20
Columns: 4
$ obs                     &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…
$ AscorbicAcid            &lt;int&gt; -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, …
$ Zinc                    &lt;int&gt; -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, -1, -1, -1,…
$ DaysUntil50PctReduction &lt;dbl&gt; 2.6, 4.4, 14.1, 6.0, 6.4, 13.3, 8.0, 0.8, 3.2,…</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Question</a></li><li><a href="#tabset-9-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<ul>
<li>Test for an interaction between the Ascorbic Acid and Zinc factors.</li>
<li>Is there evidence of efficacy of the two treatments?</li>
</ul>
</div>
<div id="tabset-9-2">
<p>The null hypothesis is <span class="math inline">\(H_0:\)</span> there is no interaction between Ascorbic Acid and Zinc treatments and the alternative hypothesis is <span class="math inline">\(H_a\)</span>: there is an interaction between between Ascorbic Acid and Zinc treatments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a>mod_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(DaysUntil50PctReduction<span class="sc">~</span>AscorbicAcid <span class="sc">+</span> Zinc <span class="sc">+</span> AscorbicAcid<span class="sc">:</span>Zinc,<span class="at">data=</span>covid)</span>
<span id="cb48-2"><a></a><span class="fu">summary</span>(mod_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Df Sum Sq Mean Sq F value Pr(&gt;F)
AscorbicAcid       1   3.28   3.281   0.192  0.667
Zinc               1   0.84   0.840   0.049  0.827
AscorbicAcid:Zinc  1   0.76   0.760   0.045  0.836
Residuals         16 273.17  17.073               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a></a><span class="fu">etaSquared</span>(mod_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       eta.sq eta.sq.part
AscorbicAcid      0.011798259 0.011866586
Zinc              0.003022843 0.003067423
AscorbicAcid:Zinc 0.002735125 0.002776272</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb52-2"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DaysUntil50PctReduction<span class="sc">~</span>AscorbicAcid <span class="sc">+</span> Zinc <span class="sc">+</span> AscorbicAcid<span class="sc">:</span>Zinc,<span class="at">data=</span>covid)</span>
<span id="cb52-3"><a></a><span class="fu">emmeans</span>(mod1,<span class="sc">~</span>AscorbicAcid<span class="sc">:</span>Zinc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> AscorbicAcid Zinc emmean   SE df lower.CL upper.CL
           -1   -1   6.70 1.85 16     2.78    10.62
            1   -1   5.50 1.85 16     1.58     9.42
           -1    1   5.90 1.85 16     1.98     9.82
            1    1   5.48 1.85 16     1.56     9.40

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a></a><span class="fu">plot</span>(<span class="fu">emmeans</span>(mod1,<span class="sc">~</span>AscorbicAcid<span class="sc">|</span>Zinc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture8_files/figure-revealjs/unnamed-chunk-14-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p>There is no evidence of an interaction between Ascorbic Acid and Zinc (<span class="math inline">\(\eta^2_p\)</span>=0, p=0.84). There is also no evidence of efficacy for Ascorbic Acid (<span class="math inline">\(\eta^2_p\)</span>=0.01, p=0.67) and Zinc (<span class="math inline">\(\eta^2_p\)</span>=0, p=0.83)</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Lecture 8 - <a href="https://madfudolig.quarto.pub/introtobiostats/">Back to home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp("https:\/\/madfudolig\.quarto\.pub\/introtobiostats");
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
          let selectedAnnoteEl;
          const selectorForAnnotation = ( cell, annotation) => {
            let cellAttr = 'data-code-cell="' + cell + '"';
            let lineAttr = 'data-code-annotation="' +  annotation + '"';
            const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
            return selector;
          }
          const selectCodeLines = (annoteEl) => {
            const doc = window.document;
            const targetCell = annoteEl.getAttribute("data-target-cell");
            const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
            const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            const lines = annoteSpan.getAttribute("data-code-lines").split(",");
            const lineIds = lines.map((line) => {
              return targetCell + "-" + line;
            })
            let top = null;
            let height = null;
            let parent = null;
            if (lineIds.length > 0) {
                //compute the position of the single el (top and bottom and make a div)
                const el = window.document.getElementById(lineIds[0]);
                top = el.offsetTop;
                height = el.offsetHeight;
                parent = el.parentElement.parentElement;
              if (lineIds.length > 1) {
                const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                height = bottom - top;
              }
              if (top !== null && height !== null && parent !== null) {
                // cook up a div (if necessary) and position it 
                let div = window.document.getElementById("code-annotation-line-highlight");
                if (div === null) {
                  div = window.document.createElement("div");
                  div.setAttribute("id", "code-annotation-line-highlight");
                  div.style.position = 'absolute';
                  parent.appendChild(div);
                }
                div.style.top = top - 2 + "px";
                div.style.height = height + 4 + "px";
                div.style.left = 0;
                let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                if (gutterDiv === null) {
                  gutterDiv = window.document.createElement("div");
                  gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                  gutterDiv.style.position = 'absolute';
                  const codeCell = window.document.getElementById(targetCell);
                  const gutter = codeCell.querySelector('.code-annotation-gutter');
                  gutter.appendChild(gutterDiv);
                }
                gutterDiv.style.top = top - 2 + "px";
                gutterDiv.style.height = height + 4 + "px";
              }
              selectedAnnoteEl = annoteEl;
            }
          };
          const unselectCodeLines = () => {
            const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
            elementsIds.forEach((elId) => {
              const div = window.document.getElementById(elId);
              if (div) {
                div.remove();
              }
            });
            selectedAnnoteEl = undefined;
          };
            // Handle positioning of the toggle
        window.addEventListener(
          "resize",
          throttle(() => {
            elRect = undefined;
            if (selectedAnnoteEl) {
              selectCodeLines(selectedAnnoteEl);
            }
          }, 10)
        );
        function throttle(fn, ms) {
        let throttle = false;
        let timer;
          return (...args) => {
            if(!throttle) { // first call gets through
                fn.apply(this, args);
                throttle = true;
            } else { // all the others get throttled
                if(timer) clearTimeout(timer); // cancel #2
                timer = setTimeout(() => {
                  fn.apply(this, args);
                  timer = throttle = false;
                }, ms);
            }
          };
        }
          const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
          for (let i=0; i<annoteTargets.length; i++) {
            const annoteTarget = annoteTargets[i];
            const targetCell = annoteTarget.getAttribute("data-target-cell");
            const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
            const contentFn = () => {
              const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              if (content) {
                const tipContent = content.cloneNode(true);
                tipContent.classList.add("code-annotation-tip-content");
                return tipContent.outerHTML;
              }
            }
            const config = {
              allowHTML: true,
              content: contentFn,
              onShow: (instance) => {
                selectCodeLines(instance.reference);
                instance.reference.classList.add('code-annotation-active');
                window.tippy.hideAll();
              },
              onHide: (instance) => {
                unselectCodeLines();
                instance.reference.classList.remove('code-annotation-active');
              },
              maxWidth: 300,
              delay: [50, 0],
              duration: [200, 0],
              offset: [5, 10],
              arrow: true,
              appendTo: function(el) {
                return el.parentElement.parentElement.parentElement;
              },
              interactive: true,
              interactiveBorder: 10,
              theme: 'light-border',
              placement: 'right',
              popperOptions: {
                modifiers: [
                {
                  name: 'flip',
                  options: {
                    flipVariations: false, // true by default
                    allowedAutoPlacements: ['right'],
                    fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                  },
                },
                {
                  name: 'preventOverflow',
                  options: {
                    mainAxis: false,
                    altAxis: false
                  }
                }
                ]        
              }      
            };
            window.tippy(annoteTarget, config); 
          }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>