<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>EAB 703-1002: Biostatistical Methods for the Health Sciences – Regression Analysis</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-12873a65cf666e61daa4b3cf91a98e13.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Regression Analysis</h1>
  <p class="subtitle">Lecture 9</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="outline" class="title-slide slide level1 center">
<h1>Outline</h1>
<ul>
<li>Definition of Terms</li>
<li>Simple Linear Regression</li>
<li>Multiple Linear Regression</li>
<li>Diagnostics</li>
<li>Correlation</li>
</ul>
</section>

<section>
<section id="definition-of-terms" class="title-slide slide level1 center">
<h1>Definition of Terms</h1>

</section>
<section id="prediction-vs.-explanation" class="slide level2">
<h2>Prediction vs.&nbsp;Explanation</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>In a prediction problem, the investigators do not necessarily need to know the rule used to predict the outcome. Attention is focused on accuracy.</p>
<p>In an explanation problem, the investigators will often assume a functional form for the dependent variable, similar to the <a href="https://madfudolig.quarto.pub/introtobiostats/lecture8.html#/general-form-of-linear-models">linear model</a> in Lecture 8.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Prediction problems do not need a functional form, hence functional relations between independent and dependent variables will not be identified.</p>
</div>
</div>
</div>
</section>
<section id="correlation-vs.-regression" class="slide level2">
<h2>Correlation vs.&nbsp;Regression</h2>
<div title="Regression Analysis">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Regression Analysis</strong></p>
</div>
<div class="callout-content">
<p>Regression analysis is helpful in assessing specific forms of the relationship between variables, and the ultimate objective when this method of analysis is employed usually is to predict or estimate the value of one variable corresponding to a given value of another variable.</p>
</div>
</div>
</div>
</div>
<div title="Correlation Analysis">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Correlation Analysis</strong></p>
</div>
<div class="callout-content">
<p>Correlation analysis is concerned with measuring the strength of the relationship between variables. It cannot predict or estimate unlike regression.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="simple-linear-regression" class="title-slide slide level1 center">
<h1>Simple Linear Regression</h1>

</section>
<section id="linear-regression" class="slide level2">
<h2>Linear Regression</h2>
<p>We are often interested in how one or more predictor/independent variables are associated with an outcome/response/dependent variable. In linear regression, we assume this association is defined by a linear function.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Linear regression models are used when the independent and dependent variables are both <strong>continuous</strong>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>It is important to keep in mind that our linear assumption is rarely met in practice. We may never know the true model, but information obtained from the linear model can still yield useful results, especially with exploratory data analysis.</p>
</div>
</div>
</div>
</section>
<section id="simple-linear-regression-model" class="slide level2">
<h2>Simple Linear Regression Model</h2>
<p>Recall Lecture 8: Linear regression models are a part of general linear models. In linear regression, a linear relationship is assumed between the independent variable <span class="math inline">\(X\)</span> and the dependent variable <span class="math inline">\(Y\)</span>. For the <span class="math inline">\(i^{th}\)</span> observation (<span class="math inline">\(X_i\)</span>,<span class="math inline">\(Y_i\)</span>)</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1X_i+ \varepsilon_i
\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The error term <span class="math inline">\(\varepsilon_i\)</span> are independent and identically distributed Gaussian errors (mean 0 and variance <span class="math inline">\(\sigma^2\)</span>). Recall that the error term contributes solely to the variance and not the mean of <span class="math inline">\(Y\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>

<img data-src="lecture9_files/figure-revealjs/unnamed-chunk-1-1.png" width="960" class="r-stretch"></section>
<section id="method-of-least-squares" class="slide level2">
<h2>Method of Least Squares</h2>
<p>To define the linear regression model, we need to estimate the following terms: the intercept, <span class="math inline">\(\beta_0\)</span>; the slope <span class="math inline">\(\beta_1\)</span>, and the variance <span class="math inline">\(\sigma^2\)</span>. The intercept and the slope can be estimated using the <strong>method of least squares</strong>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The method of least squares can be visualized using the following <a href="https://www.rossmanchance.com/applets/2021/regshuffle/regshuffle.htm">link</a>.</p>
</div>
</div>
</div>
</section>
<section id="estimation" class="slide level2">
<h2>Estimation</h2>
<p>Suppose we have an estimate of the intercept <span class="math inline">\(\hat{\beta}_0\)</span> and the slope <span class="math inline">\(\hat{\beta}_1\)</span>. The estimated value of the dependent variable <span class="math inline">\(\hat{Y}_i\)</span> for a value of the independent variable <span class="math inline">\(X_i\)</span> can be expressed as:</p>
<p><span class="math display">\[
\hat{Y}_i = \hat{\beta}_0 + \hat{\beta}_1 X_i
\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The slope estimate <span class="math inline">\(\hat{\beta}_1\)</span> is the expected change in the dependent variable for a 1-unit increase in <span class="math inline">\(X_i\)</span>. Generally, for a <span class="math inline">\(d\)</span> unit increase in <span class="math inline">\(X_i\)</span>, the dependent variable is expected to change by <span class="math inline">\(d\hat{\beta}_1\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="assumptions-of-linear-regression" class="slide level2">
<h2>Assumptions of Linear Regression</h2>
<ul>
<li>The means of the subpopulations of <span class="math inline">\(Y\)</span> all lie on the same straight line, also known as the linearity assumption.</li>
<li>The values of <span class="math inline">\(Y\)</span> are statistically independent.</li>
<li>For each value of <span class="math inline">\(X\)</span> there is a subpopulation of <span class="math inline">\(Y\)</span> values. For the usual inferential procedures of estimation and hypothesis testing to be valid, these subpopulations must be normally distributed.</li>
<li>The variances of the subpopulations of <span class="math inline">\(Y\)</span> are all equal to <span class="math inline">\(\sigma^2\)</span>.</li>
<li>The independent variable can be measured without error or with negligible error.</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The first four assumptions are also known as the LINE assumptions: <strong>Linearity, Independence, Normality, Equal Variances</strong></p>
</div>
</div>
</div>
</section>
<section id="hypothesis-testing-linear-regression" class="slide level2">
<h2>Hypothesis Testing: Linear Regression</h2>
<p>In examining the association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, the important parameter for inference is the slope <span class="math inline">\(\beta_1\)</span>.</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Slope and Association</a></li><li><a href="#tabset-1-2">Statistical Hypotheses</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>When <span class="math inline">\(\beta_1=0\)</span>, the best fit line resembles a horizontal line, indicating a lack of association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
<p>If <span class="math inline">\(\beta_1 &gt; 0\)</span>, the slope of the best fit line is positive, indicating a positive direct association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
<p>If <span class="math inline">\(\beta_1&lt;0\)</span>, the slope of the best fit line is negative, indicating a negative direct association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
<p>Simply put, <span class="math inline">\(\beta_1 \neq 0\)</span> indicates that there is an association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
</div>
</div>
</div>
</div>
<div id="tabset-1-2">
<p>The null hypothesis of no association can be expressed as <span class="math inline">\(H_0: \beta_1=0\)</span>. The alternatives can be expressed as one-sided or two-sided.</p>
<ul>
<li>One-sided: <span class="math inline">\(\beta_1 &gt;0\)</span> or <span class="math inline">\(\beta_1 &lt; 0\)</span></li>
<li>Two-sided: <span class="math inline">\(\beta_1 \neq 0\)</span></li>
</ul>
</div>
</div>
</div>
</section>
<section id="test-statistic-t" class="slide level2">
<h2>Test Statistic: <span class="math inline">\(t\)</span></h2>
<p>Suppose the estimated value of <span class="math inline">\(\beta_1\)</span> is <span class="math inline">\(\hat{\beta}_1\)</span>. The test statistic when testing the hypotheses for <span class="math inline">\(\beta_1\)</span> can be expressed as:</p>
<p><span class="math display">\[
t = \frac{\hat{\beta}_1}{\sqrt{S^2/S_{XX}^2}}
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(S^2\)</span> is given by the following equation:</p>
<p><span class="math display">\[
S^2 = \frac{\sum_i (Y_i-\hat{Y}_i)^2}{(n-2)}
\]</span></p>
<p>The term <span class="math inline">\((Y_i-\hat{Y}_i)\)</span> is also called the <em>residual</em> of the model. On the other hand, <span class="math inline">\(S_{XX}^2\)</span> is defined as the sum of squares of the independent variable.</p>
<p><span class="math display">\[
S_{XX}^2 = \sum_i (X_i-\bar{X})^2
\]</span></p>
</div>
</div>
</div>
</section>
<section id="test-statistic-f" class="slide level2">
<h2>Test Statistic: <span class="math inline">\(F\)</span></h2>
<p>An analysis of variance (ANOVA) table can also be constructed from the regression model. This framework separates the source of variation accounted by the model and the error.</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Source of Variation</th>
<th>Sum of Squares (SS)</th>
<th>Degrees of Freedom (DF)</th>
<th>Mean Squares (MS)</th>
<th>Variance Ratio (F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regression</td>
<td>SSR</td>
<td>1</td>
<td>MSR = SSR</td>
<td>MSR/MSE</td>
</tr>
<tr class="even">
<td>Error</td>
<td>SSE</td>
<td>n-2</td>
<td>MSE = SSE/(n-2)</td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>SST</td>
<td>n-1</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>The test statistic <span class="math inline">\(F = MSR/MSE\)</span> follows an F-distribution with degrees of freedom <span class="math inline">\((df_1,df_2) = (1,n-2)\)</span>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>This tests the following hypotheses: <span class="math inline">\(H_0: \beta_1=0\)</span> and <span class="math inline">\(H_a: \beta_1 \neq 0\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="goodness-of-fit-r2" class="slide level2">
<h2>Goodness of Fit: <span class="math inline">\(R^2\)</span></h2>
<p>We define the coefficient of determination, also known as <span class="math inline">\(R^2\)</span>, as the following ratio:</p>
<p><span class="math display">\[
R^2 = SSR/(SSR + SSE)
\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(R^2\)</span> is non-negative and cannot exceed 1. The <span class="math inline">\(R^2\)</span> measures the proportion of the variability explained by the predictor in the model. The higher the value of <span class="math inline">\(R^2\)</span>, the closer the fit of the data to the model.</p>
<p><span class="math inline">\(R^2 = 1\)</span> indicates a perfect fit, but is almost always not observed in real-life situations.</p>
</div>
</div>
</div>
</section>
<section id="r-implementation-lm" class="slide level2">
<h2><code>R</code> Implementation: <code>lm()</code></h2>
<p>The function <code>lm()</code> can perform calculations for linear regression. The function <code>summary()</code> is used with <code>lm()</code> to provide estimates for the intercept, slope, and residual variance. The <code>summary()</code> output also includes the results of the tests involving the slopes (both <span class="math inline">\(t\)</span> and <span class="math inline">\(F\)</span>).</p>
<p>Sample code should follow how we used <code>lm()</code> in Lecture 8:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DepVar<span class="sc">~</span>IndepVar,<span class="at">data=</span>df)</span>
<span id="cb1-2"><a></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The <code>summary()</code> function also provides the <span class="math inline">\(R^2\)</span> value of the model.</p>
</div>
</div>
</div>
</section>
<section id="r-implementation-visualization" class="slide level2">
<h2><code>R</code> implementation: Visualization</h2>
<p>The <code>ggplot2</code> package is primarily used for data visualization. This package is included in the <code>tidyverse</code> package.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The <code>geom_point()</code> is used to plot the observed data points, while <code>geom_smooth(method,formula)</code> is used to overlay the best fit line on the observed data points.</p>
</div>
</div>
</div>
<h3 id="sample-code">Sample code</h3>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>df,<span class="fu">aes</span>(<span class="at">x=</span>IndepVar,<span class="at">y=</span>DepVar)) <span class="sc">+</span></span>
<span id="cb2-2"><a></a><span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb2-3"><a></a><span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">formula=</span>y<span class="sc">~</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="framework-for-analysis" class="slide level2">
<h2>Framework for Analysis</h2>
<p>Here are the recommended steps in performing regression analysis:</p>
<ul>
<li>Visualize the data using <code>ggplot2()</code>. Is there a discernible linear trend?</li>
<li>Obtain the equation of the best fit line using <code>lm()</code> and <code>summary()</code>.</li>
<li>Evaluate the equation to obtain a measure of the strength of association between the independent and dependent variables (hypothesis tests).</li>
<li>Use <code>geom_smooth()</code> as a litmus test of model fit.</li>
</ul>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<p>The data set <code>trees</code> (loaded in <code>R</code>) includes the measurements of the diameter (inches), height (ft), and volume (cubic ft) of timber in 31 felled black cherry trees. The diameter, labeled as Girth, is measured at 4’6” above the ground.</p>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Question</a></li><li><a href="#tabset-2-2">Plot before Fit</a></li><li><a href="#tabset-2-3">Fit</a></li><li><a href="#tabset-2-4">Plot after Fit</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p>Test the hypothesis that there is an association between the diameter and height of the cherry trees. Use simple linear regression to estimate the best fit line that estimates the height of the cherry trees based on its diameter. What is the <span class="math inline">\(R^2\)</span> value?</p>
</div>
<div id="tabset-2-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb3-2"><a></a><span class="fu">glimpse</span>(trees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 31
Columns: 3
$ Girth  &lt;dbl&gt; 8.3, 8.6, 8.8, 10.5, 10.7, 10.8, 11.0, 11.0, 11.1, 11.2, 11.3, …
$ Height &lt;dbl&gt; 70, 65, 63, 72, 81, 83, 66, 75, 80, 75, 79, 76, 76, 69, 75, 74,…
$ Volume &lt;dbl&gt; 10.3, 10.3, 10.2, 16.4, 18.8, 19.7, 15.6, 18.2, 22.6, 19.9, 24.…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>trees,<span class="fu">aes</span>(<span class="at">x=</span>Girth,<span class="at">y=</span>Height)) <span class="sc">+</span> </span>
<span id="cb5-2"><a></a>  <span class="fu">geom_point</span>()  <span class="sc">+</span> </span>
<span id="cb5-3"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb5-4"><a></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Diameter (in)"</span>, <span class="at">y=</span><span class="st">"Height (ft)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-2-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Height<span class="sc">~</span>Girth,<span class="at">data=</span>trees)</span>
<span id="cb6-2"><a></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Height ~ Girth, data = trees)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.5816  -2.7686   0.3163   2.4728   9.9456 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  62.0313     4.3833  14.152 1.49e-14 ***
Girth         1.0544     0.3222   3.272  0.00276 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.538 on 29 degrees of freedom
Multiple R-squared:  0.2697,    Adjusted R-squared:  0.2445 
F-statistic: 10.71 on 1 and 29 DF,  p-value: 0.002758</code></pre>
</div>
</div>
<p>The estimated equation for the tree height is <span class="math inline">\(\hat{height} = 1.0544*Diameter + 62.0313\)</span>.</p>
<p>The p-value of the coefficient is 0.0028, and the test statistic <span class="math inline">\(t\)</span> is 3.27. There is sufficient evidence of an association between diameter and height. The value of <span class="math inline">\(R^2\)</span> is 0.27.</p>
</div>
<div id="tabset-2-4">
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb8-2"><a></a><span class="fu">glimpse</span>(trees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 31
Columns: 3
$ Girth  &lt;dbl&gt; 8.3, 8.6, 8.8, 10.5, 10.7, 10.8, 11.0, 11.0, 11.1, 11.2, 11.3, …
$ Height &lt;dbl&gt; 70, 65, 63, 72, 81, 83, 66, 75, 80, 75, 79, 76, 76, 69, 75, 74,…
$ Volume &lt;dbl&gt; 10.3, 10.3, 10.2, 16.4, 18.8, 19.7, 15.6, 18.2, 22.6, 19.9, 24.…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>trees,<span class="fu">aes</span>(<span class="at">x=</span>Girth,<span class="at">y=</span>Height)) <span class="sc">+</span> </span>
<span id="cb10-2"><a></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb10-3"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">formula=</span>y<span class="sc">~</span>x,<span class="at">se=</span>F) <span class="sc">+</span> </span>
<span id="cb10-4"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb10-5"><a></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Diameter (in)"</span>, <span class="at">y=</span><span class="st">"Height (ft)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-4-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="r-implementation-estimationprediction" class="slide level2">
<h2><code>R</code> implementation: Estimation/Prediction</h2>
<p>Recall that we can estimate the value of the dependent variable using our best fit line. Recall that for a value of the independent variable <span class="math inline">\(X\)</span>, the estimated value of the dependent variable <span class="math inline">\(\hat{Y}\)</span> is:</p>
<p><span class="math display">\[
\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 * X
\]</span></p>
<p>In <code>R</code>, we can use the <code>predict</code> function with <code>lm()</code> to calculate predicted values for one or more values of the independent variable. It can also output confidence and prediction intervals</p>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Extrapolation</a></li><li><a href="#tabset-3-2">Intercept</a></li><li><a href="#tabset-3-3">Confidence vs.&nbsp;Prediction Intervals</a></li><li><a href="#tabset-3-4">Sample Code</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Estimation/Prediction using linear regression works best if the considered value of the independent variable is within the range of the data used to fit the regression line (interpolation). Estimation outside this range is referred to as extrapolation, which is not a recommended practice.</p>
</div>
</div>
</div>
</div>
<div id="tabset-3-2">
<p>The intercept is the estimated value of the dependent variable when the independent variable is equal to 0. Interpreting the intercept can be considered as extrapolation if 0 is not within the range of the independent variable. It might also be trivial to interpret the intercept if the case of <span class="math inline">\(X=0\)</span> is trivial.</p>
</div>
<div id="tabset-3-3">
<p><strong>Confidence intervals</strong> are made for parameters, whereas an interval for random variables are called <strong>prediction intervals</strong>. Prediction interval are generally wider than confidence intervals.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>For example, if we want to determine an interval estimate for the mean height of a tree with girth <span class="math inline">\(X\)</span>, then we use a confidence interval. If we want to estimate the height of a particular tree with girth <span class="math inline">\(X\)</span>, then we use a prediction interval</p>
</div>
</div>
</div>
</div>
<div id="tabset-3-4">
<div class="sourceCode" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DepVar<span class="sc">~</span>IndepVar,<span class="at">data=</span>df)</span>
<span id="cb11-2"><a></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">IndepVar=</span><span class="fu">c</span>(X)) <span class="co"># substitute X with the value of the independent variable you want to estimate the value of the predictor for.</span></span>
<span id="cb11-3"><a></a></span>
<span id="cb11-4"><a></a>newdata<span class="sc">$</span>prediction <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1,newdata,<span class="at">interval =</span> <span class="st">"confidence"</span>,<span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb11-5"><a></a>newdata<span class="sc">$</span>prediction <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1,newdata,<span class="at">interval =</span> <span class="st">"prediction"</span>,<span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb11-6"><a></a>newdata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="example-2" class="slide level2">
<h2>Example</h2>
<p>The data set <code>trees</code> (loaded in <code>R</code>) includes the measurements of the diameter, height, and volume of timber in 31 felled black cherry trees. The diameter, labeled as Girth, is measured at 4’6” above the ground.</p>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Question</a></li><li><a href="#tabset-4-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<ul>
<li>Calculate the estimated height of the black cherry trees with the following diameters: 10 inches, 15 inches, 20 inches with the corresponding prediction intervals.</li>
<li>Is it advisable to interpret the intercept? Explain.</li>
<li>Is it advisable to use this regression line to estimate the height of a black cherry tree with a 25-inch diameter? Explain.</li>
</ul>
</div>
<div id="tabset-4-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Height<span class="sc">~</span>Girth,<span class="at">data=</span>trees)</span>
<span id="cb12-2"><a></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Girth=</span><span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">15</span>,<span class="dv">20</span>))</span>
<span id="cb12-3"><a></a>newdata<span class="sc">$</span>prediction <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1,<span class="at">newdata=</span>newdata,<span class="at">interval =</span> <span class="st">"prediction"</span>,<span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb12-4"><a></a>newdata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Girth prediction.fit prediction.lwr prediction.upr
1    10       72.57500       60.86890       84.28110
2    15       77.84685       66.28041       89.41328
3    20       83.11869       70.77983       95.45755</code></pre>
</div>
</div>
<p>It is not advisable to interpret the intercept because it is trivial to examine the case when the tree diameter is equal to zero. It is also outside the range of diameters considered in the study. Specifically, the range shown below does not include zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">range</span>(trees<span class="sc">$</span>Girth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  8.3 20.6</code></pre>
</div>
</div>
<p>Similarly, X=25 is not in the range of diameters considered in the study and would lead to extrapolation if used in estimation. Hence, estimating the height of a tree with a 25-inch diameter using our best fit line is not recommended.</p>
</div>
</div>
</div>
</section>
<section id="exercise" class="slide level2">
<h2>Exercise</h2>
<p>Consider the liver steatosis data set <code>Liver_Steatosis.csv</code>. This dataset contains information on the 443 of 451 patients who had bariatric surgery at the Cleveland Clinic between 2005 and 2009 and underwent livery biopsy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a>liver <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Liver_Steatosis.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Question</a></li><li><a href="#tabset-5-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<p>Suppose we want to investigate whether we can use an individual’s weight in kg (variable weight) to estimate their LDL levels (variable LDL).</p>
<ul>
<li>Estimate the best fit line using regression methods.</li>
<li>Test for an association between weight and LDL values.</li>
<li>Predict the LDL value for an individual weighing 120 kg. Provide a 95% prediction interval.</li>
<li>Provide the value of <span class="math inline">\(R^2\)</span>.</li>
<li>Create a scatter plot with the regression line overlayed using <code>ggplot</code>.</li>
</ul>
</div>
<div id="tabset-5-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>liver,<span class="fu">aes</span>(<span class="at">x=</span>Weight,<span class="at">y=</span>LDL))<span class="sc">+</span></span>
<span id="cb17-2"><a></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb17-3"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">formula=</span>y<span class="sc">~</span>x,<span class="at">se=</span>F) <span class="sc">+</span> </span>
<span id="cb17-4"><a></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-8-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p>There appears to be a weak association between LDL and weight.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LDL<span class="sc">~</span>Weight,<span class="at">data=</span>liver)</span>
<span id="cb18-2"><a></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LDL ~ Weight, data = liver)

Residuals:
    Min      1Q  Median      3Q     Max 
-94.282 -22.991  -0.458  19.363 138.310 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 108.89842    7.68701  14.167   &lt;2e-16 ***
Weight       -0.02319    0.05618  -0.413     0.68    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 33 on 393 degrees of freedom
  (48 observations deleted due to missingness)
Multiple R-squared:  0.0004335, Adjusted R-squared:  -0.00211 
F-statistic: 0.1704 on 1 and 393 DF,  p-value: 0.68</code></pre>
</div>
</div>
<p>The best fit line is <span class="math inline">\(\hat{LDL} = 108.90 - 0.02*Weight\)</span>. The p-value of the coefficient is 0.68, and the test statistic <span class="math inline">\(t\)</span> is -0.41. There is no evidence of an association between weight and LDL levels. The <span class="math inline">\(R^2\)</span> value is 4^{-4}. Note that <strong>there are 48 observations deleted due to missingness</strong>. These variables were excluded from the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Weight=</span><span class="fu">c</span>(<span class="dv">120</span>))</span>
<span id="cb20-2"><a></a>newdata<span class="sc">$</span>prediction <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1,<span class="at">newdata=</span>newdata,<span class="at">interval =</span> <span class="st">"prediction"</span>,<span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb20-3"><a></a>newdata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Weight prediction.fit prediction.lwr prediction.upr
1    120      106.11543       41.13065      171.10020</code></pre>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="multiple-linear-regression" class="title-slide slide level1 center">
<h1>Multiple Linear Regression</h1>

</section>
<section id="multiple-linear-regression-1" class="slide level2">
<h2>Multiple Linear Regression</h2>
<p>Often, we want to consider the effect of multiple predictors on the dependent variable. The simple linear regression can be extended to any number of predictor variables. We define <span class="math inline">\(X_{ij}\)</span> as the value of predictor <span class="math inline">\(j\)</span> on unit <span class="math inline">\(i\)</span>.</p>
<p>The multiple linear regression model extended to <span class="math inline">\(p\)</span> predictors is then:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1X_{1i} + \beta_2X_{2i} + ... + \beta_pX_{ip} + \varepsilon_i
\]</span></p>
<p>The estimated best fit line can be written as:</p>
<p><span class="math display">\[
\hat{Y}_i = \hat{\beta}_0 + \hat{\beta}_1X_{1i} + \hat{\beta}_2X_{2i} + ... + \hat{\beta}_pX_{ip}
\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The slope estimate <span class="math inline">\(\hat{\beta}_k\)</span> is the expected change in the dependent variable for a 1-unit increase in <span class="math inline">\(X_ki\)</span> assuming all other variables remain constant. Generally, for a <span class="math inline">\(d\)</span> unit increase in <span class="math inline">\(X_ki\)</span>, the dependent variable is expected to change by <span class="math inline">\(d\hat{\beta}_1\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-tests-significance-of-regression" class="slide level2">
<h2>Hypothesis Tests: Significance of Regression</h2>
<p>The testing of significance of regression involves the null hypothesis <span class="math inline">\(H_0: \beta_1=\beta_2=...=\beta_p=0\)</span>, assuming that there is a total of <span class="math inline">\(p\)</span> predictors. The alternative hypothesis that at least one coefficient is non-zero. The test of significance of regression is used to test if there are any predictors with a non-zero coefficient. This test uses the F-statistic similar to what was discussed for simple linear regression.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><code>R</code> provides this information in the <code>summary()</code> output of <code>lm()</code> with the F-statistic and the corresponding p-value. The corresponding degrees of freedom are (p,N-p-1).</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-tests-individual-coefficients" class="slide level2">
<h2>Hypothesis Tests: Individual Coefficients</h2>
<p>When the null hypothesis of the significance of regression is rejected, we can perform hypothesis tests for each coefficient estimated.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><code>R</code> provides this information in the <code>summary()</code> output of <code>lm()</code> with the t-statistic and the corresponding p-value.</p>
</div>
</div>
</div>
</section>
<section id="discrete-variables-as-predictors" class="slide level2">
<h2>Discrete Variables as Predictors</h2>
<p>It is possible that we have a categorical independent variable that we want to consider for the regression model.</p>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Dichotomous Variables</a></li><li><a href="#tabset-6-2">Multi-level</a></li><li><a href="#tabset-6-3"><code>R</code> Implementation</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p>For a <em>dichotomous</em> variable, we can introduce a variable such that a “Yes” condition is assigned to <code>1</code> and <code>0</code> otherwise.</p>
</div>
<div id="tabset-6-2">
<p>For a categorical predictor variable with <span class="math inline">\(k\)</span> levels, we can introduce a <span class="math inline">\(k-1\)</span> <strong>dichotomous dummy variables</strong> to describe each level of the categorical predictor variable.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>For example, blood type (A, B, AB, O) has four levels. This means we need three dummy variables <span class="math inline">\((X_1,X_2,X_3)\)</span> to account for blood type. We define these dummy variables as:</p>
<p><span class="math display">\[
X_1 =
\begin{cases}
1, BloodType=A\\
0, otherwise
\end{cases}
\]</span></p>
<p><span class="math display">\[
X_2 =
\begin{cases}
1, BloodType=B\\
0, otherwise
\end{cases}
\]</span></p>
<p><span class="math display">\[
X_3 =
\begin{cases}
1, BloodType=AB\\
0, otherwise
\end{cases}
\]</span></p>
<p>For an individual with blood type <span class="math inline">\(A\)</span>, the dummy variable values are <span class="math inline">\((X_1,X_2,X_3)=(1,0,0)\)</span>. Similarly, <span class="math inline">\(B\)</span> corresponds to <span class="math inline">\((X_1,X_2,X_3)=(0,1,0)\)</span>. For blood type O, <span class="math inline">\((X_1,X_2,X_3)=(0,0,0)\)</span>.</p>
</div>
</div>
</div>
</div>
<div id="tabset-6-3">
<p><code>lm()</code> creates dummy variables for character/factor variables. If the variable as a numeric variable, we need to use <code>as.factor()</code> for <code>R</code> to recognize its categorical nature.</p>
</div>
</div>
</div>
</section>
<section id="adjusted-r2" class="slide level2">
<h2>Adjusted <span class="math inline">\(R^2\)</span></h2>
<p>When we add more predictor variables to a model, the <span class="math inline">\(R^2\)</span> can only go up or stay the same. It is tempting to add more predictor variables to increase <span class="math inline">\(R^2\)</span> even if these variables have little to no effect.</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The adjusted <span class="math inline">\(R^2\)</span> value, also known as <span class="math inline">\(R_{adj}^2\)</span>, is used to penalize models with more parameters. One form of the adjusted <span class="math inline">\(R^2\)</span> is given by:</p>
<p><span class="math display">\[
R_{adj}^2 = 1-\frac{(N-1)}{(N-p-1)}(1-R^2)
\]</span></p>
<p>where <span class="math inline">\(N\)</span> is the total number of samples. This is also provided in the <code>summary()</code> output of <code>lm()</code>.</p>
</div>
</div>
</div>
</section>
<section id="model-checking" class="slide level2">
<h2>Model Checking</h2>
<p>Recall: The residual is defined as the difference between the observed and predicted responses, specifically <span class="math inline">\(r_i = y_i-\hat{y}_i\)</span>. The residuals can be used to test the normality, equal variance, and independence assumptions. What is of interest to us are the <strong>residual plots</strong>.</p>
<p>The following tabs explain the plots shown when plotting an <code>lm()</code> object using <code>plot()</code>.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>x1<span class="sc">+</span>x2,<span class="at">data=</span>df)</span>
<span id="cb22-2"><a></a><span class="fu">plot</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Residual v. Fitted</a></li><li><a href="#tabset-7-2">Q-Q Residuals</a></li><li><a href="#tabset-7-3">Scale-Location</a></li><li><a href="#tabset-7-4">Residuals v. Leverage</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<p>This plot shows the fitted values of the predictor data to the residuals. If the results can be confined in a horizontal band, there are no obvious model defects.</p>
</div>
<div id="tabset-7-2">
<p>The normal probability plot of residuals, also known as the QQ plot, plots the theoretical quantiles of the normal distribution to the residuals. A good plot shows the points coinciding with the dashed line, defined as the expected behavior of the residuals if they follow a normal distribution.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Small deviations from this line is not a major source of concern. Visual inspection of the QQ plot is more recommended than formal statistical tests for normality, as these residuals are not independent. The non-independence of the residuals breaks the independence assumptions of most normality tests.</p>
</div>
</div>
</div>
</div>
<div id="tabset-7-3">
<p>The Scale-Location plot is a plot of the fitted values against the square root of the standardized residuals. Ideally, the red line should be generally horizontal with no upward trend, sharp angles, or slope.</p>
</div>
<div id="tabset-7-4">
<p>The residuals vs.&nbsp;leverage plot provides information on highly influential points in the model. Highly influential data points might lead to a skewed model. If the points are within the dashed lines, then there are no highly influential points in the model.</p>
</div>
</div>
</div>
</section>
<section id="example-3" class="slide level2">
<h2>Example</h2>
<p>Consider the sleep health data set in <code>SleepHealthData.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Question</a></li><li><a href="#tabset-8-2">Answer</a></li><li><a href="#tabset-8-3">Plots</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p>Suppose researchers are interested in estimating sleep duration based on heart rate, age, and gender.</p>
<ul>
<li>Estimate the best fit line using multiple regression</li>
<li>Comment on the results of the test of significance of regression. Is there evidence of non-zero coefficients?</li>
<li>Comment on the results of the hypothesis tests for each coefficient. Which predictors do we have evidence of an association with sleep duration?</li>
<li>Provide the <span class="math inline">\(R^2\)</span> and the adjusted <span class="math inline">\(R^2\)</span> for this model.</li>
<li>Comment on the plots used for model checking. Are there major model defects?</li>
</ul>
</div>
<div id="tabset-8-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(sleep_duration<span class="sc">~</span>gender <span class="sc">+</span> age <span class="sc">+</span> heart_rate,<span class="at">data=</span>sleep)</span>
<span id="cb24-2"><a></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sleep_duration ~ gender + age + heart_rate, data = sleep)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.0447 -0.6814  0.1215  0.5053  2.0566 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 12.084352   0.650015  18.591  &lt; 2e-16 ***
genderMale   0.304680   0.083770   3.637 0.000315 ***
age          0.032200   0.004845   6.646 1.08e-10 ***
heart_rate  -0.092133   0.008356 -11.027  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6465 on 370 degrees of freedom
Multiple R-squared:  0.345, Adjusted R-squared:  0.3397 
F-statistic: 64.96 on 3 and 370 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The best fit line to estimate sleep duration is <span class="math inline">\(\hat{y} = 12.08 +  0.305*X_{male} +0.03*Age - 0.09*HeartRate\)</span>, where <span class="math inline">\(X_{male}=1\)</span> if the individual is male and 0 otherwise.</p>
<p>The overall test of significance of regression yielded an F-statistic of F(3,370) = 64.96 corresponding to a p-value &lt;2.2e-16, indicating there is sufficient evidence that there is at least one non-zero coefficient in the assumed model.</p>
<p>The individual hypothesis tests show that there is evidence of associations between sleep duration and gender (<span class="math inline">\(\beta\)</span> = 0.30, p=0.0003), age (<span class="math inline">\(\beta\)</span>=0.03, p=1.08e-10), and heart rate (<span class="math inline">\(\beta\)</span>=-0.09,p&lt;2.2e-16).</p>
<p>The corresponding <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> values are 0.345 and 0.3397.</p>
</div>
<div id="tabset-8-3">
<p>The plots show major defects on the normality assumption of the residuals, which we must keep in mind when we are interpreting our results. We can also see that the residuals vs.&nbsp;fitted values cannot be enclosed in two horizontal bands, implying evidence of unequal variances.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="fu">plot</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-13-1.png" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-13-2.png" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-13-3.png" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-13-4.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-1" class="slide level2">
<h2>Exercise</h2>
<p>Consider the liver steatosis data set <code>Liver_Steatosis.csv</code>. This dataset contains information on the 443 of 451 patients who had bariatric surgery at the Cleveland Clinic between 2005 and 2009 and underwent livery biopsy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a>liver <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Liver_Steatosis.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Question</a></li><li><a href="#tabset-9-2">Answer</a></li><li><a href="#tabset-9-3">Plots</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<p>Suppose researchers are interested in estimating a person’s total cholesterol levels (variable CHOL) based on their BMI (variable BMI), age (variable Age), history of metabolic syndrome (variable MET_Syndrome, equal to 1 means patient has history), and plasma triglycerides (variable TG).</p>
<ul>
<li>Estimate the best fit line using multiple regression.</li>
<li>Comment on the results of the test of significance of regression. Is there evidence of non-zero coefficients?</li>
<li>Comment on the results of the hypothesis tests for each coefficient. Which predictors do we have evidence of an association with total cholesterol levels?</li>
<li>Provide the <span class="math inline">\(R^2\)</span> and the adjusted <span class="math inline">\(R^2\)</span> for this model.</li>
<li>Comment on the plots used for model checking. Are there major model defects?</li>
</ul>
</div>
<div id="tabset-9-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(CHOL<span class="sc">~</span>BMI<span class="sc">+</span> Age <span class="sc">+</span> MET_Syndrome<span class="sc">+</span>TG,<span class="at">data=</span>liver)</span>
<span id="cb28-2"><a></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = CHOL ~ BMI + Age + MET_Syndrome + TG, data = liver)

Residuals:
     Min       1Q   Median       3Q      Max 
-142.490  -25.349   -1.504   22.242  134.882 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  152.18618   12.46599  12.208   &lt;2e-16 ***
BMI            0.09060    0.17538   0.517   0.6057    
Age            0.19541    0.17158   1.139   0.2554    
MET_Syndrome  -9.98380    4.36471  -2.287   0.0227 *  
TG             0.15812    0.01478  10.699   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 37.59 on 406 degrees of freedom
  (32 observations deleted due to missingness)
Multiple R-squared:  0.2233,    Adjusted R-squared:  0.2157 
F-statistic: 29.19 on 4 and 406 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The best fit line to estimate total cholesterol levels is <span class="math inline">\(\hat{y} = 152.19 +  0.091*BMI + 0.195*Age -9.98*X_{MetSyndrome} + 0.158*TG\)</span>. where <span class="math inline">\(X_{MetSyndrome}=1\)</span> when patient has history of metabolic syndrome.</p>
<p>The overall test of significance of regression yielded an F-statistic of F(4,406) = 29.19 corresponding to a p-value &lt;2.2e-16, indicating there is sufficient evidence that there is at least one non-zero coefficient in the assumed model.</p>
<p>The individual hypothesis tests show that there is evidence of associations between total cholesterol and Metabolic Syndrome history (<span class="math inline">\(\beta\)</span> = -9.98, p=0.0003) and triglycerides (<span class="math inline">\(\beta\)</span>=0.158,p&lt;2.2e-16). There is no evidence of association between total cholesterol and BMI (<span class="math inline">\(\beta\)</span> = 0.09, p=0.61) and Age (<span class="math inline">\(\beta\)</span> = 0.195, p=0.25).</p>
<p>The corresponding <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> values are 0.2233 and 0.2157.</p>
</div>
<div id="tabset-9-3">
<p>A sharp curve in the residuals vs.&nbsp;fitted plot could be indicative of unequal variances. Normality assumption appears to hold well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="fu">plot</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-16-1.png" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-16-2.png" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-16-3.png" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture9_files/figure-revealjs/unnamed-chunk-16-4.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="correlation" class="title-slide slide level1 center">
<h1>Correlation</h1>

</section>
<section id="correlation-1" class="slide level2">
<h2>Correlation</h2>
<p>In regression analysis, we assumed that the predictor variables were constant and the only random variable was the response or outcome. Often, we encounter scenarios where both response and predictor variables are random. This is when we use a <em>correlation model</em>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>In the previous exercise, cholesterol and triglycerides can be treated as random if they are measured at the same time.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Although correlation analysis cannot be carried out meaningfully under the classic regression model, regression analysis can be carried out under the correlation model.</p>
</div>
</div>
</div>
</section>
<section id="correlation-coefficient" class="slide level2">
<h2>Correlation Coefficient</h2>
<p>The population correlation coefficient <span class="math inline">\(\rho\)</span> measures the strength of linear relationship between the predictor <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. On the other hand, The sample correlation coefficient, <span class="math inline">\(r\)</span>, describes the linear relationship between the sample observations on two variables in the same way that <span class="math inline">\(\rho\)</span> describes the relationship in a population.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(\rho\)</span> and <span class="math inline">\(r\)</span> can take on values between -1 and 1. Negative values of the correlation coefficient indicate a negative/inverse association, while positive values of the correlation coefficient indicate a positive/direct association.</p>
<p>A value of the correlation coefficient equal to 1 indicates perfect positive linear association, i.e.&nbsp;all data points fit in a line with a positive slope.</p>
<p>A value of the correlation coefficient equal to -1 indicates perfect negative linear association, i.e.&nbsp;all data points fit in a line with a negative slope.</p>
<p>A value of the correlation coefficient equal to 0 indicates no association.</p>
</div>
</div>
</div>
</section>
<section id="types-of-correlation-coefficients" class="slide level2">
<h2>Types of Correlation Coefficients</h2>
<p>There are two main types of correlation coefficients: Pearson and Spearman correlation coefficients.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Pearson correlation coefficients measures the strength of <strong>linear relationship</strong>. This is typically used in most studies.</p>
<p>Spearman correlation coefficients measures the strength of monotonic relationship using non-parametric methods. It is used to measure association that might not be linear, or in the presence of outliers.</p>
</div>
</div>
</div>
<p>We will focus on Pearson correlation coefficients in this chapter.</p>
</section>
<section id="a-stern-warning" class="slide level2">
<h2>A Stern Warning</h2>
<p>Always remember: <strong>CORRELATION DOES NOT MEAN CAUSATION</strong>. No matter how high the correlation coefficient values are, this is not evidence that <span class="math inline">\(X\)</span> causes <span class="math inline">\(Y\)</span> or vice versa.</p>
<p>Examples of spurious correlation can be found <a href="https://www.tylervigen.com/spurious-correlations">here</a></p>
</section>
<section id="hypothesis-test-correlation-coefficient-rho" class="slide level2">
<h2>Hypothesis Test: Correlation Coefficient <span class="math inline">\(\rho\)</span></h2>
<p>We can perform a test on the correlation coefficient <span class="math inline">\(\rho\)</span> to determine if we have evidence of linear association between the two variables. We use the null hypothesis of no association <span class="math inline">\(H_0: \rho=0\)</span>. The alternative hypotheses can be one-sided (<span class="math inline">\(\rho &lt; 0\)</span> or <span class="math inline">\(\rho &gt; 0\)</span>), or two-sided (<span class="math inline">\(\rho \neq 0\)</span>).</p>
<p>The test statistic can be calculated from the sample correlation coefficient <span class="math inline">\(r\)</span>.</p>
<p><span class="math display">\[
t = r \sqrt{\frac{(n-2)}{(1-r^2)}}
\]</span></p>
<p>This test statistic follows a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom, where <span class="math inline">\(n\)</span> is the total sample size.</p>
</section>
<section id="r-implementation-1" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The function <code>cor.test(x,y)</code> can be used to estimate the sample correlation coefficient <span class="math inline">\(r\)</span>, as well as perform the hypothesis test of no association and estimate confidence interval for <span class="math inline">\(\rho\)</span>.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a><span class="fu">cor.test</span>(df<span class="sc">$</span>x,df<span class="sc">$</span>y,<span class="at">conf.level=</span><span class="fl">0.95</span>)</span>
<span id="cb31-2"><a></a></span>
<span id="cb31-3"><a></a><span class="co"># OR</span></span>
<span id="cb31-4"><a></a></span>
<span id="cb31-5"><a></a><span class="fu">cor.test</span>(<span class="sc">~</span>x<span class="sc">+</span>y, <span class="at">data=</span>df,<span class="at">conf.level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Note that the formula is slightly different from <code>lm()</code> and <code>aov()</code>.</p>
</div>
</div>
</div>
</section>
<section id="example-4" class="slide level2">
<h2>Example</h2>
<p>Consider the sleep health data <code>SleepHealthData.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Question</a></li><li><a href="#tabset-10-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<p>Test for an association between stress level and sleep duration using correlation analysis.</p>
</div>
<div id="tabset-10-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a>cortest <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(sleep<span class="sc">$</span>sleep_duration,sleep<span class="sc">$</span>stress_level,<span class="at">conf.level=</span><span class="fl">0.95</span>)</span>
<span id="cb33-2"><a></a></span>
<span id="cb33-3"><a></a>cortest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  sleep$sleep_duration and sleep$stress_level
t = -26.739, df = 372, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.8430912 -0.7732074
sample estimates:
      cor 
-0.811023 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a><span class="fu">cor.test</span>(<span class="sc">~</span>sleep_duration<span class="sc">+</span>stress_level,<span class="at">data=</span>sleep,<span class="at">conf.level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  sleep_duration and stress_level
t = -26.739, df = 372, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.8430912 -0.7732074
sample estimates:
      cor 
-0.811023 </code></pre>
</div>
</div>
<p>The estimated correlation coefficient between sleep duration and stress level is -0.811 with a 95% confidence interval of -0.843, -0.773.</p>
<p>The hypothesis test shows that the test statistic is -26.739 with 372 degrees of freedom. This corresponds to a p-value &lt;2.2e-16, indicating we have sufficient evidence of a correlation between sleep duration and stress level.</p>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="slide level2">
<h2>Exercise</h2>
<p>Consider the liver steatosis data set <code>Liver_Steatosis.csv</code>. This dataset contains information on the 443 of 451 patients who had bariatric surgery at the Cleveland Clinic between 2005 and 2009 and underwent livery biopsy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a>liver <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Liver_Steatosis.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">Question</a></li><li><a href="#tabset-11-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<p>Test for an association between BMI (variable BMI) and cholesterol (variable CHOL) using correlation analysis.</p>
</div>
<div id="tabset-11-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a>cortest <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(liver<span class="sc">$</span>BMI,liver<span class="sc">$</span>CHOL,<span class="at">conf.level=</span><span class="fl">0.95</span>)</span>
<span id="cb38-2"><a></a></span>
<span id="cb38-3"><a></a>cortest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  liver$BMI and liver$CHOL
t = -0.13162, df = 409, p-value = 0.8954
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.10317221  0.09027825
sample estimates:
        cor 
-0.00650787 </code></pre>
</div>
</div>
<p>The estimated correlation coefficient between BMI and cholesterol is -0.007 with a 95% confidence interval of -0.103, 0.09.</p>
<p>The hypothesis test shows that the test statistic is -0.132 with 409 degrees of freedom. This corresponds to a p-value of 0.8953525, indicating we have insufficient evidence of a correlation between BMI and cholesterol.</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Lecture 9 - <a href="https://madfudolig.quarto.pub/introtobiostats/">Back to home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/madfudolig\.quarto\.pub\/introtobiostats");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
            for (let i=0; i<annoteTargets.length; i++) {
              const annoteTarget = annoteTargets[i];
              const targetCell = annoteTarget.getAttribute("data-target-cell");
              const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
              const contentFn = () => {
                const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
                if (content) {
                  const tipContent = content.cloneNode(true);
                  tipContent.classList.add("code-annotation-tip-content");
                  return tipContent.outerHTML;
                }
              }
              const config = {
                allowHTML: true,
                content: contentFn,
                onShow: (instance) => {
                  selectCodeLines(instance.reference);
                  instance.reference.classList.add('code-annotation-active');
                  window.tippy.hideAll();
                },
                onHide: (instance) => {
                  unselectCodeLines();
                  instance.reference.classList.remove('code-annotation-active');
                },
                maxWidth: 300,
                delay: [50, 0],
                duration: [200, 0],
                offset: [5, 10],
                arrow: true,
                appendTo: function(el) {
                  return el.parentElement.parentElement.parentElement;
                },
                interactive: true,
                interactiveBorder: 10,
                theme: 'light-border',
                placement: 'right',
                popperOptions: {
                  modifiers: [
                  {
                    name: 'flip',
                    options: {
                      flipVariations: false, // true by default
                      allowedAutoPlacements: ['right'],
                      fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                    },
                  },
                  {
                    name: 'preventOverflow',
                    options: {
                      mainAxis: false,
                      altAxis: false
                    }
                  }
                  ]        
                }      
              };
              window.tippy(annoteTarget, config); 
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>