<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>EAB 703-1002: Biostatistical Methods for the Health Sciences – Selected Nonparametric Methods</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-12873a65cf666e61daa4b3cf91a98e13.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Selected Nonparametric Methods</h1>
  <p class="subtitle">Lecture 11</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="outline" class="title-slide slide level1 center">
<h1>Outline</h1>
<ul>
<li>Nonparametric Statistics</li>
<li>Test for Normality</li>
<li>One-Sample Wilcoxon Test</li>
<li>Paired-Sample Test</li>
<li>Two-Sample Test</li>
<li>Kruskal-Wallis Test</li>
<li>Spearman Correlation</li>
</ul>
</section>

<section>
<section id="nonparametric-statistics" class="title-slide slide level1 center">
<h1>Nonparametric Statistics</h1>

</section>
<section id="what-is-non-parametric-statistics" class="slide level2">
<h2>What is Non-Parametric Statistics?</h2>
<p>Most of the inferential statistical procedures we have discussed so far can be classified as <em>parametric methods</em>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Parametric methods are based on statistical parameters like the mean, proportion, or variance.</p>
<p>An examle of a test that did not use any statistical parameter assumption are the chi-square tests.</p>
</div>
</div>
</div>
</section>
<section id="nonparametric-tests" class="slide level2">
<h2>Nonparametric Tests</h2>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Advantages</a></li><li><a href="#tabset-1-2">Disadvantages</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Unknown form of sampled population</strong></p>
</div>
<div class="callout-content">
<p>Nonparametric tests allow us to develop tests that do not involve parameters. Hence, they may be used when the form of the sampled population is unknown.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Small Sample Size</strong></p>
</div>
<div class="callout-content">
<p>Nonparametric tests can be applied to small data sets and are generally easy to do computationally.</p>
</div>
</div>
</div>
</div>
<div id="tabset-1-2">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Lower power</strong></p>
</div>
<div class="callout-content">
<p>Nonparametric tests may have less power compared to some parametric tests.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Economics of Scale</strong></p>
</div>
<div class="callout-content">
<p>Nonparametric tests may be tedious to apply to large data sets.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Ties</strong></p>
</div>
<div class="callout-content">
<p>For rank-based tests, some methods assume that there are no “ties” in ranking, hence adjustments need to be performed if ties are present.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="tests-for-normality" class="title-slide slide level1 center">
<h1>Tests for Normality</h1>

</section>
<section id="formal-tests-for-normality" class="slide level2">
<h2>Formal Tests for Normality</h2>
<p>There are nonparametric tests that can be used to test if a variable measured in a data set follow a Gaussian distribution.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The Shapiro-Wilks test is a common test for normality.</p>
<p>The Kolgomorov-Smirnov (K-S),Anderson-Darling and Lilliefors tests are also used.</p>
</div>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Notes about K-S</a></li><li><a href="#tabset-2-2">Lilliefors Test</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p>The K-S test can be used for any given reference probability distribution or to compare if two samples came from the same distribution.</p>
</div>
<div id="tabset-2-2">
<p>The Lilliefors test is an improvement on the K-S test for the normality assumption.</p>
</div>
</div>
</div>
</section>
<section id="statistical-hypotheses" class="slide level2">
<h2>Statistical Hypotheses</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>For all these tests, the null hypothesis is that the data follow the normal distribution. The alternative hypothesis is that the data does not follow the normal distribution.</p>
<p>Rejecting the null hypothesis means we have sufficient evidence of a deviation from the normal distribution.</p>
</div>
</div>
</div>
</section>
<section id="r-implementation" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The Kolgomorov-Smirnov test can be implemented using the <code>ks.test()</code> function in <code>R</code>.</p>
</section></section>
<section>
<section id="one-sample-tests" class="title-slide slide level1 center">
<h1>One-Sample tests</h1>

</section>
<section id="wilcoxon-signed-rank-test-for-location" class="slide level2">
<h2>Wilcoxon Signed-Rank Test for Location</h2>
<p>The Wilcoxon Signed-Rank Test for Location is used when we want to test a mean, but neither <span class="math inline">\(z\)</span> or <span class="math inline">\(t\)</span> are appropriate.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions</strong></p>
</div>
<div class="callout-content">
<p>The Wilcoxon test assumes the following about the data:</p>
<ul>
<li>The sample is random</li>
<li>The random variable is continuous</li>
<li>The population is symmetric about its mean.</li>
<li>The measurement scale is at least interval.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="statistical-hypotheses-1" class="slide level2">
<h2>Statistical Hypotheses</h2>
<p>Unlike the one-sample t-test or z-test that hypothesize about the mean, the hypothesis of the one-sample Wilcoxon test involves the median (assuming the symmetry assumption holds).</p>
<p>The null hypothesis is that the median of the data set, <span class="math inline">\(\tilde{\mu}\)</span> is equal to a null value <span class="math inline">\(\tilde{\mu}_0\)</span>.</p>
<p><span class="math display">\[
H_0: \tilde{\mu}=\tilde{\mu}_0
\]</span></p>
<p>The alternative can be one-sided (<span class="math inline">\(\tilde{\mu}&gt; \tilde{\mu}_0\)</span> or <span class="math inline">\(\tilde{\mu}&lt; \tilde{\mu}_0\)</span>) or two-sided (<span class="math inline">\(\tilde{\mu}\neq \tilde{\mu}_0\)</span>).</p>
</section>
<section id="how-it-works" class="slide level2">
<h2>How it Works</h2>
<ul>
<li>The difference between the data points and the null value are calculated</li>
<li>These differences are then ranked from highest to lowest. If the difference is zero, it is ignored.</li>
<li>Reapply the original signs to these ranks</li>
<li>Sum the positive and negative ranks to obtain the test statistic.</li>
<li>The test statistic is the lower value between the absolute value of the sums of the positive and negative ranks.</li>
</ul>
</section>
<section id="r-implementation-1" class="slide level2">
<h2><code>R</code> Implementation</h2>
<p>The <code>wilcox.test()</code> function can be used to perform a one-sample Wilcoxon-test in <code>R</code>. For a vector x in a data frame <code>df</code> and a null value <code>m0</code>, an example code of a two-sided test can be written as</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">wilcox.test</span>(df<span class="sc">$</span>x,<span class="at">mu=</span>mu0,<span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>
<p>Consider the sleep health data set in <code>SleepHealthData.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span>
<span id="cb2-3"><a></a><span class="fu">glimpse</span>(sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 374
Columns: 13
$ person_id               &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…
$ gender                  &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male"…
$ age                     &lt;int&gt; 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29…
$ occupation              &lt;chr&gt; "Software Engineer", "Doctor", "Doctor", "Sale…
$ sleep_duration          &lt;dbl&gt; 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7…
$ quality_of_sleep        &lt;int&gt; 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6…
$ physical_activity_level &lt;int&gt; 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75…
$ stress_level            &lt;int&gt; 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8…
$ bmi_category            &lt;chr&gt; "Overweight", "Normal", "Normal", "Obese", "Ob…
$ blood_pressure          &lt;chr&gt; "126/83", "125/80", "125/80", "140/90", "140/9…
$ heart_rate              &lt;int&gt; 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70…
$ daily_steps             &lt;int&gt; 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80…
$ sleep_disorder          &lt;chr&gt; "None", "None", "None", "Sleep Apnea", "Sleep …</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Question</a></li><li><a href="#tabset-3-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p>Use the one-sample Wilcoxon test to test whether the median stress level for the sampled population is higher than 4.5.</p>
</div>
<div id="tabset-3-2">
<p>The statistical hypothesis can be written as:</p>
<p><span class="math display">\[
H_0: \tilde{\mu}=4.5; H_a: \tilde{\mu}&gt; 4.5
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>wtest <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(sleep<span class="sc">$</span>stress_level,<span class="at">mu=</span><span class="fl">4.5</span>,<span class="at">alternative =</span> <span class="st">"greater"</span>)</span>
<span id="cb4-2"><a></a>wtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  sleep$stress_level
V = 51379, p-value = 1.556e-15
alternative hypothesis: true location is greater than 4.5</code></pre>
</div>
</div>
<p>The p-value is 1.5555249^{-15}, which is less than 0.05. We reject the null hypothesis. We have sufficient evidence that the median stress level of the sampled population is greater than 4.5.</p>
<p>We can also visually check if this makes sense using a box plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>sleep,<span class="fu">aes</span>(<span class="at">x=</span><span class="cn">NULL</span>,<span class="at">y=</span>stress_level)) <span class="sc">+</span> </span>
<span id="cb6-2"><a></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb6-3"><a></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept=</span><span class="fl">4.5</span>),<span class="at">color=</span><span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb6-4"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb6-5"><a></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Stress Level"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture11_files/figure-revealjs/unnamed-chunk-3-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="notes" class="slide level2">
<h2>Notes</h2>
<p>If the assumption about the symmetry of the data set is not satisfied, the Wilcoxon test might have faulty results about the inference involving medians.</p>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Warning</a></li><li><a href="#tabset-4-2">Sign test</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Note that the test statistic is based on the ranked differences and that zero differences are ignored. This means that if the data is asymmetric and the assumed median is part of the data set, it might lead to a significant result even if the medians are the same.</p>
<p>If we are interested in a pure test of medians for a skewed sample, the <strong>sign test</strong> might be a better alternative.</p>
</div>
</div>
</div>
</div>
<div id="tabset-4-2">
<p>The <code>BSDA</code> package includes the <code>SIGN.test()</code> function that can be used to run the sign test.</p>
</div>
</div>
</div>
</section>
<section id="exercise" class="slide level2">
<h2>Exercise</h2>
<p>Consider the sleep health data set in <code>SleepHealthData.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb7-2"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span>
<span id="cb7-3"><a></a><span class="fu">glimpse</span>(sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 374
Columns: 13
$ person_id               &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…
$ gender                  &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male"…
$ age                     &lt;int&gt; 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29…
$ occupation              &lt;chr&gt; "Software Engineer", "Doctor", "Doctor", "Sale…
$ sleep_duration          &lt;dbl&gt; 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7…
$ quality_of_sleep        &lt;int&gt; 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6…
$ physical_activity_level &lt;int&gt; 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75…
$ stress_level            &lt;int&gt; 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8…
$ bmi_category            &lt;chr&gt; "Overweight", "Normal", "Normal", "Obese", "Ob…
$ blood_pressure          &lt;chr&gt; "126/83", "125/80", "125/80", "140/90", "140/9…
$ heart_rate              &lt;int&gt; 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70…
$ daily_steps             &lt;int&gt; 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80…
$ sleep_disorder          &lt;chr&gt; "None", "None", "None", "Sleep Apnea", "Sleep …</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Question</a></li><li><a href="#tabset-5-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<p>Use the one-sample Wilcoxon test to test whether the median physical activity level for the sampled population is not equal to 60.</p>
</div>
<div id="tabset-5-2">
<p>The statistical hypothesis can be written as:</p>
<p><span class="math display">\[
H_0: \tilde{\mu}=60; H_a: \tilde{\mu}\neq 60
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a>wtest <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(sleep<span class="sc">$</span>physical_activity_level,<span class="at">mu=</span><span class="dv">60</span>,<span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span>
<span id="cb9-2"><a></a>wtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  sleep$physical_activity_level
V = 22196, p-value = 0.5121
alternative hypothesis: true location is not equal to 60</code></pre>
</div>
</div>
<p>We can also visually check if this makes sense using a box plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>sleep,<span class="fu">aes</span>(<span class="at">x=</span><span class="cn">NULL</span>,<span class="at">y=</span>physical_activity_level)) <span class="sc">+</span> </span>
<span id="cb11-2"><a></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb11-3"><a></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept=</span><span class="dv">60</span>),<span class="at">color=</span><span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb11-4"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb11-5"><a></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Physical Activity Level"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture11_files/figure-revealjs/unnamed-chunk-6-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="paired-samples-test" class="title-slide slide level1 center">
<h1>Paired-Samples Test</h1>

</section>
<section id="paired-samples-test-1" class="slide level2">
<h2>Paired-Samples Test</h2>
<p>the Wilcoxon signed-rank test can be used to test for a difference between paired samples.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>This is the non-parametric equivalent of a paired t-test.</p>
</div>
</div>
</div>
</section>
<section id="statistical-hypotheses-2" class="slide level2">
<h2>Statistical Hypotheses</h2>
<p>The hypothesis of the paired-sample Wilcoxon signed rank test involves the median of the paired difference.</p>
<p>The null hypothesis is that the median of the data set, <span class="math inline">\(\tilde{\mu}_d\)</span> is equal to a null value <span class="math inline">\(\tilde{\mu}_{d,0}\)</span>.</p>
<p><span class="math display">\[
H_0: \tilde{\mu}_d=\tilde{\mu}_{d,0}
\]</span></p>
<p>The alternative can be one-sided (<span class="math inline">\(\tilde{\mu}_d&gt;\tilde{\mu}_{d,0}\)</span> or <span class="math inline">\(\tilde{\mu}_d&lt;\tilde{\mu}_{d,0}\)</span>) or two-sided (<span class="math inline">\(\tilde{\mu}_d\neq\tilde{\mu}_{d,0}\)</span>).</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The null value commonly used is 0 (null hypothesis of equality).</p>
</div>
</div>
</div>
</section>
<section id="r-implementation-2" class="slide level2">
<h2><code>R</code> Implementation</h2>
<p>The <code>wilcox.test()</code> can also be used for paired data. For a data frame <code>df</code> with paired data <code>x1</code> and <code>x2</code> and a one-sided “less” alternative hypothesis , the sample code would look like:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">wilcox.test</span>(<span class="at">x=</span>df<span class="sc">$</span>x1,<span class="at">y=</span>df<span class="sc">$</span>x2,<span class="at">paired=</span>T,<span class="at">alternative=</span><span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<p>The following data set <code>example</code> shows data from research that investigated the possible beneficial effects of singing on wellbeing during a single singing lesson. One of the variables of interest was the change in cortisol as a result of the singing lesson.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>example <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb13-2"><a></a>  <span class="at">before=</span><span class="fu">c</span>(<span class="dv">214</span>,<span class="dv">362</span>,<span class="dv">202</span>,<span class="dv">158</span>,<span class="dv">403</span>,<span class="dv">219</span>,<span class="dv">307</span>,<span class="dv">331</span>),</span>
<span id="cb13-3"><a></a>  <span class="at">after=</span><span class="fu">c</span>(<span class="dv">232</span>,<span class="dv">276</span>,<span class="dv">224</span>,<span class="dv">412</span>,<span class="dv">562</span>,<span class="dv">203</span>,<span class="dv">340</span>,<span class="dv">313</span>)</span>
<span id="cb13-4"><a></a>)</span>
<span id="cb13-5"><a></a><span class="fu">glimpse</span>(example)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 8
Columns: 2
$ before &lt;dbl&gt; 214, 362, 202, 158, 403, 219, 307, 331
$ after  &lt;dbl&gt; 232, 276, 224, 412, 562, 203, 340, 313</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Question</a></li><li><a href="#tabset-6-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p>Use the Wilcoxon Signed-Rank Test to test whether the cortisol levels increased after singing.</p>
</div>
<div id="tabset-6-2">
<p>The alternative hypothesis is one-sided because of the direction assumed in the problem. We assume that <span class="math inline">\(\tilde{\mu}_d\)</span> is calculated as <code>before</code>-<code>after</code> Hence, the hypotheses can be written as:</p>
<p><span class="math display">\[
H_0: \tilde{\mu}_d=0;H_0: \tilde{\mu}_d&gt;0
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>wtest <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(<span class="at">x=</span>example<span class="sc">$</span>before,<span class="at">y=</span>example<span class="sc">$</span>after,<span class="at">paired=</span>T,<span class="at">alternative=</span><span class="st">"less"</span>,<span class="at">correct=</span><span class="cn">TRUE</span>)</span>
<span id="cb15-2"><a></a>wtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  example$before and example$after
V = 9.5, p-value = 0.131
alternative hypothesis: true location shift is less than 0</code></pre>
</div>
</div>
<p>The resulting Wilcoxon test p-value is 0.1310164. We fail to reject the null hypothesis at the significance level of 0.05. We have insufficient evidence to claim that the cortisol levels increased after singing.</p>
</div>
</div>
</div>
</section>
<section id="exercise-1" class="slide level2">
<h2>Exercise</h2>
<p>The data set <code>anorexia</code> from the package <code>MASS</code> contains weight change data for young female anorexia patients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">library</span>(MASS)</span>
<span id="cb17-2"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb17-3"><a></a><span class="fu">glimpse</span>(anorexia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 72
Columns: 3
$ Treat  &lt;fct&gt; Cont, Cont, Cont, Cont, Cont, Cont, Cont, Cont, Cont, Cont, Con…
$ Prewt  &lt;dbl&gt; 80.7, 89.4, 91.8, 74.0, 78.1, 88.3, 87.3, 75.1, 80.6, 78.4, 77.…
$ Postwt &lt;dbl&gt; 80.2, 80.1, 86.4, 86.3, 76.1, 78.1, 75.1, 86.7, 73.5, 84.6, 77.…</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Question</a></li><li><a href="#tabset-7-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<p>Perform a paired-sample non-parametric test to test whether there is a difference between the preweight <code>prewt</code> and <code>postwt</code> for all patients, disregarding the type of treatment. Use a significance level of 0.05.</p>
</div>
<div id="tabset-7-2">
<p>The alternative hypothesis is two-sided. We assume that <span class="math inline">\(\tilde{\mu}_d\)</span> is calculated as <code>Postwt</code>-<code>Prewt</code> Hence, the hypotheses can be written as:</p>
<p><span class="math display">\[
H_0: \tilde{\mu}_d=0;H_0: \tilde{\mu}_d\neq 0
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>wtest <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(<span class="at">x=</span>anorexia<span class="sc">$</span>Postwt,<span class="at">y=</span>anorexia<span class="sc">$</span>Prewt,<span class="at">paired=</span>T,<span class="at">alternative=</span><span class="st">"two.sided"</span>)</span>
<span id="cb19-2"><a></a>wtest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  anorexia$Postwt and anorexia$Prewt
V = 1724.5, p-value = 0.0106
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>The p-value is 0.0106022. We reject the null hypothesis at the 0.05 level of significance. There is sufficient evidence to conclude that there is a difference in post-weight and pre-weight scores across the sample.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="two-sample-test" class="title-slide slide level1 center">
<h1>Two-Sample Test</h1>

</section>
<section id="mann-whitney-u-test" class="slide level2">
<h2>Mann-Whitney U Test</h2>
<p>The Mann-Whitney U Test is equivalent to the two-sample Wilcoxon test.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions</strong></p>
</div>
<div class="callout-content">
<p>The Mann-Whitney test assumes the following:</p>
<ul>
<li>The two samples are independent and randomly drawn from their respective populations</li>
<li>The measurement scale is at least ordinal</li>
<li>The variable of interest is continuous</li>
<li>If the populations differ at all, they differ only with respect to their medians.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="statistical-hypotheses-3" class="slide level2">
<h2>Statistical Hypotheses</h2>
<p>The null hypothesis for the Mann-Whitney U test is that there is no difference between the distribution of the two independent groups.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The distribution can be measured using the median or sometimes, the mean of the ranks.</p>
</div>
</div>
</div>
<p>The alternative hypotheses can be:</p>
<ul>
<li>One-sided: One group tends to have higher or lower values than the other</li>
<li>Two-sided: There is a difference between the distributions of the two groups.</li>
</ul>
</section>
<section id="the-u-statistic" class="slide level2">
<h2>The <span class="math inline">\(U\)</span> Statistic</h2>
<p>To calculate the test statistic:</p>
<ul>
<li>Assign ranks to the values from the two groups pooled together in order from smallest to largest.</li>
<li>Sum the ranks of each group.</li>
<li>Calculate the <span class="math inline">\(U_j\)</span> value as:</li>
</ul>
<p><span class="math display">\[
U_1 = n_1n_2 + n_1(n_1+1)/2 - \sum_iR_{i1}
\]</span></p>
<p><span class="math display">\[
U_2 = n_1n_2 + n_2(n_2+1)/2 - \sum_iR_{i2}
\]</span></p>
<ul>
<li>The test statistic is the lower value between <span class="math inline">\(U_1\)</span> and <span class="math inline">\(U_2\)</span>.</li>
</ul>
</section>
<section id="r-implementation-3" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The <code>wilcox.test()</code> function can implement the Mann-Whitney U test for independent groups. The syntax is similar to the paired-samples test but specifying that <code>paired=FALSE</code>.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a><span class="fu">wilcox.test</span>(<span class="at">x=</span>df<span class="sc">$</span>x1,<span class="at">y=</span>df<span class="sc">$</span>x2,<span class="at">alternative=</span><span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>If the grouping variable and the response variables are defined as two distinct columns, we can use the formula notation as well.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="fu">wilcox.test</span>(response<span class="sc">~</span>grouping,<span class="at">data=</span>df,<span class="at">alternative=</span><span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="example-2" class="slide level2">
<h2>Example</h2>
<p>Consider the data set <code>SleepHealthData.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span>
<span id="cb23-2"><a></a><span class="fu">glimpse</span>(sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 374
Columns: 13
$ person_id               &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…
$ gender                  &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male"…
$ age                     &lt;int&gt; 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29…
$ occupation              &lt;chr&gt; "Software Engineer", "Doctor", "Doctor", "Sale…
$ sleep_duration          &lt;dbl&gt; 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7…
$ quality_of_sleep        &lt;int&gt; 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6…
$ physical_activity_level &lt;int&gt; 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75…
$ stress_level            &lt;int&gt; 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8…
$ bmi_category            &lt;chr&gt; "Overweight", "Normal", "Normal", "Obese", "Ob…
$ blood_pressure          &lt;chr&gt; "126/83", "125/80", "125/80", "140/90", "140/9…
$ heart_rate              &lt;int&gt; 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70…
$ daily_steps             &lt;int&gt; 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80…
$ sleep_disorder          &lt;chr&gt; "None", "None", "None", "Sleep Apnea", "Sleep …</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Question</a></li><li><a href="#tabset-8-2">Answer</a></li><li><a href="#tabset-8-3">Violin Plot</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p>Use the Mann-Whitney U test to determine if there is a difference in quality of sleep between males and females.</p>
</div>
<div id="tabset-8-2">
<p>The alternative hypothesis should be two-sided because of the lack of directionality specified in the difference that we want to detect.</p>
<p>The null hypothesis is that there is no difference in quality of sleep between males and females, while the alternative hypothesis is that there is a difference in quality of sleep between males and females.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a>wtest<span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(quality_of_sleep<span class="sc">~</span>gender,<span class="at">data=</span>sleep,<span class="at">alternative=</span><span class="st">"two.sided"</span>)</span>
<span id="cb25-2"><a></a>wtest </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  quality_of_sleep by gender
W = 23369, p-value = 6.048e-09
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>The resulting p-value is 6.0476062^{-9}. We reject the null hypothesis. We have sufficient evidence to conclude that there is a difference in quality of sleep between males and females.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>sleep,<span class="fu">aes</span>(<span class="at">x=</span>gender,<span class="at">y=</span>quality_of_sleep))<span class="sc">+</span></span>
<span id="cb27-2"><a></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb27-3"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb27-4"><a></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Quality of Sleep"</span>,<span class="at">x=</span><span class="st">"Gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture11_files/figure-revealjs/unnamed-chunk-13-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-8-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>sleep,<span class="fu">aes</span>(<span class="at">x=</span>gender,<span class="at">y=</span>quality_of_sleep))<span class="sc">+</span></span>
<span id="cb28-2"><a></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span> </span>
<span id="cb28-3"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb28-4"><a></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Quality of Sleep"</span>,<span class="at">x=</span><span class="st">"Gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture11_files/figure-revealjs/unnamed-chunk-14-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="slide level2">
<h2>Exercise</h2>
<p>Consider the sleep health data set <code>SleepHealthData.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span>
<span id="cb29-2"><a></a><span class="fu">glimpse</span>(sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 374
Columns: 13
$ person_id               &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…
$ gender                  &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male"…
$ age                     &lt;int&gt; 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29…
$ occupation              &lt;chr&gt; "Software Engineer", "Doctor", "Doctor", "Sale…
$ sleep_duration          &lt;dbl&gt; 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7…
$ quality_of_sleep        &lt;int&gt; 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6…
$ physical_activity_level &lt;int&gt; 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75…
$ stress_level            &lt;int&gt; 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8…
$ bmi_category            &lt;chr&gt; "Overweight", "Normal", "Normal", "Obese", "Ob…
$ blood_pressure          &lt;chr&gt; "126/83", "125/80", "125/80", "140/90", "140/9…
$ heart_rate              &lt;int&gt; 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70…
$ daily_steps             &lt;int&gt; 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80…
$ sleep_disorder          &lt;chr&gt; "None", "None", "None", "Sleep Apnea", "Sleep …</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Question</a></li><li><a href="#tabset-9-2">Answer</a></li><li><a href="#tabset-9-3">Violin Plot</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<p>Use the Mann-Whitney U test to determine if there is a difference in daily steps between males and females.</p>
</div>
<div id="tabset-9-2">
<p>The alternative hypothesis should be two-sided because of the lack of directionality specified in the difference that we want to detect.</p>
<p>The null hypothesis is that there is no difference in daily number of steps between males and females, while the alternative hypothesis is that there is a difference in daily number of steps between males and females.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>wtest<span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(daily_steps<span class="sc">~</span>gender,<span class="at">data=</span>sleep,<span class="at">alternative=</span><span class="st">"two.sided"</span>)</span>
<span id="cb31-2"><a></a>wtest </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  daily_steps by gender
W = 15890, p-value = 0.1203
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>The resulting p-value is 0.1203365. We fail to reject the null hypothesis at the 0.05 level of significance. We have insufficient evidence to conclude that there is a difference in number of daily steps between males and females.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>sleep,<span class="fu">aes</span>(<span class="at">x=</span>gender,<span class="at">y=</span>daily_steps))<span class="sc">+</span></span>
<span id="cb33-2"><a></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb33-3"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb33-4"><a></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Number of Steps (Daily)"</span>,<span class="at">x=</span><span class="st">"Gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture11_files/figure-revealjs/unnamed-chunk-17-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-9-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>sleep,<span class="fu">aes</span>(<span class="at">x=</span>gender,<span class="at">y=</span>daily_steps))<span class="sc">+</span></span>
<span id="cb34-2"><a></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span> </span>
<span id="cb34-3"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb34-4"><a></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Number of Steps (Daily)"</span>,<span class="at">x=</span><span class="st">"Gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture11_files/figure-revealjs/unnamed-chunk-18-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="anova-like-tests" class="title-slide slide level1 center">
<h1>ANOVA-like Tests</h1>

</section>
<section id="anova-like-tests-1" class="slide level2">
<h2>ANOVA-like tests</h2>
<p>There are non-parametric tests that compare the distributions of more than two groups.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The Kruskal-Wallis Rank Sum test works similarly to the one-way ANOVA, while the Friedman’s test works similarly to the two-way ANOVA. Both use assumptions that are the same as the Mann-Whitney test for two independent samples.</p>
</div>
</div>
</div>
</section>
<section id="statistical-hypotheses-kruskal-wallis-test" class="slide level2">
<h2>Statistical Hypotheses: Kruskal-Wallis Test</h2>
<p>The null hypothesis of the Kruskal-Wallis Rank Sum Test states that there is no difference in the distribution of the response variable across the different groups.</p>
<p>The alternative hypothesis states that there is at least one group that has a different distribution of the response variable across the different groups.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>This can be stated in terms of medians, similar to how ANOVA was stated in terms of means.</p>
</div>
</div>
</div>
</section>
<section id="r-implementation-4" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The <code>kruskal.test()</code> function implements the Kruskal-Wallis test. The function works best with the formula notation.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a><span class="fu">kruskal.test</span>(response<span class="sc">~</span>group,<span class="at">data=</span>df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="example-3" class="slide level2">
<h2>Example</h2>
<p>Consider the <code>penguins</code> data set in <code>R</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb36-2"><a></a><span class="fu">glimpse</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 344
Columns: 8
$ species     &lt;fct&gt; Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Ad…
$ island      &lt;fct&gt; Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Tor…
$ bill_len    &lt;dbl&gt; 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, 42.0, …
$ bill_dep    &lt;dbl&gt; 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, 20.2, …
$ flipper_len &lt;int&gt; 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186, 180,…
$ body_mass   &lt;int&gt; 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, 4250, …
$ sex         &lt;fct&gt; male, female, female, NA, female, male, female, male, NA, …
$ year        &lt;int&gt; 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Question</a></li><li><a href="#tabset-10-2">Answer</a></li><li><a href="#tabset-10-3">Violin Plot</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<p>Use the Kruskal-Wallis test to test for a difference between the body mass across the different years (2007,2008,2009).</p>
</div>
<div id="tabset-10-2">
<p>The null hypothesis is that there is no difference in the distribution of body mass of the penguins across the different years. The alternative is that at least one year is different from the others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a>ktest <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(body_mass<span class="sc">~</span><span class="fu">as.factor</span>(year),<span class="at">data=</span>penguins)</span>
<span id="cb38-2"><a></a>ktest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  body_mass by as.factor(year)
Kruskal-Wallis chi-squared = 2.5523, df = 2, p-value = 0.2791</code></pre>
</div>
</div>
<p>The resulting p-value is 0.279111. At 0.05 level of significance, we fail to reject the null hypothesis. We have insufficient evidence that there is at least one year with a different distribution of body mass compared to the others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>penguins,<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">as.factor</span>(year),<span class="at">y=</span>body_mass)) <span class="sc">+</span> </span>
<span id="cb40-2"><a></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb40-3"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb40-4"><a></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Year"</span>,<span class="at">y=</span><span class="st">"Body Mass of Penguins"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture11_files/figure-revealjs/unnamed-chunk-21-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-10-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>penguins,<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">as.factor</span>(year),<span class="at">y=</span>body_mass)) <span class="sc">+</span> </span>
<span id="cb41-2"><a></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb41-3"><a></a>  <span class="fu">geom_violin</span>(<span class="fu">aes</span>(<span class="at">fill=</span><span class="fu">as.factor</span>(year)),<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb41-4"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb41-5"><a></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Year"</span>,<span class="at">y=</span><span class="st">"Body Mass of Penguins"</span>,<span class="at">fill=</span><span class="st">"Year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture11_files/figure-revealjs/unnamed-chunk-22-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-3" class="slide level2">
<h2>Exercise</h2>
<p>Consider the <code>iris</code> data set in <code>R</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a></a><span class="fu">glimpse</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 5
$ Sepal.Length &lt;dbl&gt; 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.…
$ Sepal.Width  &lt;dbl&gt; 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.…
$ Petal.Length &lt;dbl&gt; 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.…
$ Petal.Width  &lt;dbl&gt; 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.…
$ Species      &lt;fct&gt; setosa, setosa, setosa, setosa, setosa, setosa, setosa, s…</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">Question</a></li><li><a href="#tabset-11-2">Answer</a></li><li><a href="#tabset-11-3">Violin Plot</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<p>Use the Kruskal-Wallis test to test for a difference between the petal widths of the species of iris.</p>
</div>
<div id="tabset-11-2">
<p>The null hypothesis is that there is no difference in petal widths of the species of iris. the alternative hypothesis is that there is at least one species that has a different distribution of petal widths compared to the others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a></a>ktest <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(Petal.Width<span class="sc">~</span>Species,<span class="at">data=</span>iris)</span>
<span id="cb44-2"><a></a>ktest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Petal.Width by Species
Kruskal-Wallis chi-squared = 131.19, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The p-value is 3.2617956^{-29}. At the 0.05 level of significance, we reject the null hypothesis. We have sufficient evidence that at least one species has a different distribution of petal widths compared to the others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>iris,<span class="fu">aes</span>(<span class="at">x=</span>Species,<span class="at">y=</span>Petal.Width)) <span class="sc">+</span> </span>
<span id="cb46-2"><a></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb46-3"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb46-4"><a></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Species"</span>,<span class="at">y=</span><span class="st">"Petal Width"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture11_files/figure-revealjs/unnamed-chunk-25-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-11-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a></a><span class="fu">ggplot</span>(<span class="at">data=</span>iris,<span class="fu">aes</span>(<span class="at">x=</span>Species,<span class="at">y=</span>Petal.Width)) <span class="sc">+</span> </span>
<span id="cb47-2"><a></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb47-3"><a></a>  <span class="fu">geom_violin</span>(<span class="fu">aes</span>(<span class="at">fill=</span>Species),<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb47-4"><a></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">palette=</span><span class="st">"viridis"</span>) <span class="sc">+</span></span>
<span id="cb47-5"><a></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb47-6"><a></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Species"</span>,<span class="at">y=</span><span class="st">"Petal Width"</span>,<span class="at">fill=</span><span class="st">"Species"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture11_files/figure-revealjs/unnamed-chunk-26-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="non-parametric-correlation-tests" class="title-slide slide level1 center">
<h1>Non-Parametric Correlation Tests</h1>

</section>
<section id="spearman-correlation" class="slide level2">
<h2>Spearman Correlation</h2>
<p>Recall Lecture 9: The Spearman correlation coefficient is a measure of association that measures monotonic correlation between the two variables.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The Spearman correlation coefficient is based on the data ranks, and can be used if the Pearson correlation assumptions are not met.</p>
</div>
</div>
</div>
</section>
<section id="statistical-hypotheses-4" class="slide level2">
<h2>Statistical Hypotheses</h2>
<p>The null hypothesis is that there is no association between the two variables. The alternative hypothesis can be one-sided (negative or positive association) or two-sided (there is an association).</p>
</section>
<section id="r-implementation-5" class="slide level2">
<h2><code>R</code> Implementation</h2>
<p>The function <code>cor.test()</code> can perform a test for the Spearman correlation, as long as the method is specified.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>If the method (<code>method="spearman"</code>) is unspecified, <code>cor.test()</code> defaults to the Pearson correlation coefficient.</p>
</div>
</div>
</div>
<div class="sourceCode" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a><span class="fu">cor.test</span>(df<span class="sc">$</span>x,df<span class="sc">$</span>y,<span class="at">alternative=</span><span class="st">"two.sided"</span>,<span class="at">method=</span><span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="example-4" class="slide level2">
<h2>Example</h2>
<p>Consider the sleep health data set <code>SleepHealthData.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb49-2"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span>
<span id="cb49-3"><a></a><span class="fu">glimpse</span>(sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 374
Columns: 13
$ person_id               &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…
$ gender                  &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male"…
$ age                     &lt;int&gt; 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29…
$ occupation              &lt;chr&gt; "Software Engineer", "Doctor", "Doctor", "Sale…
$ sleep_duration          &lt;dbl&gt; 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7…
$ quality_of_sleep        &lt;int&gt; 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6…
$ physical_activity_level &lt;int&gt; 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75…
$ stress_level            &lt;int&gt; 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8…
$ bmi_category            &lt;chr&gt; "Overweight", "Normal", "Normal", "Obese", "Ob…
$ blood_pressure          &lt;chr&gt; "126/83", "125/80", "125/80", "140/90", "140/9…
$ heart_rate              &lt;int&gt; 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70…
$ daily_steps             &lt;int&gt; 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80…
$ sleep_disorder          &lt;chr&gt; "None", "None", "None", "Sleep Apnea", "Sleep …</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-12" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-12-1">Question</a></li><li><a href="#tabset-12-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1">
<p>Calculate the Spearman correlation coefficient between the daily steps and sleep duration. Test for an association at the 0.01 level of significance.</p>
</div>
<div id="tabset-12-2">
<p>The null hypothesis is that there is no association between daily steps and sleep duration, while the alternative hypothesis is that there is an association between daily steps and sleep duration.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a>ctest <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(sleep<span class="sc">$</span>daily_steps,sleep<span class="sc">$</span>sleep_duration,<span class="at">alternative=</span><span class="st">"two.sided"</span>,<span class="at">method=</span><span class="st">"spearman"</span>)</span>
<span id="cb51-2"><a></a>ctest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  sleep$daily_steps and sleep$sleep_duration
S = 8630931, p-value = 0.8458
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.01008658 </code></pre>
</div>
</div>
<p>The estimate of the Spearman correlation coefficient is 0.0101, corresponding to a p-value of 0.8458492. We fail to reject the null hypothesis. There is insufficient evidence of an association between the daily number of steps and sleep duration.</p>
</div>
</div>
</div>
</section>
<section id="exercise-4" class="slide level2">
<h2>Exercise</h2>
<p>Consider the sleep health data set <code>SleepHealthData.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb53-2"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span>
<span id="cb53-3"><a></a><span class="fu">glimpse</span>(sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 374
Columns: 13
$ person_id               &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…
$ gender                  &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male"…
$ age                     &lt;int&gt; 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29…
$ occupation              &lt;chr&gt; "Software Engineer", "Doctor", "Doctor", "Sale…
$ sleep_duration          &lt;dbl&gt; 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7…
$ quality_of_sleep        &lt;int&gt; 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6…
$ physical_activity_level &lt;int&gt; 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75…
$ stress_level            &lt;int&gt; 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8…
$ bmi_category            &lt;chr&gt; "Overweight", "Normal", "Normal", "Obese", "Ob…
$ blood_pressure          &lt;chr&gt; "126/83", "125/80", "125/80", "140/90", "140/9…
$ heart_rate              &lt;int&gt; 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70…
$ daily_steps             &lt;int&gt; 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80…
$ sleep_disorder          &lt;chr&gt; "None", "None", "None", "Sleep Apnea", "Sleep …</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-13" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-13-1">Question</a></li><li><a href="#tabset-13-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-13-1">
<p>Calculate the Spearman correlation coefficient between the daily steps and quality of sleep. Test for an association at the 0.01 level of significance.</p>
</div>
<div id="tabset-13-2">
<p>The null hypothesis is that there is no association between daily steps and quality of sleep, while the alternative hypothesis is that there is an association between daily steps and quality of sleep</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a>ctest <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(sleep<span class="sc">$</span>daily_steps,sleep<span class="sc">$</span>quality_of_sleep,<span class="at">alternative=</span><span class="st">"two.sided"</span>,<span class="at">method=</span><span class="st">"spearman"</span>)</span>
<span id="cb55-2"><a></a>ctest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  sleep$daily_steps and sleep$quality_of_sleep
S = 8520266, p-value = 0.6606
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.02277921 </code></pre>
</div>
</div>
<p>The estimate of the Spearman correlation coefficient is 0.0228, corresponding to a p-value of 0.6605808. We fail to reject the null hypothesis. There is insufficient evidence of an association between the daily number of steps and quality of sleep.</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Lecture 11 - <a href="https://madfudolig.quarto.pub/introtobiostats/">Back to home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/madfudolig\.quarto\.pub\/introtobiostats");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
            for (let i=0; i<annoteTargets.length; i++) {
              const annoteTarget = annoteTargets[i];
              const targetCell = annoteTarget.getAttribute("data-target-cell");
              const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
              const contentFn = () => {
                const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
                if (content) {
                  const tipContent = content.cloneNode(true);
                  tipContent.classList.add("code-annotation-tip-content");
                  return tipContent.outerHTML;
                }
              }
              const config = {
                allowHTML: true,
                content: contentFn,
                onShow: (instance) => {
                  selectCodeLines(instance.reference);
                  instance.reference.classList.add('code-annotation-active');
                  window.tippy.hideAll();
                },
                onHide: (instance) => {
                  unselectCodeLines();
                  instance.reference.classList.remove('code-annotation-active');
                },
                maxWidth: 300,
                delay: [50, 0],
                duration: [200, 0],
                offset: [5, 10],
                arrow: true,
                appendTo: function(el) {
                  return el.parentElement.parentElement.parentElement;
                },
                interactive: true,
                interactiveBorder: 10,
                theme: 'light-border',
                placement: 'right',
                popperOptions: {
                  modifiers: [
                  {
                    name: 'flip',
                    options: {
                      flipVariations: false, // true by default
                      allowedAutoPlacements: ['right'],
                      fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                    },
                  },
                  {
                    name: 'preventOverflow',
                    options: {
                      mainAxis: false,
                      altAxis: false
                    }
                  }
                  ]        
                }      
              };
              window.tippy(annoteTarget, config); 
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>