<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>EAB 703-1002: Biostatistical Methods for the Health Sciences – Interval Estimation</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-12873a65cf666e61daa4b3cf91a98e13.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Interval Estimation</h1>
  <p class="subtitle">Lecture 6</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="outline" class="title-slide slide level1 center">
<h1>Outline</h1>
<ul>
<li><p>Estimation: Confidence Intervals</p></li>
<li><p>The t-distribution</p></li>
<li><p>Confidence Intervals for different parameters:</p>
<ul>
<li>Population Mean</li>
<li>Difference Between Two Population Means</li>
<li>Population Proportion</li>
<li>Diffrence Between Two Population Proportions</li>
</ul></li>
</ul>
</section>

<section>
<section id="estimation" class="title-slide slide level1 center">
<h1>Estimation</h1>

</section>
<section id="statistical-inference" class="slide level2">
<h2>Statistical Inference</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Statistical inference</strong> is the procedure by which we reach a conclusion about a population on the basis of the information contained in a sample drawn from that population.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The process of estimation entails calculating some statistic from the sample that is offered as an approximation of the corresponding parameter of the population from which the sample was drawn.</p>
</div>
</div>
</div>
</section>
<section id="point-estimation-vs.-interval-estimation" class="slide level2">
<h2>Point Estimation vs.&nbsp;Interval Estimation</h2>
<div title="Point Estimation">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Point Estimation</strong></p>
</div>
<div class="callout-content">
<p>Point estimation is the process of finding a single number to use as our best guess for the value of an unknown population parameter. Point estimates do not provide a measure of uncertainty.</p>
</div>
</div>
</div>
</div>
<div title="Interval Estimation">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interval Estimation</strong></p>
</div>
<div class="callout-content">
<p>Interval estimation involves estimating two numerical values that define a range of values that, with a specified degree of confidence, most likely includes the parameter being estimated.</p>
</div>
</div>
</div>
</div>
</section>
<section id="point-estimation-unbiased-estimators" class="slide level2">
<h2>Point Estimation: Unbiased Estimators</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The single computed value has been referred to as an estimate. On the other hand, the rule that tells us how to compute this estimate is referred to as an estimator.</p>
</div>
</div>
</div>
<div title="Unbiasedness">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Unbiasedness</strong></p>
</div>
<div class="callout-content">
<p>An estimator of a parameter <span class="math inline">\(\Theta\)</span>, <span class="math inline">\(T\)</span>, is said to be an unbiased estimator of <span class="math inline">\(\Theta\)</span> if <span class="math inline">\(E(T)=\Theta\)</span>. AN example of an unbiased estimator is the sample mean. The sample mean <span class="math inline">\(\bar{X}\)</span> is an unbiased estimator of the population mean.</p>
</div>
</div>
</div>
</div>
</section>
<section id="sampled-vs.-target-populations" class="slide level2">
<h2>Sampled vs.&nbsp;Target Populations</h2>
<div title="Target Population">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Target Population</strong></p>
</div>
<div class="callout-content">
<p>The target population is the population about which one wishes to make an inference.</p>
</div>
</div>
</div>
</div>
<div title="Sampled Population">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Sampled Population</strong></p>
</div>
<div class="callout-content">
<p>The sampled population is the population from which one actually draws a sample.</p>
</div>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>If the sampled population and the target population are different, the researcher can reach conclusions about the target population only on the basis of nonstatistical considerations. Estimation from the sampled population could lead to biased estimates.</p>
</div>
</div>
</div>
</section>
<section id="random-vs.-convenience-sampling" class="slide level2">
<h2>Random vs.&nbsp;Convenience Sampling</h2>
<p>In most examples in this class, we assume that the data was collected from random samples. However, it is impossible or impractical to use truly random samples.</p>
<div title="Convenience sampling">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Convenience sampling</strong></p>
</div>
<div class="callout-content">
<p>Convenience sampling involves sampling through volunteerism or readily available subjects to record data. While collecting data using convenience sampling is easy, the results might not be generalizable to the target population.</p>
</div>
</div>
</div>
</div>
</section>
<section id="interval-estimation-confidence-intervals" class="slide level2">
<h2>Interval Estimation: Confidence Intervals</h2>
<p>There are many variants of interval estimation methods that can be used. One of the more popular interval estimates is the <strong>confidence interval</strong>.</p>
<div title="Confidence Interval">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Confidence Interval</strong></p>
</div>
<div class="callout-content">
<p>A confidence interval is a random interval that will contain the true value of a parameter with probability <span class="math inline">\(1-\alpha\)</span>. The value <span class="math inline">\(1-\alpha\)</span> is called the <strong>confidence level</strong> of the interval.</p>
</div>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The confidence interval provides all plausible values of the parameters. The parameter itself is treated as fixed, while the endpoints of the confidence interval are treated as random variables. The endpoints are random because it depends on the data collected.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>The viewpoint for making a probability statement must be <strong>before</strong> the data are collected, not <strong>after</strong>.</p>
</div>
</div>
</div>
</section>
<section id="confidence-intervals" class="slide level2">
<h2>Confidence Intervals</h2>
<p>For the following tabs, supposed that the 95% confidence interval for the population mean, <span class="math inline">\(\mu\)</span>, was calculated to be the interval (80,100).</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Misconception 1</a></li><li><a href="#tabset-1-2">Misconception 2</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<div title="Misconception 1">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Misconception 1</strong></p>
</div>
<div class="callout-content">
<p>Misconception 1: <span class="math inline">\(P(80 &lt; \mu &lt; 100) = 0.95\)</span></p>
</div>
</div>
</div>
</div>
<p>This is incorrect. The parameter <span class="math inline">\(\mu\)</span> is not random, hence there shouldn’t be a probability assigned to it. 80 and 100 are also not random because we have already measured them. Either the interval contains the true value of <span class="math inline">\(\mu\)</span> or not. Hence, the probability interpretation does not make any sense.</p>
</div>
<div id="tabset-1-2">
<div title="Misconception 2">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Misconception 2</strong></p>
</div>
<div class="callout-content">
<p>Misconception 2: 95% of the population lies in the interval (80,100).</p>
</div>
</div>
</div>
</div>
<p>The confidence interval is for the population mean, not the set of all data values from the population. A confidence interval for the mean will often include only a small fraction of the population.</p>
</div>
</div>
</div>
</section>
<section id="interpretation-of-confidence-intervals" class="slide level2">
<h2>Interpretation of Confidence Intervals</h2>
<p>The confidence level is pertaining to the method that we calculated, not the particular interval. In the long run (or infinite repeated sampling), around 95% of the confidence intervals calculated will include <span class="math inline">\(\mu\)</span>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Since our method works 95% of the time, we believe that <span class="math inline">\(\mu\)</span> is in our 95% confidence interval. We don’t have the time and means to calculate all confidence intervals.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="confidence-intervals-1" class="title-slide slide level1 center">
<h1>Confidence Intervals</h1>

</section>
<section id="confidence-interval-form" class="slide level2">
<h2>Confidence Interval Form</h2>
<p>The confidence intervals in this chapter will follow the form:</p>
<p><span class="math display">\[
estimate \pm reliability~coefficient*standard~error
\]</span></p>
</section>
<section id="confidence-intervals-for-population-means" class="slide level2">
<h2>Confidence Intervals for Population Means</h2>
<p>We can estimate the population mean by using the mean of a representative sample from the population.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>The method differs for cases with known and unknown population variance. Some approximations can be done when there is a large sample size.</p>
</div>
</div>
</div>
</section>
<section id="ci-for-mean-known-population-variance" class="slide level2">
<h2>CI for Mean: Known Population Variance</h2>
<p>Cases in which population variances are known are rare. The best example of measurements with known population variances are standardized scales.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The Wechsler Adult Intelligence Scale (WAIS) maintains a standard deviation of 15 points for its full scale IQ scores.</p>
</div>
</div>
</div>
<p>For a known population variance <span class="math inline">\(\sigma^2\)</span>, sample mean <span class="math inline">\(\bar{x}\)</span>, and sample size <span class="math inline">\(n\)</span>, the 95% confidence limits for the <span class="math inline">\((1-\alpha)%\)</span> can be calculated using the following formula:</p>
<p><span class="math display">\[
\bar{x} \pm z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}}
\]</span></p>
</section>
<section id="ci-for-mean-notes" class="slide level2">
<h2>CI for Mean: Notes</h2>
<p>Confidence intervals are often written in parentheses notation as such:</p>
<p><span class="math display">\[
\left(\bar{x} - z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}}, \bar{x} + z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}}\right)
\]</span></p>
<p><span class="math inline">\(z_{1-\alpha/2}\)</span> is referred to as the reliability coefficient and defined as the following:</p>
<p><span class="math display">\[
P(Z \leq z_{1-\alpha/2}) = 1-\alpha/2
\]</span></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Recall that <span class="math inline">\(Z\)</span> follows the standard normal distribution. <span class="math inline">\(z_{1-\alpha/2}\)</span> can be calculated using <code>qnorm(1-alpha/2,mean=0,sd=1).</code> For a 95% confidence interval, <span class="math inline">\(\alpha = 0.05\)</span>, then it follows that <span class="math inline">\(1-\alpha/2 = 1-0.05/2 = 0.975\)</span>. Therefore, the reliability coefficient for a 95% confidence interval can be calculated as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>alpha<span class="ot">=</span><span class="fl">0.05</span></span>
<span id="cb1-2"><a></a><span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>
<p>The file <code>lec6example.csv</code> contains simulated values from a normal distribution with a variance of 4.</p>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Question</a></li><li><a href="#tabset-2-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p>Create a 95% confidence interval for the population mean. Is 1 a plausible value for the population mean?</p>
</div>
<div id="tabset-2-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># setwd("where your file is")</span></span>
<span id="cb3-2"><a></a>example <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/lec6example.csv"</span>)</span>
<span id="cb3-3"><a></a>sdpop <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We need to calculate the sample mean of the <code>Sims</code> column, the sample size, and the reliability coefficient.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-6"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-6-1"><a href="#annotated-cell-6-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(example<span class="sc">$</span>Sims)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-6" data-target-annotation="1">1</button><span id="annotated-cell-6-2" class="code-annotation-target"><a href="#annotated-cell-6-2"></a>sampsize <span class="ot">&lt;-</span> <span class="fu">nrow</span>(example)</span>
<span id="annotated-cell-6-3"><a href="#annotated-cell-6-3"></a>alpha <span class="ot">&lt;-</span> <span class="dv">1</span><span class="fl">-0.95</span></span>
<span id="annotated-cell-6-4"><a href="#annotated-cell-6-4"></a>relcoeff <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>,<span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-6" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-6" data-code-lines="2" data-code-annotation="1"><code>nrow()</code> calculates the number of rows of the data frame. If dealing with a singular vector, you can use <code>length()</code>. <code>nrow(example)</code> will yield the same answer as <code>length(example$Sims)</code>.</span>
</dd>
</dl>
</div>
</div>
<p>We can now calculate the 95% confidence interval limits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>lower <span class="ot">&lt;-</span> xbar <span class="sc">-</span> relcoeff<span class="sc">*</span>sdpop<span class="sc">/</span><span class="fu">sqrt</span>(sampsize)</span>
<span id="cb4-2"><a></a>upper <span class="ot">&lt;-</span> xbar <span class="sc">+</span> relcoeff<span class="sc">*</span>sdpop<span class="sc">/</span><span class="fu">sqrt</span>(sampsize)</span>
<span id="cb4-3"><a></a>lower</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6637448</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>upper</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.303866</code></pre>
</div>
</div>
<p>The resulting 95% confidence interval is (0.66, 1.3). Since 1 is in the confidence interval, then we can claim that 1 is a plausible value for the population mean.</p>
</div>
</div>
</div>
</section>
<section id="exercise" class="slide level2">
<h2>Exercise</h2>
<p>Consider the sleep health data uploaded on Canvas as <code>SleepHealthData.csv</code>. Suppose that in the population that this sample represents, the variance of the sleep duration is 0.5.</p>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Question</a></li><li><a href="#tabset-3-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p>Calculate the 95% confidence interval for the average sleep duration (<code>sleep_duration</code>) in the population this sample represents. Is 7 hours a plausible value for the average sleep distribution of the population?</p>
</div>
<div id="tabset-3-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span>
<span id="cb8-2"><a></a>sdpop <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fl">0.5</span>)</span>
<span id="cb8-3"><a></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(sleep<span class="sc">$</span>sleep_duration)</span>
<span id="cb8-4"><a></a>sampsize <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sleep)</span>
<span id="cb8-5"><a></a>alpha <span class="ot">&lt;-</span> <span class="dv">1</span><span class="fl">-0.95</span></span>
<span id="cb8-6"><a></a>relcoeff <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>) </span>
<span id="cb8-7"><a></a><span class="co"># not specifying the mean and sd in qnorm assumes standard normal</span></span>
<span id="cb8-8"><a></a></span>
<span id="cb8-9"><a></a>lower <span class="ot">&lt;-</span> xbar <span class="sc">-</span> relcoeff<span class="sc">*</span>sdpop<span class="sc">/</span><span class="fu">sqrt</span>(sampsize)</span>
<span id="cb8-10"><a></a>lower</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.060422</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>upper <span class="ot">&lt;-</span> xbar <span class="sc">+</span> relcoeff<span class="sc">*</span>sdpop<span class="sc">/</span><span class="fu">sqrt</span>(sampsize)</span>
<span id="cb10-2"><a></a>upper</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.203749</code></pre>
</div>
</div>
<p>The 95% confidence interval is (7.06,7.2). 7 is not a plausible value for the average sleep distribution of the population.</p>
</div>
</div>
</div>
</section>
<section id="precision" class="slide level2">
<h2>Precision</h2>
<p>The precision of an interval estimate is related to its width.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The precision, also known as the <strong>margin of error</strong>, can be expressed as the product of the reliability coefficient and the standard error.</p>
</div>
</div>
</div>
<p>For the case of the population mean with known population variance,</p>
<p><span class="math display">\[
precision = z_{1-\alpha/2}* \frac{\sigma}{\sqrt{n}} = \frac{upper-lower}{2}
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Because of the symmetry of the confidence interval, the precision is half the width of the confidence interval.</p>
</div>
</div>
</div>
</section>
<section id="ci-for-mean-unknown-population-variance" class="slide level2">
<h2>CI for Mean: Unknown Population Variance</h2>
<p>It is more common to not know the population variance when estimating the population mean. Because of this, we are inclined to use the next best thing: an estimate of the population variance from the collected sample. This estimate is the <strong>sample variance</strong></p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Using an approximate value for the population variance implies that our standardized statistic <strong>might not</strong> follow the standard normal distribution. We need a new distribution to calculate reliability coefficients for these confidence intervals.</p>
</div>
</div>
</div>
</section>
<section id="the-students-t-distribution" class="slide level2">
<h2>The Student’s t-distribution</h2>
<p>The <span class="math inline">\(t\)</span> distribution is symmetric and bell-shaped like the normal distribution, but has heavier tails.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Heavier tails mean that the distribution is more likely to produce values that fall farther from the mean compared to the normal distribution. The heavier tails account for the extra uncertainty introduced by using the sample variance to estimate the population variance.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The t-distribution is defined by the degrees of freedom denoted by <span class="math inline">\(\nu\)</span> or <code>df</code>, and specific t-distributions can be written as <span class="math inline">\(t_{\nu}\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="the-t-distribution-r" class="slide level2">
<h2>The t distribution: <code>R</code></h2>
<p>The <code>R</code> syntax for the t-distribution with degrees of freedom <code>df</code> consists of the following functions:</p>
<ul>
<li>PDF: <code>dt(x,df)</code></li>
<li>CDF: <code>pt(x,df)</code></li>
<li>Quantile: <code>qt(x,df)</code></li>
<li>Generate/Simulate <code>n</code> t-distribution points: <code>rt(n,df)</code></li>
</ul>
</section>
<section id="ci-for-mean-unknown-population-variance-1" class="slide level2">
<h2>CI for Mean: Unknown Population Variance</h2>
<p>When the population variance is unknown OR the sample from a normally distributed population has a low sample size, the <span class="math inline">\((1-\alpha)*100%\)</span> confidence interval can be calculated using the following formula:</p>
<p><span class="math display">\[
\bar{x} \pm t_{\nu,1-\alpha/2} \frac{s}{\sqrt{n}}
\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(s\)</span> is the sample standard deviation <span class="math inline">\(t_{\nu,1-\alpha/2}\)</span> is defined as <span class="math inline">\(P(t&lt;t_{\nu,1-\alpha/2}) = 1-\alpha/2\)</span>. The degrees of freedom <span class="math inline">\(\nu\)</span> can be calculated as <span class="math inline">\(\nu=n-1\)</span>.</p>
</div>
</div>
</div>
<p>The 95% confidence interval can be written as:</p>
<p><span class="math display">\[
\left(\bar{x} - t_{\nu,1-\alpha/2} \frac{s}{\sqrt{n}}, \bar{x} + t_{\nu,1-\alpha/2} \frac{s}{\sqrt{n}}\right)
\]</span></p>
</section>
<section id="precision-1" class="slide level2">
<h2>Precision</h2>
<p>The precision of an interval estimate is related to its width.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The precision, also known as the <strong>margin of error</strong>, can be expressed as the product of the reliability coefficient and the standard error.</p>
</div>
</div>
</div>
<p>For the case of the population mean with unknown population variance,</p>
<p><span class="math display">\[
precision = t_{\nu,1-\alpha/2} \frac{s}{\sqrt{n}}= \frac{upper-lower}{2}
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Because of the symmetry of the confidence interval, the precision is half the width of the confidence interval.</p>
</div>
</div>
</div>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<p>The file <code>lec6example.csv</code> contains simulated values from a normal distribution.</p>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Question</a></li><li><a href="#tabset-4-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<p>Supposed the population variance is unknown. Create a 95% confidence interval for the population mean. Is 1 a plausible value for the population mean?</p>
</div>
<div id="tabset-4-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="co"># setwd("where your file is")</span></span>
<span id="cb12-2"><a></a>example <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/lec6example.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We need to calculate the sample mean of the <code>Sims</code> column, the sample size, and the reliability coefficient.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-16"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-16-1"><a href="#annotated-cell-16-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(example<span class="sc">$</span>Sims)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-16" data-target-annotation="1">1</button><span id="annotated-cell-16-2" class="code-annotation-target"><a href="#annotated-cell-16-2"></a>sampsize <span class="ot">&lt;-</span> <span class="fu">nrow</span>(example)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-16" data-target-annotation="2">2</button><span id="annotated-cell-16-3" class="code-annotation-target"><a href="#annotated-cell-16-3"></a>stdev <span class="ot">&lt;-</span> <span class="fu">sd</span>(example<span class="sc">$</span>Sims)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-16" data-target-annotation="3">3</button><span id="annotated-cell-16-4" class="code-annotation-target"><a href="#annotated-cell-16-4"></a>df <span class="ot">&lt;-</span> sampsize<span class="dv">-1</span></span>
<span id="annotated-cell-16-5"><a href="#annotated-cell-16-5"></a>alpha <span class="ot">&lt;-</span> <span class="dv">1</span><span class="fl">-0.95</span></span>
<span id="annotated-cell-16-6"><a href="#annotated-cell-16-6"></a>relcoeff <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="at">p=</span><span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>,<span class="at">df=</span>df) </span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-16" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-16" data-code-lines="2" data-code-annotation="1"><code>nrow()</code> calculates the number of rows of the data frame. If dealing with a singular vector, you can use <code>length()</code>. <code>nrow(example)</code> will yield the same answer as <code>length(example$Sims)</code>.</span>
</dd>
<dt data-target-cell="annotated-cell-16" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-16" data-code-lines="3" data-code-annotation="2">We are calculating the sample variance using <code>sd()</code>.</span>
</dd>
<dt data-target-cell="annotated-cell-16" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-16" data-code-lines="4" data-code-annotation="3">Degrees of freedom <code>df = n-1</code>.</span>
</dd>
</dl>
</div>
</div>
<p>We can now calculate the 95% confidence interval limits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>lower <span class="ot">&lt;-</span> xbar <span class="sc">-</span> relcoeff<span class="sc">*</span>stdev<span class="sc">/</span><span class="fu">sqrt</span>(sampsize)</span>
<span id="cb13-2"><a></a>upper <span class="ot">&lt;-</span> xbar <span class="sc">+</span> relcoeff<span class="sc">*</span>stdev<span class="sc">/</span><span class="fu">sqrt</span>(sampsize)</span>
<span id="cb13-3"><a></a>lower</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6642442</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>upper</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.303367</code></pre>
</div>
</div>
<p>The resulting 95% confidence interval is (0.66, 1.3). Since 1 is in the confidence interval, then we can claim that 1 is a plausible value for the population mean.</p>
</div>
</div>
</div>
</section>
<section id="exercise-1" class="slide level2">
<h2>Exercise</h2>
<p>Consider the sleep health data uploaded on Canvas as <code>SleepHealthData.csv</code>.</p>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Question</a></li><li><a href="#tabset-5-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<p>Calculate the <strong>99%</strong> confidence interval for the average heart rate (<code>heart_rate</code>) in bpm in the population this sample represents. Is 65 bpm a plausible value for the average sleep distribution of the population? Calculate the margin of error.</p>
</div>
<div id="tabset-5-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepHealthData.csv"</span>)</span>
<span id="cb17-2"><a></a>sdpop <span class="ot">&lt;-</span> <span class="fu">sd</span>(sleep<span class="sc">$</span>heart_rate)</span>
<span id="cb17-3"><a></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(sleep<span class="sc">$</span>heart_rate)</span>
<span id="cb17-4"><a></a>sampsize <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sleep)</span>
<span id="cb17-5"><a></a>alpha <span class="ot">&lt;-</span> <span class="dv">1</span><span class="fl">-0.99</span></span>
<span id="cb17-6"><a></a>relcoeff <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="at">p=</span><span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>,<span class="at">df=</span>sampsize<span class="dv">-1</span>) </span>
<span id="cb17-7"><a></a><span class="co"># not specifying the mean and sd in qnorm assumes standard normal</span></span>
<span id="cb17-8"><a></a></span>
<span id="cb17-9"><a></a>lower <span class="ot">&lt;-</span> xbar <span class="sc">-</span> relcoeff<span class="sc">*</span>sdpop<span class="sc">/</span><span class="fu">sqrt</span>(sampsize)</span>
<span id="cb17-10"><a></a>lower</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 69.6121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>upper <span class="ot">&lt;-</span> xbar <span class="sc">+</span> relcoeff<span class="sc">*</span>sdpop<span class="sc">/</span><span class="fu">sqrt</span>(sampsize)</span>
<span id="cb19-2"><a></a>upper</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 70.71945</code></pre>
</div>
</div>
<p>The 99% confidence interval is (69.61,70.72). 65 is not a plausible value for the average heart rate of the population.</p>
<p>The margin of error can be calculated as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>relcoeff<span class="sc">*</span>sdpop<span class="sc">/</span><span class="fu">sqrt</span>(sampsize)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5536753</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>(upper<span class="sc">-</span>lower)<span class="sc">/</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5536753</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="confidence-interval-for-population-proportions" class="slide level2">
<h2>Confidence Interval for Population Proportions</h2>
<p>Many questions of interest to the health worker relate to population proportions.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Some questions could be:</p>
<ul>
<li>What is the recovery rate of patients for a particular type of treatment?</li>
<li>What is the prevalence rate of a disease?</li>
<li>What proportion of medical providers agree with current health recommendations?</li>
</ul>
</div>
</div>
</div>
</section>
<section id="ci-population-proportions" class="slide level2">
<h2>CI: Population Proportions</h2>
<p>For a sample of size <span class="math inline">\(n\)</span> and sample proportion <span class="math inline">\(\hat{p}\)</span>, the <span class="math inline">\(100(1-\alpha)\)</span>% confidence interval for the population proportion <span class="math inline">\(\pi\)</span> is given by:</p>
<p><span class="math display">\[
\hat{p} \pm z_{1-\alpha/2} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}
\]</span></p>
<p>Similar to the CI for means, <span class="math inline">\(z_{1-\alpha/2}\)</span> is defined as <span class="math inline">\(P(Z \leq z_{1-\alpha/2}) = 1-\alpha/2\)</span>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The use of <span class="math inline">\(z_{1-\alpha/2}\)</span> can be justified using the central limit theorem (CLT). The most common guideline for the CLT to apply to proportions is that <span class="math inline">\(n\pi\)</span> and <span class="math inline">\(n(1-\pi)\)</span> are both greater than five.</p>
</div>
</div>
</div>
<p>The CI would then be reported as:</p>
<p><span class="math display">\[
\left(\hat{p} - z_{1-\alpha/2} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}},\hat{p} + z_{1-\alpha/2} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}} \right)
\]</span></p>
</section>
<section id="example-2" class="slide level2">
<h2>Example</h2>
<p>The data set <code>Liver_Steatosis.csv</code> comes from a retrospective cohort study to estimate the prevalence of liver steatosis (fatty liver disease) in those who had bariatric surgery (<a href="https://pubmed.ncbi.nlm.nih.gov/21901286/">Wu et al, 2012</a>). The data set also includes other covariates and comorbidities.</p>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Question</a></li><li><a href="#tabset-6-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p>One of the comorbidities studied was history of metabolic syndrome (1=Yes, 2=No, <code>NA</code> = missing). Calculate a 95% confidence interval for the prevalence of metabolic syndrome based on the data. Only consider <strong>non-missing data</strong> in your analysis.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>This data set was collected from patients who had bariatric surgery at the Cleveland Clinic between 2005 and 2009 and underwent liver biopsy. Is this result generalizable to all US adults who have had bariatric surgery?</p>
</div>
</div>
</div>
</div>
<div id="tabset-6-2">
<p>We need to calculate the proportion of patients reported to have metabolic syndrome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a><span class="fu">library</span>(summarytools)</span>
<span id="cb25-2"><a></a>liver <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/Liver_Steatosis.csv"</span>)</span>
<span id="cb25-3"><a></a>summarytools<span class="sc">::</span><span class="fu">freq</span>(liver<span class="sc">$</span>MET_Syndrome)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Frequencies  
liver$MET_Syndrome  
Type: Integer  

              Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
----------- ------ --------- -------------- --------- --------------
          0    144     32.65          32.65     32.51          32.51
          1    297     67.35         100.00     67.04          99.55
       &lt;NA&gt;      2                               0.45         100.00
      Total    443    100.00         100.00    100.00         100.00</code></pre>
</div>
</div>
<p>Based on <code>freq</code>, the proportion of those with metabolic syndrome is 0.6735 out of a sample size of 441 (removed two missing). We now have everything we need to calculate the confidence interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a>phat <span class="ot">&lt;-</span> <span class="dv">297</span><span class="sc">/</span><span class="dv">443</span></span>
<span id="cb27-2"><a></a>sampsize <span class="ot">&lt;-</span> <span class="dv">441</span></span>
<span id="cb27-3"><a></a>alpha <span class="ot">&lt;-</span> <span class="dv">1</span><span class="fl">-0.95</span></span>
<span id="cb27-4"><a></a>relcoeff <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="at">p=</span><span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb27-5"><a></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((phat<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>phat)<span class="sc">/</span>sampsize))</span>
<span id="cb27-6"><a></a></span>
<span id="cb27-7"><a></a>lower <span class="ot">&lt;-</span> phat <span class="sc">-</span> relcoeff<span class="sc">*</span>se</span>
<span id="cb27-8"><a></a>lower</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6265577</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>upper <span class="ot">&lt;-</span> phat <span class="sc">+</span> relcoeff<span class="sc">*</span>se</span>
<span id="cb29-2"><a></a>upper</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7143001</code></pre>
</div>
</div>
<p>The 95% confidence interval for the proportion of patients with metabolic syndrome is (0.6266,0.7143).</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Caution should be exercised in generalizing this result to all patients from the country as this is a very specific sample.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="slide level2">
<h2>Exercise</h2>
<p>Consider the sleep health data uploaded on Canvas as <code>SleepHealthData.csv</code>.</p>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Question</a></li><li><a href="#tabset-7-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<p>Use the <code>sleep_disorder</code> column to do the following:</p>
<ul>
<li>Estimate the prevalence rate of sleep apnea in the population this sample represents using the sample proportion.</li>
<li>Calculate a 90% confidence interval for the prevalence rate of sleep apnea.</li>
</ul>
</div>
<div id="tabset-7-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a><span class="fu">freq</span>(sleep<span class="sc">$</span>sleep_disorder)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Frequencies  
sleep$_disorder  
Type: Character  

                    Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
----------------- ------ --------- -------------- --------- --------------
         Insomnia     77     20.59          20.59     20.59          20.59
             None    219     58.56          79.14     58.56          79.14
      Sleep Apnea     78     20.86         100.00     20.86         100.00
             &lt;NA&gt;      0                               0.00         100.00
            Total    374    100.00         100.00    100.00         100.00</code></pre>
</div>
</div>
<p>The proportion of participants who reported sleep apnea is 0.2086. The sample size is 374. We can now calculate a 90% confidence interval for the prevalence rate of sleep apnea based on this sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a>phat <span class="ot">&lt;-</span> <span class="dv">78</span><span class="sc">/</span><span class="dv">374</span></span>
<span id="cb33-2"><a></a>sampsize <span class="ot">&lt;-</span> <span class="dv">374</span></span>
<span id="cb33-3"><a></a>alpha <span class="ot">=</span> <span class="dv">1</span><span class="fl">-0.9</span></span>
<span id="cb33-4"><a></a>relcoeff <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="at">p=</span><span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb33-5"><a></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((phat<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>phat)<span class="sc">/</span>sampsize))</span>
<span id="cb33-6"><a></a></span>
<span id="cb33-7"><a></a>lower <span class="ot">&lt;-</span> phat <span class="sc">-</span> relcoeff<span class="sc">*</span>se</span>
<span id="cb33-8"><a></a>lower</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.174001</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a>upper <span class="ot">&lt;-</span> phat <span class="sc">+</span> relcoeff<span class="sc">*</span>se</span>
<span id="cb35-2"><a></a>upper</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2431113</code></pre>
</div>
</div>
<p>The 90% confidence interval for the prevalence rate of sleep apnea in the population this sample represents is (0.174,0.2431).</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="sample-size-calculation" class="title-slide slide level1 center">
<h1>Sample Size Calculation</h1>

</section>
<section id="how-to-determine-sample-sizes" class="slide level2">
<h2>How to determine sample sizes</h2>
<p>Before data are collected, we often need to make a decision about how large of a sample will be required to estimate population parameters.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The sample size depends on the precision/margin of error we would like for our resulting confidence intervals.</p>
</div>
</div>
</div>
</section>
<section id="sample-size-for-population-proportion-estimation" class="slide level2">
<h2>Sample size for population proportion estimation</h2>
<p>Suppose we want our margin of error (MOE) to be equal to <span class="math inline">\(E\)</span> for our planned study. The corresponding estimate for the sample size needed to reach this level of precision is given by</p>
<p><span class="math display">\[
n = z^2_{1-\alpha/2} \frac{ \hat{\pi}(1-\hat{\pi})}{E^2}
\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Note that the population proportion AND sample proportion are unknown before data collection. However, we need to have an idea what the expected proportion is for our study, denoted by <span class="math inline">\(\hat{\pi}\)</span> in this case. This proportion can be estimated from prior or pilot studies. If there are no prior studies available (which is the case for some pilot studies), we can assume <span class="math inline">\(\hat{\pi}=0.5\)</span> to create a conservative confidence interval.</p>
</div>
</div>
</div>
</section>
<section id="example-3" class="slide level2">
<h2>Example</h2>
<p>Suppose we want to design a pilot study to estimate the proportion of young adults in NV who use anabolic-androgenic steroids for muscle growth.</p>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Question</a></li><li><a href="#tabset-8-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p>Calculate the sample size required so the resulting 95% confidence interval estimates will have a margin of error of 5%.</p>
</div>
<div id="tabset-8-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a>E <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb37-2"><a></a>pi_hat <span class="ot">&lt;-</span><span class="fl">0.5</span></span>
<span id="cb37-3"><a></a>alpha <span class="ot">&lt;-</span> <span class="dv">1</span><span class="fl">-0.95</span></span>
<span id="cb37-4"><a></a>z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="at">p=</span><span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb37-5"><a></a></span>
<span id="cb37-6"><a></a>sampsize <span class="ot">&lt;-</span> z<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>pi_hat<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>pi_hat)<span class="sc">/</span>E<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb37-7"><a></a>sampsize</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 384.1459</code></pre>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>When doing sample size calculations, always <strong>round up</strong> your final answer. For this study, you would recommend recruiting 385 participants for the study so that the MOE for the interval estimate of the usage rate of anabolic-androgenic steroids for muscle growth will be approximately 5%.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-3" class="slide level2">
<h2>Exercise</h2>
<p>Suppose we performed the pilot study on steroid use and we plan to use the results to design a large scale study.</p>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Question</a></li><li><a href="#tabset-9-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<p>The pilot study yielded an estimated usage rate of 32%. Calculate the sample size required so the resulting 95% confidence interval estimates will have a margin of error of 1%.</p>
</div>
<div id="tabset-9-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a>E <span class="ot">&lt;-</span> <span class="fl">0.01</span></span>
<span id="cb39-2"><a></a>pi_hat <span class="ot">&lt;-</span><span class="fl">0.32</span></span>
<span id="cb39-3"><a></a>alpha <span class="ot">&lt;-</span> <span class="dv">1</span><span class="fl">-0.95</span></span>
<span id="cb39-4"><a></a>z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="at">p=</span><span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb39-5"><a></a></span>
<span id="cb39-6"><a></a>sampsize <span class="ot">&lt;-</span> z<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>pi_hat<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>pi_hat)<span class="sc">/</span>E<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb39-7"><a></a>sampsize</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8359.014</code></pre>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>For this study, you would recommend recruiting 8360 participants for the study so that the MOE for the interval estimate of the usage rate of anabolic-androgenic steroids for muscle growth will be approximately 1%.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sample-size-for-population-mean-estimation" class="slide level2">
<h2>Sample size for population mean estimation</h2>
<p>Suppose we want our margin of error (MOE) to be equal to <span class="math inline">\(E\)</span> for our planned study. The corresponding estimate for the sample size needed to reach this level of precision is given by</p>
<p><span class="math display">\[
n = z^2_{1-\alpha/2} \frac{\hat{\sigma}^2}{E^2}
\]</span></p>
<p>where <span class="math inline">\(\hat{\sigma}\)</span> is an a priori estimate of the population standard deviation. As with the estimated population proportion, this value can be obtained from prior studies or estimated using pilot studies.</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Recall that for a Gaussian distribution, approximately 99% of the population can be found within the range <span class="math inline">\((\mu-3\sigma,\mu+3\sigma)\)</span>. The width of this region is <span class="math inline">\(6\sigma\)</span>, which could be approximated by the range of the data. Hence, an approximate of the population standard deviation could be expressed as: <span class="math inline">\(\sigma= R/6\)</span>, where <span class="math inline">\(R\)</span> is the range.</p>
</div>
</div>
</div>
</section>
<section id="example-4" class="slide level2">
<h2>Example</h2>
<p>Suppose we want to estimate the average number of views that health provider social media pages in Nevada receive weekly.</p>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Question</a></li><li><a href="#tabset-10-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<p>If the range of mean views was estimated to be 300,000, how many social media pages should be sampled so that our 99% confidence interval for the average number of views of Nevada health provider social media pages has a margin of error of 10,000?</p>
</div>
<div id="tabset-10-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a>alpha <span class="ot">&lt;-</span> <span class="dv">1</span><span class="fl">-0.99</span></span>
<span id="cb41-2"><a></a>z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="at">p=</span><span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb41-3"><a></a>sigma <span class="ot">&lt;-</span> <span class="dv">300000</span><span class="sc">/</span><span class="dv">6</span></span>
<span id="cb41-4"><a></a>E <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb41-5"><a></a>sampsize <span class="ot">&lt;-</span>z<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>sigma<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>E<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb41-6"><a></a>sampsize</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 165.8724</code></pre>
</div>
</div>
<p>We need to sample 166 to achieve a margin of error of 10,000 for our 99% confidence interval.</p>
</div>
</div>
</div>
</section>
<section id="example-5" class="slide level2">
<h2>Example</h2>
<p>You designed a study to estimate the average number of views that health provider social media pages in Nevada receive weekly.</p>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">Question</a></li><li><a href="#tabset-11-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<p>Suppose your boss was not happy with the margin of error for the 99% confidence interval of 10,000 and wanted to decrease the margin of error to 500. How many samples would be recommended for the study if the range of mean views was estimated to be 300,000.</p>
</div>
<div id="tabset-11-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a>alpha <span class="ot">&lt;-</span> <span class="dv">1</span><span class="fl">-0.99</span></span>
<span id="cb43-2"><a></a>z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="at">p=</span><span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb43-3"><a></a>sigma <span class="ot">&lt;-</span> <span class="dv">300000</span><span class="sc">/</span><span class="dv">6</span></span>
<span id="cb43-4"><a></a>E <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb43-5"><a></a>sampsize <span class="ot">&lt;-</span>z<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>sigma<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>E<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb43-6"><a></a>sampsize</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 66348.97</code></pre>
</div>
</div>
<p>We need to sample 66349 to achieve a margin of error of 500 for our 99% confidence interval.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="confidence-intervals-for-difference-in-statistics" class="title-slide slide level1 center">
<h1>Confidence Intervals for Difference in Statistics</h1>

</section>
<section id="ci-for-difference-in-statistics" class="slide level2">
<h2>CI for Difference in Statistics</h2>
<p>Often, we are more interested in comparing between two groups.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Recall that in Chapter 5, we showed how differences between two parameters had a different sampling distribution that individual parameters.</p>
</div>
</div>
</div>
</section>
<section id="ci-for-difference-in-population-means" class="slide level2">
<h2>CI for Difference in Population Means</h2>
<p>For two groups with known population variances <span class="math inline">\(\sigma_1\)</span> and <span class="math inline">\(\sigma_2\)</span>, the <span class="math inline">\(100(1-\alpha)\)</span>% can be calculated using the following formula:</p>
<p><span class="math display">\[
(\bar{x}_1-\bar{x}_2) \pm z_{1-\alpha/2}\sqrt{\sigma_1^2/n_1 + \sigma_2^2/n_2}
\]</span></p>
</section>
<section id="ci-for-difference-in-population-means-1" class="slide level2">
<h2>CI for Difference in Population Means</h2>
<p>For two groups with unknown population variances, we will still use the sample variances to estimate the population variances of each group. However, we have to consider two cases:</p>
<div class="panel-tabset">
<ul id="tabset-12" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-12-1">Equal Pop. Variances</a></li><li><a href="#tabset-12-2">Unequal Pop. Variances</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1">
<p>When the population variances are assumed to be equal, we need to introduce a pooled variance to estimate the variance for each group.</p>
<p><span class="math display">\[
s_p^2 = \frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}
\]</span></p>
<p>This results to the following <span class="math inline">\(100(1-\alpha)\)</span>% confidence interval:</p>
<p><span class="math display">\[
(\bar{x}_1-\bar{x}_2) \pm t_{1-\alpha/2,df} \sqrt{s_p^2\left(\frac{1}{n_1} + \frac{1}{n_2}\right)}
\]</span></p>
<p>where <span class="math inline">\(t_{1-\alpha/2,df}\)</span> has degrees of freedom equal to <span class="math inline">\(df= n_1+n_2-2\)</span>.</p>
</div>
<div id="tabset-12-2">
<p>When the population variances are not equal, then we don’t need to pool the variances. However, the t-distribution has to account for the fact that we are using estimated variances for both groups.</p>
<p>We introduce the <strong>Welch-Satterthwaite</strong> procedure to construct this confidence interval such that the <span class="math inline">\(100(1-\alpha)\)</span>% confidence interval is given by:</p>
<p><span class="math display">\[
(\bar{x}_1-\bar{x}_2) \pm t_{1-\alpha/2,df}\sqrt{s_1^2/n_1 + s_2^2/n_2}
\]</span></p>
<p>where</p>
<p><span class="math display">\[
df = \frac{(s_1^2/n_1 + s_2^2/n_2)^2}{\left(\frac{s_1^2}{n_1}\right)^2/(n_1-1) + \left(\frac{s_2^2}{n_2}\right)^2/(n_2-1)}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="r-implementation" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>We can use <code>R</code> to manually calculate the confidence intervals using the formulas provided. However, there is an <code>R</code> function called <code>t.test(formula,conf.level=conf.level, var.equal=TRUE)</code> that we can use to calculate these confidence intervals.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>This approach will not work with aggregated data (Mean and SD provided). When data is aggregated, you would need to use the formulas.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The <code>formula</code> should be of the form <code>response_variable~group_variable</code>. It can also be of the form <code>x = df$col1, y=df$col2</code> if the data has two separate columns for the two groups.</p>
</div>
</div>
</div>
</section>
<section id="example-6" class="slide level2">
<h2>Example</h2>
<p>Consider the sleep health data uploaded on Canvas as <code>SleepHealthData.csv</code>.</p>
<div class="panel-tabset">
<ul id="tabset-13" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-13-1">Question</a></li><li><a href="#tabset-13-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-13-1">
<p>Calculate a 95% confidence interval for the difference in average age of males and females who participated in the study assuming equal population variances.</p>
</div>
<div id="tabset-13-2">
<p>The groups are not presented as two separate columns, but rather defined by another column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a>confidence_int <span class="ot">&lt;-</span> <span class="fu">t.test</span>(age<span class="sc">~</span>gender,</span>
<span id="cb45-2"><a></a>       <span class="at">data=</span>sleep,</span>
<span id="cb45-3"><a></a>       <span class="at">var.equal=</span>T,</span>
<span id="cb45-4"><a></a>       <span class="at">conf.level=</span><span class="fl">0.95</span>)</span>
<span id="cb45-5"><a></a></span>
<span id="cb45-6"><a></a>confidence_int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  age by gender
t = 14.329, df = 372, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
95 percent confidence interval:
  8.913564 11.749098
sample estimates:
mean in group Female   mean in group Male 
            47.40541             37.07407 </code></pre>
</div>
</div>
<p>The 95% confidence interval was calculated to be: (8.9136,11.7491)</p>
</div>
</div>
</div>
</section>
<section id="example-7" class="slide level2">
<h2>Example</h2>
<p>The file <code>40yarddash.csv</code> includes the 40-yard dash times from randomly selected football players from a D1 and D3 university.</p>
<div class="panel-tabset">
<ul id="tabset-14" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-14-1">Question</a></li><li><a href="#tabset-14-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-14-1">
<p>Calculate a 90% confidence interval for the difference in average 40-yard dash times between the two groups assuming unequal variances.</p>
</div>
<div id="tabset-14-2">
<p>The groups are presented as two separate columns, hence we cannot use the formula notation. We have to define <code>x</code> and <code>y</code> in <code>t.test</code> to estimate the difference of averages in <code>x</code> and <code>y</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a></a>yard<span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"40yarddash.csv"</span>)</span>
<span id="cb47-2"><a></a>confidence_int <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="at">x=</span>yard<span class="sc">$</span>D1,<span class="at">y=</span>yard<span class="sc">$</span>D3,</span>
<span id="cb47-3"><a></a>       <span class="at">var.equal=</span>F,</span>
<span id="cb47-4"><a></a>       <span class="at">conf.level=</span><span class="fl">0.9</span>)</span>
<span id="cb47-5"><a></a></span>
<span id="cb47-6"><a></a>confidence_int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  yard$D1 and yard$D3
t = -4.5203, df = 41.952, p-value = 4.979e-05
alternative hypothesis: true difference in means is not equal to 0
90 percent confidence interval:
 -0.7112031 -0.3254636
sample estimates:
mean of x mean of y 
 4.717667  5.236000 </code></pre>
</div>
</div>
<p>The 90% confidence interval for the difference in 40-yard dash times was calculated to be: (-0.7112,-0.3255)</p>
</div>
</div>
</div>
</section>
<section id="exercise-4" class="slide level2">
<h2>Exercise</h2>
<p>Consider the sleep health data uploaded on Canvas as <code>SleepHealthData.csv</code>.</p>
<div class="panel-tabset">
<ul id="tabset-15" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-15-1">Question</a></li><li><a href="#tabset-15-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-15-1">
<p>Calculate a 95% confidence interval for the difference in average sleep duration of males and females who participated in the study assuming equal population variances.</p>
</div>
<div id="tabset-15-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a></a>confidence_int <span class="ot">&lt;-</span> <span class="fu">t.test</span>(sleep_duration<span class="sc">~</span>gender,</span>
<span id="cb49-2"><a></a>       <span class="at">data=</span>sleep,</span>
<span id="cb49-3"><a></a>       <span class="at">var.equal=</span>T,</span>
<span id="cb49-4"><a></a>       <span class="at">conf.level=</span><span class="fl">0.95</span>)</span>
<span id="cb49-5"><a></a></span>
<span id="cb49-6"><a></a>confidence_int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  sleep_duration by gender
t = 2.3624, df = 372, p-value = 0.01867
alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
95 percent confidence interval:
 0.03239537 0.35404821
sample estimates:
mean in group Female   mean in group Male 
            7.229730             7.036508 </code></pre>
</div>
</div>
<p>The 95% confidence interval was calculated to be: (0.0324,0.354)</p>
</div>
</div>
</div>
</section>
<section id="ci-for-difference-in-proportions" class="slide level2">
<h2>CI for Difference in Proportions</h2>
<p>For populations with <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are large and the population proportions <span class="math inline">\(\pi_1\)</span> and <span class="math inline">\(\pi_2\)</span> are not too close to 0 or 1, we can implement the central limit theorem and assume the Gaussian distribution for the sampling distribution of the difference in proportions.</p>
<p>The resulting <span class="math inline">\(100(1-\alpha)\)</span>% confidence interval for <span class="math inline">\(\pi_1-\pi_2\)</span> can be expressed as:</p>
<p><span class="math display">\[
\hat{p}_1 - \hat{p}_2 \pm z_{1-\alpha/2} \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1}+\frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>This does not include a continuity correction.</p>
</div>
</div>
</div>
</section>
<section id="r-implementation-1" class="slide level2">
<h2><code>R</code> implementation</h2>
<p>The function <code>prop.test()</code> can calculate the confidence intervals for the difference in proportions, even adding the continuity correction. Suppose the successes for each group are denoted by <code>x1</code> and <code>x2</code>, while the totals for each group are <code>n1</code> and <code>n2</code>.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a><span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">c</span>(x1,x2), <span class="at">n=</span><span class="fu">c</span>(n1,n2),<span class="at">conf.level=</span><span class="fl">0.95</span>, <span class="at">correct=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>For the resulting CI with the continuity correction, set <code>correct=TRUE</code>.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>The <code>prop.test()</code> can be used to implement the continuity correction. While the <code>prop.test()</code> can calculate the confidence intervals, it uses the pooled variance method in confidence intervals. It also uses a different distribution to calculate the reliability coefficient.</p>
</div>
</div>
</div>
</section>
<section id="example-8" class="slide level2">
<h2>Example</h2>
<p>Consider the liver steatosis data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a></a>liver <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Liver_Steatosis.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-16" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-16-1">Question</a></li><li><a href="#tabset-16-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-16-1">
<p>Calculate the 95% confidence interval of the difference between the proportion of positive liver steatosis detections using ultrasound (<code>LS_US=1</code>) and through biopsy (<code>LS_Biopsy=1</code>). Is it plausible that the long-run detection rates for the two methods are equal? Omit missing data and apply the continuity correction.</p>
</div>
<div id="tabset-16-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a><span class="fu">library</span>(summarytools)</span>
<span id="cb53-2"><a></a><span class="fu">freq</span>(liver<span class="sc">$</span>LS_US)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Frequencies  
liver$LS_US  
Type: Numeric  

              Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
----------- ------ --------- -------------- --------- --------------
          0    122     28.98          28.98     27.54          27.54
        0.5      4      0.95          29.93      0.90          28.44
          1    295     70.07         100.00     66.59          95.03
       &lt;NA&gt;     22                               4.97         100.00
      Total    443    100.00         100.00    100.00         100.00</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a><span class="fu">freq</span>(liver<span class="sc">$</span>LS_Biopsy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Frequencies  
liver$LS_Biopsy  
Type: Numeric  

              Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
----------- ------ --------- -------------- --------- --------------
          0    124     27.99          27.99     27.99          27.99
        0.5      8      1.81          29.80      1.81          29.80
          1    311     70.20         100.00     70.20         100.00
       &lt;NA&gt;      0                               0.00         100.00
      Total    443    100.00         100.00    100.00         100.00</code></pre>
</div>
</div>
<p>There are 295/421 positive diagnoses for the ultrasound group and 311/443 for the biopsy group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a></a>ptest<span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">295</span>,<span class="dv">311</span>),</span>
<span id="cb57-2"><a></a>          <span class="at">n=</span><span class="fu">c</span>(<span class="dv">443-22</span>,<span class="dv">443</span>),</span>
<span id="cb57-3"><a></a>          <span class="at">conf.level=</span><span class="fl">0.95</span>,</span>
<span id="cb57-4"><a></a>          <span class="at">correct=</span><span class="cn">TRUE</span>)</span>
<span id="cb57-5"><a></a></span>
<span id="cb57-6"><a></a>ptest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(295, 311) out of c(443 - 22, 443)
X-squared = 1.3976e-29, df = 1, p-value = 1
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.06369117  0.06105315
sample estimates:
   prop 1    prop 2 
0.7007126 0.7020316 </code></pre>
</div>
</div>
<p>The resulting 95% confidence interval is (-0.0637, 0.0611). 0 is part of the interval, which means it is a plausible value of the difference in detection rates between the two methods. Hence, it is plausible that the long-run detection rates of the two methods do not differ.</p>
</div>
</div>
</div>
</section>
<section id="exercise-5" class="slide level2">
<h2>Exercise</h2>
<p>In a randomized controlled trial, 23 out of 40 participants who received the treatment reported improvement while 14 out of 35 participants who received the placebo reported improvement.</p>
<div class="panel-tabset">
<ul id="tabset-17" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-17-1">Question</a></li><li><a href="#tabset-17-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-17-1">
<p>Calculate a 99% confidence interval <strong>with and without the continuity correction</strong> for the difference in improvement rate between the treatment and placebo groups.</p>
</div>
<div id="tabset-17-2">
<p>Without continuity correction,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a></a>ptest<span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">23</span>,<span class="dv">14</span>),</span>
<span id="cb59-2"><a></a>          <span class="at">n=</span><span class="fu">c</span>(<span class="dv">40</span>,<span class="dv">35</span>),</span>
<span id="cb59-3"><a></a>          <span class="at">conf.level=</span><span class="fl">0.99</span>,</span>
<span id="cb59-4"><a></a>          <span class="at">correct=</span><span class="cn">FALSE</span>)</span>
<span id="cb59-5"><a></a></span>
<span id="cb59-6"><a></a>ptest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions without continuity correction

data:  c(23, 14) out of c(40, 35)
X-squared = 2.2871, df = 1, p-value = 0.1305
alternative hypothesis: two.sided
99 percent confidence interval:
 -0.1183113  0.4683113
sample estimates:
prop 1 prop 2 
 0.575  0.400 </code></pre>
</div>
</div>
<p>With the continuity correction,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a></a>ptest<span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">23</span>,<span class="dv">14</span>),</span>
<span id="cb61-2"><a></a>          <span class="at">n=</span><span class="fu">c</span>(<span class="dv">40</span>,<span class="dv">35</span>),</span>
<span id="cb61-3"><a></a>          <span class="at">conf.level=</span><span class="fl">0.99</span>,</span>
<span id="cb61-4"><a></a>          <span class="at">correct=</span><span class="cn">TRUE</span>)</span>
<span id="cb61-5"><a></a></span>
<span id="cb61-6"><a></a>ptest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(23, 14) out of c(40, 35)
X-squared = 1.6405, df = 1, p-value = 0.2003
alternative hypothesis: two.sided
99 percent confidence interval:
 -0.145097  0.495097
sample estimates:
prop 1 prop 2 
 0.575  0.400 </code></pre>
</div>
</div>
<p>The resulting 99% confidence interval with the continuity correction is is (-0.1451, 0.4951). 0 is part of the interval, which means it is a plausible value of the difference in improvement rates between the two groups. Hence, it is plausible that the long-run improvement rate due to the treatment does not differ from the placebo.</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Lecture 6 - <a href="https://madfudolig.quarto.pub/introtobiostats/">Back to home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/madfudolig\.quarto\.pub\/introtobiostats");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
            for (let i=0; i<annoteTargets.length; i++) {
              const annoteTarget = annoteTargets[i];
              const targetCell = annoteTarget.getAttribute("data-target-cell");
              const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
              const contentFn = () => {
                const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
                if (content) {
                  const tipContent = content.cloneNode(true);
                  tipContent.classList.add("code-annotation-tip-content");
                  return tipContent.outerHTML;
                }
              }
              const config = {
                allowHTML: true,
                content: contentFn,
                onShow: (instance) => {
                  selectCodeLines(instance.reference);
                  instance.reference.classList.add('code-annotation-active');
                  window.tippy.hideAll();
                },
                onHide: (instance) => {
                  unselectCodeLines();
                  instance.reference.classList.remove('code-annotation-active');
                },
                maxWidth: 300,
                delay: [50, 0],
                duration: [200, 0],
                offset: [5, 10],
                arrow: true,
                appendTo: function(el) {
                  return el.parentElement.parentElement.parentElement;
                },
                interactive: true,
                interactiveBorder: 10,
                theme: 'light-border',
                placement: 'right',
                popperOptions: {
                  modifiers: [
                  {
                    name: 'flip',
                    options: {
                      flipVariations: false, // true by default
                      allowedAutoPlacements: ['right'],
                      fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                    },
                  },
                  {
                    name: 'preventOverflow',
                    options: {
                      mainAxis: false,
                      altAxis: false
                    }
                  }
                  ]        
                }      
              };
              window.tippy(annoteTarget, config); 
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>