{
  "hash": "e5be928e5ec7f38344cf230e01944ead",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Analysis of Variance\"\nsubtitle: Lecture 8\nformat:\n  revealjs:\n    theme: clean.scss\n    scrollable: true\n    footer: \"Lecture 8 - [Back to home](https://madfudolig.quarto.pub/introtobiostats/)\"\n    code-block-bg: true\n    code-block-border-left: \"#31BAE9\"\n    slide-number: true\n    menu: true\n    code-annotations: hover\n    chalkboard: true\n    engine: knitr\n    echo: true\n    code-fold: false\n    \n  pdf: \n    number-sections: true\n    geometry:\n      - landscape\n      - margin=1in\n    include-in-header:\n      text: |\n        \\usepackage{titlesec}\n        \\titleformat{\\section}{\\normalfont\\large\\bfseries}{\\thesection}{1em}{}\n        \\titleformat{\\subsection}{\\normalfont\\large\\bfseries}{\\thesubsection}{1em}{}\n        \\titleformat{\\subsubsection}{\\normalfont\\normalsize\\bfseries}{\\thesubsubsection}{1em}{}\n        \n        % Syntax: \\titlespacing{command}{left-sep}{before-sep}{after-sep}\n        \\titlespacing{\\section}{0pt}{12pt}{12pt}\n        % \\titlespacing{\\subsection}{0pt}{3in}{12pt}\n        \\titlespacing{\\subsubsection}{0pt}{3in}{10pt}\n        \n        % This forces a clearpage before every subsection\n        \\let\\oldsubsection\\subsection\n        \\renewcommand{\\subsection}{\\clearpage\\oldsubsection}\n        \nbibliography: references.bib\n---\n\n# Outline\n\n-   Linear Models\n\n-   Single Factor Analysis of Variance (ANOVA)\n\n    -   Hypotheses\n    -   Test Statistic\n\n-   Two Factor ANOVA\n\n    -   Interaction Term\n\n# Linear Models\n\n## What are Linear Models?\n\nLinear models are very generalized models that allow us to investigate phenomena from many perspectives.\n\n::: callout-note\nIn this course we will focus on three important applications of linear models:\n\n-   Analysis of Variance (ANOVA)\n-   Linear Regression\n-   Correlation\n:::\n\n## Definition of Terms\n\n::: callout-important\nThe dependent variable is also referred to as the response variable, outcome variable, or measured variable.\n:::\n\n::: callout-important\nThe independent variable is also referred to as the explanatory variable, predictor variable, or *factor*\n:::\n\n## General Form of Linear Models\n\nThe general form of the linear model is given by\n\n$$\nY_j = \\beta_0 + \\beta_1X_{1j} + \\beta_2X_{2j} +... + \\beta_k X_{kj} + \\varepsilon_j\n$$\n\n::: callout-important\nThe \\beta terms are coefficients, with $\\beta_0$ known as the intercept of the model. $X_{1j}$ are predictor variables or covariates, also known as confounding variables. These terms constitute a partition that estimates the mean of $Y_j$.\n:::\n\n::: callout-important\nThe term $\\varepsilon_j$ corresponds to the noise term of the model. This term does not contribute to the mean, rather this partition captures the variability in the data.\n:::\n\n# Analysis of Variance (ANOVA)\n\n## Single Factor ANOVA\n\nIn Chapter 7, we compared the statistics of samples from two populations. Often, we want to compare more than two groups.\n\n::: callout-note\nSuppose we want to compare more than two species or more than two treatment groups.\n:::\n\n## Statistical Hypotheses\n\nIn single-factor ANOVAs (also referred to as one-way ANOVAs), we would like to compare **the means of multiple groups**. Suppose we have $k$ groups defined by an explanatory variable. The null and alternative hypotheses can be expressed as:\n\n$$\nH_0: \\mu_1 = \\mu_2 = ... = \\mu_k\n$$\n\n$H_a:$ At least one group mean is not equal to others.\n\n## One-way ANOVA: Linear Model\n\nThe linear model for the ANOVA can be written as:\n\n$$\nY_{ij} = \\mu_{i} + \\varepsilon_{ij}\n$$ where $Y_{ij}$ is the value of the response variable for the $j^{th}$ subject in the $i^{th}$ group, $\\mu_i$ is the group mean of the $i^{th}$ group, and $\\varepsilon_{ij}$ is the error term.\n\n::: callout-note\nThe group mean of the $i^{th}$ group can be decomposed into $\\mu_i = \\mu + \\tau_i$ where $\\mu$ is referred to as the grand mean, and $\\tau_i$ is the treatment effect.\n:::\n\n## Why ANOVA?\n\nWhile it is referred to as an analysis of variance, it can be used to compare group means.\n\n![Compare the purple squares to the yellow squares.](figs/8-anova-squares-graph.png)\n\n::: callout-tip\nWe need to estimate the variability within groups and between groups. If the variability between groups is larger than the variability within groups, then there is evidence that the group means are different from each other.\n:::\n\n## Sum of Squares\n\nThe areas of the squares in the previous slide can be calculated using the *sum of squares*.\n\n::::::: panel-tabset\n### Terms\n\n::: {.callout-note title=\"Group Means\"}\nThe mean of group $i$ with size $n_i$ is expressed as $\\bar{y}_{i\\cdot}$ which can be written as:\n\n$$\n\\bar{y}_{i\\cdot} = \\sum_{j=1}^{n_i}y_{ij}/n_i\n$$\n:::\n\n::: {.callout-note title=\"Overall Mean\"}\nThe overall mean $\\bar{y}_{\\cdot\\cdot}$ can be expressed as:\n\n$$\n\\bar{y}_{\\cdot\\cdot} = \\left(\\frac{1}{N}\\right) \\sum_{i=1}^k\\sum_{j=1}^{n_i}y_{ij}\n$$\n:::\n\nwhere $N$ is the total sample size (sum of all $n_i$).\n\n### Factor Sum of Squares\n\n::: {.callout-note title=\"Sum of Squares due to Factor A\"}\nSuppose the groups are dictated by a factor $A$ with $k$ levels. We define the sum of squares due to the factor $A$ as $SSA$ given by,\n\n$$\nSSA = \\sum_{i=1}^k n_i(y_{i\\cdot} - \\bar{y}_{\\cdot \\cdot})^2\n$$\n\nThis sum of squares measures the variability of the sample means from the overall mean.\n:::\n\n### Error Sum of Squares\n\n::: {.callout-note title=\"Sum of Squares due to Error\"}\nThe sum of squares due to error, denoted as SSE can be expressed as:\n\n$$\nSSE = \\sum_{i=1}^k \\sum_{j=1}^{n_i} (y_{ij} - \\bar{y}_{i\\cdot})^2\n$$\n\nThis sum of squares measures the variability of each measurement to their respective group mean.\n:::\n:::::::\n\n## Total Sum of Squares\n\nThe total sum of squares, $SST$ can then be expressed as:\n\n$$\nSST = SSA + SSE\n$$\n\n## Mean Squares\n\n::: panel-tabset\n\n### Factor Mean Squares\n\n::: {.callout-note title=\"Mean Squares due to Factor A\"} \n\nSuppose the groups are dictated by a factor $A$ with $k$ levels. We define the mean squares of factor $A$ as $MSA$ given by,\n\n$$\nMSA = \\frac{SSA}{k-1}\n$$\n\nThis sum of squares is an estimate of the variance between groups.\n:::\n\n### Error Sum of Squares\n\n::: {.callout-note title=\"Mean Squares due to Error\"}\n\nWe define the mean squares error as $MSE$ as,\n\n$$\nMSE = \\frac{SSE}{N-k}\n$$\n\nwhere $N$ is the total number of samples. \n\n:::\n\n:::\n\n## Variance Ratio\n\nRecall that we want to compare the variability between groups and within groups. We do this by computing the following variance ratio, which we will use as our test statistic.\n\n$$\nVR = F = MSA/MSE\n$$\n\nThis test statistic follows an F-distribution where the numerator degrees of freedom $df_1 = k-1$ and denominator degrees of freedom $df_2 = N-k$.\n\n## ANOVA table\n\nThe Analysis of Variance metrics can be summarized in an ANOVA table:\n\n| Source of Variation | Sum of Squares | Degrees of Freedom | Mean Square | Variance Ratio or F |\n|----|----|----|----|----|\n| Factor A | SSA | (k-1) | MSA = SSA/(k-1) | MSA/MSE |\n| Error | SSE | (N-k) | MSE = SSE/(N-k) |  |\n| Total | SST | (N-1) |  |  |\n\n## `R` implementation\n\nThe rejection region can be determined using the F-statistic. In `R`, we can use the following functions to perform hypothesis testing, estimating linear model coefficients, and estimate group means.\n\n::: panel-tabset\n### `aov()`\n\nThe package `aov(formula,data)` in `R` works with the `summary` function to perform the single-factor ANOVA. For a response variable in column `y` and group variable in column `x` in a data set `df`.\n\n```{.r}\nmod1 <- aov(y~x,data=df)\nsummary(mod1)\n```\n\n::: callout-note\nIt is recommended that the group variable $x$ is expressed as a factor.\n:::\n\n### `lm()` \n\nTo view the estimates of the coefficients of the corresponding linear model, we use `lm(formula,data)` to estimate the linear model. These coefficients can be viewed using the `summary` function.\n\n```{.r}\nmod1 <- lm(y~x,data=df)\nsummary(mod1)\n```\n\n::: callout-note\nIt is recommended that the group variable $x$ is expressed as a factor.\n:::\n\n### `emmeans()`\n\nThe package `emmeans` contains the function `emmeans()` that calculates the group means based on the estimates of the linear models in `lm()`\n\n```{.r}\nlibrary(emmeans)\nmod1 <- lm(y~x,data=df)\nemmeans(mod1,~x)\n```\n\n:::\n\n## Interpretation of Null Hypothesis Rejection\n\nThe rejection of the null hypothesis implies sufficient evidence that not all population means are equal. However, there is no information on which groups have the different means. \n\nFailure to reject the null hypothesis implies insufficient evidence that not all population means are equal.\n\n## Assumptions of ANOVA\n\nANOVA assumes the following:\n\n- The data follows the Gaussian distribution\n- Groups have equal variances\n- Observations are independent of each other\n\n## Effect Size\n\nA commonly reported effect size for ANOVA is the partial eta-squared ($\\eta^2_p$).\n\n$$\n\\eta^2 = \\frac{SSA}{SSA+SSE}\n$$\n\nThis could also be calculated using the `effectsize` function in the `lsr` package in `R`.\n\n:::callout-important\n$\\eta^2_p=0.01$ is considered small, 0.06 is considered medium, and 0.14 is large.\n:::\n\n## Example\n\nConsider the `iris` data set loaded in `R`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --\nv dplyr     1.1.4     v readr     2.1.5\nv forcats   1.0.0     v stringr   1.5.1\nv ggplot2   4.0.0     v tibble    3.3.0\nv lubridate 1.9.4     v tidyr     1.3.1\nv purrr     1.1.0     \n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\ni Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 150\nColumns: 5\n$ Sepal.Length <dbl> 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.~\n$ Sepal.Width  <dbl> 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.~\n$ Petal.Length <dbl> 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.~\n$ Petal.Width  <dbl> 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.~\n$ Species      <fct> setosa, setosa, setosa, setosa, setosa, setosa, setosa, s~\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### Question\nUse ANOVA to test if three species have different population average sepal length. Use a significance level of 0.05. Calculate the partial eta-squared value for the species effect.\n\n### Answer\n\nThere are three species (\"setosa\", \"versicolor\", and \"virginica\"). The hypotheses are $H_0:$ The population average sepal length is equal for all three species. and $H_a:$ At least one population has a different average sepal length.\n\nWe now implement the ANOVA using `R`. To calculate the ANOVA table, we use `aov()`\n\n```{.r}\ninstall.packages(\"lsr\")\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lsr)\nmod_aov <-aov(Sepal.Length~Species,data=iris)\nsummary(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nSpecies       2  63.21  31.606   119.3 <2e-16 ***\nResiduals   147  38.96   0.265                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\netaSquared(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           eta.sq eta.sq.part\nSpecies 0.6187057   0.6187057\n```\n\n\n:::\n:::\n\nThe p-value is <2e-16, which is less than 0.05. We reject the null hypothesis and therefore there is sufficient evidence that at least one species has a different population average sepal length compared to the others. The effect size is 0.6187057 \n\nWe examine the group means to see how much the group means differ using `emmeans()`. To use `emmeans()`, we need to create a linear model for the problem using `lm()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install emmeans first if not installed yet: \n#install.packages(\"emmeans\")\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code}\nmod_lm <-lm(Sepal.Length~Species,data=iris)\nsummary(mod_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Sepal.Length ~ Species, data = iris)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.6880 -0.3285 -0.0060  0.3120  1.3120 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         5.0060     0.0728  68.762  < 2e-16 ***\nSpeciesversicolor   0.9300     0.1030   9.033 8.77e-16 ***\nSpeciesvirginica    1.5820     0.1030  15.366  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.5148 on 147 degrees of freedom\nMultiple R-squared:  0.6187,\tAdjusted R-squared:  0.6135 \nF-statistic: 119.3 on 2 and 147 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nemmeans(mod_lm,~Species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Species    emmean     SE  df lower.CL upper.CL\n setosa       5.01 0.0728 147     4.86     5.15\n versicolor   5.94 0.0728 147     5.79     6.08\n virginica    6.59 0.0728 147     6.44     6.73\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\nWe see that Setosa has the lowest average sepal length and Virginica has the highest average sepal length.\n\n:::\n\n## Exercise\n\nThe data set `penguins` from the `datasets` package in `R` includes data on adult penguins covering three species found on three islands in the Palmer Archipelago, Antarctica.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(datasets)\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 344\nColumns: 8\n$ species     <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Ad~\n$ island      <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Tor~\n$ bill_len    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, 42.0, ~\n$ bill_dep    <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, 20.2, ~\n$ flipper_len <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186, 180,~\n$ body_mass   <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, 4250, ~\n$ sex         <fct> male, female, female, NA, female, male, female, male, NA, ~\n$ year        <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007~\n```\n\n\n:::\n\n```{.r .cell-code}\n# disregard missing data:\n\npenguins <- drop_na(penguins,bill_len)\n```\n:::\n\n\n::: panel-tabset\n### Question\n\nTest for a difference in average bill length (bill_len) between the species. Use a significance level of 0.05. Calculate the partial eta-squared for the species effect.\n\n### Answer\n\nThe hypotheses are $H_0:$ The population average bill length is equal for all three species. and $H_a:$ At least one population has a different average bill length.\n\nWe now implement the ANOVA using `R`. To calculate the ANOVA table, we use `aov()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lsr)\nmod_aov <-aov(bill_len~species,data=penguins)\nsummary(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nspecies       2   7194    3597   410.6 <2e-16 ***\nResiduals   339   2970       9                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\netaSquared(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           eta.sq eta.sq.part\nspecies 0.7078091   0.7078091\n```\n\n\n:::\n:::\n\nThe p-value is <2e-16, which is less than 0.05. We reject the null hypothesis and therefore there is sufficient evidence that at least one species has a different population average bill length compared to the others. The effect size is 0.7078091 \n\nWe examine the group means to see how much the group means differ using `emmeans()`. To use `emmeans()`, we need to create a linear model for the problem using `lm()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install emmeans first if not installed yet: \n#install.packages(\"emmeans\")\nlibrary(emmeans)\n\nmod_lm <-lm(bill_len~species,data=penguins)\nsummary(mod_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_len ~ species, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-7.9338 -2.2049  0.0086  2.0662 12.0951 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       38.7914     0.2409  161.05   <2e-16 ***\nspeciesChinstrap  10.0424     0.4323   23.23   <2e-16 ***\nspeciesGentoo      8.7135     0.3595   24.24   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.96 on 339 degrees of freedom\nMultiple R-squared:  0.7078,\tAdjusted R-squared:  0.7061 \nF-statistic: 410.6 on 2 and 339 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nemmeans(mod_lm,~species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n species   emmean    SE  df lower.CL upper.CL\n Adelie      38.8 0.241 339     38.3     39.3\n Chinstrap   48.8 0.359 339     48.1     49.5\n Gentoo      47.5 0.267 339     47.0     48.0\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\nWe see that Adelie has the shortest average bill length, while Chinstrap and Gentoo have comparable average bill lengths.\n:::\n\n## Pairwise Comparisons and Post-hoc Analysis\n\nSuppose we want to examine the means further to determine which groups are different when compared pairwise, i.e. A vs. B, A vs. C, B vs. C, etc. after rejecting the null hypothesis in ANOVA. This analysis is considered a post-hoc analysis.\n\n::: callout-warning\nPerforming multiple pairwise t-tests and making inferences simultaneously can lead to multiplicity, which increases the chance of making a Type I error. We have to control for this when performing comparisons across the groups.\n:::\n\n## Multiplicity corrections\n\nTwo of the popular corrections to account for the Type I error inflation are:\n\n- Bonferroni correction: for planned comparisons, i.e. These comparisons are planned before the study was implemented.\n- Tukey correction: for post-hoc comparisons, i.e. Comparisons done to examine which groups are different from each other after the rejection of an ANOVA hypothesis.\n\n## `R` implementation\n\nThe function `contrast` is applied to the `emmeans` function to estimate pairwise comparisons. Using previous examples,\n\n```{.r}\nlibrary(emmeans)\nmod1 <- lm(y~x,data=df)\nem_mod1 <- emmeans(mod1,~x)\ncontrast(em_mod1,method=\"pairwise\",adjust=\"tukey\")\n```\n\n::: callout-note\nThe Tukey correction can be applied by setting `adjust=tukey`, while the Bonferroni correction can be applied by setting `adjust=\"bon\"`.\n:::\n\n\n\n## Example\n\nConsider the `iris` data set loaded in `R`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nglimpse(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 150\nColumns: 5\n$ Sepal.Length <dbl> 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.~\n$ Sepal.Width  <dbl> 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.~\n$ Petal.Length <dbl> 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.~\n$ Petal.Width  <dbl> 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.~\n$ Species      <fct> setosa, setosa, setosa, setosa, setosa, setosa, setosa, s~\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n\n\n### Question\nRecall that you rejected the null hypothesis after performing ANOVA. Perform pairwise comparisons to determine which groups have different sepal lengths. Use a significance level of 0.05 and the Tukey correction.\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_lm <- lm(Sepal.Length~Species,data=iris)\nem_mod_lm <- emmeans(mod_lm,~Species)\ncontrast(em_mod_lm,method=\"pairwise\",adjust=\"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast               estimate    SE  df t.ratio p.value\n setosa - versicolor      -0.930 0.103 147  -9.033  <.0001\n setosa - virginica       -1.582 0.103 147 -15.366  <.0001\n versicolor - virginica   -0.652 0.103 147  -6.333  <.0001\n\nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\nThe p-values are all less than 0.0001, which means we have sufficient evidence that all means are different from each other. Setosa sepal length was estimated to be 0.930 units lower than Versicolor and 1.58 units lower than Virginica. Versicolor sepal length was estimated to be 0.65 units lower than Virginica.\n:::\n\n## Exercise\n\nThe data set `penguins` from the `datasets` package in `R` includes data on adult penguins covering three species found on three islands in the Palmer Archipelago, Antarctica.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(datasets)\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 342\nColumns: 8\n$ species     <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Ad~\n$ island      <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgersen, Tor~\n$ bill_len    <dbl> 39.1, 39.5, 40.3, 36.7, 39.3, 38.9, 39.2, 34.1, 42.0, 37.8~\n$ bill_dep    <dbl> 18.7, 17.4, 18.0, 19.3, 20.6, 17.8, 19.6, 18.1, 20.2, 17.1~\n$ flipper_len <int> 181, 186, 195, 193, 190, 181, 195, 193, 190, 186, 180, 182~\n$ body_mass   <int> 3750, 3800, 3250, 3450, 3650, 3625, 4675, 3475, 4250, 3300~\n$ sex         <fct> male, female, female, female, male, female, male, NA, NA, ~\n$ year        <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007~\n```\n\n\n:::\n\n```{.r .cell-code}\n# disregard missing data:\n\npenguins <- drop_na(penguins,bill_len)\n```\n:::\n\n\n::: panel-tabset\n### Question\n\nPerform pairwise comparisons of average bill length (in mm) across the three species. Use the Bonferroni correction and a significance level of 0.001.\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install emmeans first if not installed yet: \n#install.packages(\"emmeans\")\nlibrary(emmeans)\n\nmod_lm <-lm(bill_len~species,data=penguins)\n\nem_mod_lm <- emmeans(mod_lm,~species)\ncontrast(em_mod_lm,method=\"pairwise\",adjust=\"bon\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast           estimate    SE  df t.ratio p.value\n Adelie - Chinstrap   -10.04 0.432 339 -23.232  <.0001\n Adelie - Gentoo       -8.71 0.360 339 -24.237  <.0001\n Chinstrap - Gentoo     1.33 0.447 339   2.971  0.0095\n\nP value adjustment: bonferroni method for 3 tests \n```\n\n\n:::\n:::\n\nAt significance level of 0.001, we have sufficient evidence that the average bill length of Adelie penguins is different from Chinstrap and Gentoo penguins by 10 mm and 8.7 mm, respectively. The difference between the average bill length of Chinstrap and Gentoo is 1.33, where we have insufficient evidence of a difference with p=0.0095.\n:::\n\n## Two-Way ANOVA\n\nSuppose we want to study the effect of two factors.\n\n::: callout-note\nSuppose we want to investigate the interplay of pain relief and blood thinners on patient comfort level, We can perform separate analyses using single factor (or one-way) ANOVAs, but it will fail to capture the interplay between the two groups.\n:::\n\n## Interaction Effect\n\nAside from the factor effects, we have to consider the interaction effect.\n\n::: callout-note\nThe interaction effect is defined as the difference in effect of one factor between the levels of the other factor. Consider two factors $A$ (levels: $A_1$ and $A_2$) and $B$ (levels: $B_1$ and $B_2$). The interaction effect can be interpreted as:\n\n$$\n\\mu_{A1B1} - \\mu_{A1B2} -(\\mu_{A2B1} - \\mu_{A2B2})\n$$\n\n:::\n\n## Linear Model\n\nThe linear model of the two-way ANOVA can be written as:\n\n$$\nY_{ijk} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij} + \\varepsilon_{ijk}\n$$\nwhere $\\alpha$ is the main effect of Factor A, $\\beta$ is the main effect of Factor B, and $(\\alpha\\beta)$ is the interaction effect between Factors A and B.\n\n## ANOVA Table\n\nIf Factor A has $a$ levels and Factor B has $b$ levels and total sample size $N$, the ANOVA table can be expressed as:\n\n| Source of Variation | Sum of Squares | Degrees of Freedom | Mean Square | Variance Ratio or F |\n|----|----|----|----|----|\n| Factor A | SSA | (a-1) | MSA = SSA/(a-1) | MSA/MSE |\n| Factor B | SSB | (b-1) | MSA = SSB/(b-1) | MSB/MSE |\n| Interaction A*B | SSAB | (a-1)(b-1) | MSA = SSAB/((a-1)(b-1)) | MSAB/MSE |\n| Error | SSE | N-ab | MSE = SSE/(N-k) |  |\n| Total | SST | N-1 |  |  |\n\n## Analysis\n\nHere is a guide on how to perform a two-way ANOVA:\n\n- Check if we have sufficient evidence of an interaction effect.\n\n::: callout-warning\nIf there is evidence of an interaction effect, the main effects are NOT interpretable. You must compare the levels of A under all levels of B and vice versa. Interaction effects are slightly different from effect modification analysis, where we are only concerned with the effect of one factor in the levels of the other, e.g. effect of drugs for all levels of sex.\n:::\n\n::: callout-note\nIf there is no evidence of an interaction effect, the main effects can be interpreted similar to the result of a one-way/single-factor ANOVA.\n:::\n\n## `R` implementation\n\nThe same functions used in the single factor ANOVA are used to perform a two-way ANOVA. However, the model specification is slightly different.\n\n```{.r}\nlibrary(emmeans)\nmod1 <- lm(y~A+B+A:B,data=df)\nemmeans(mod1,~A*B)\n```\n\n## Example\n\nThe data set `lec8_example.csv` includes simulated data from a study that randomly sampled 20 individuals with and without family history of hypertension. These individuals were randomly assigned to two treatments for hypertension, A and B. The systolic blood pressure was measured for each participant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsystolic <- read.csv(\"lec8_example.csv\")\nglimpse(systolic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 40\nColumns: 3\n$ Treatment <chr> \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"B\", \"B\", ~\n$ History   <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes~\n$ Systolic  <int> 141, 137, 136, 131, 133, 141, 129, 134, 134, 141, 132, 127, ~\n```\n\n\n:::\n:::\n\n\n\n::: panel-tabset\n### Question\nTest for an interaction effect between family history and hypertension. Provide the estimated group means for each group.\n\n### Answer\n\nThe null hypothesis is $H_0:$ there is no interaction between family history and hypertension and the alternative hypothesis is $H_a$: there is an interaction between family history and hypertension.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_aov <- aov(Systolic~Treatment + History + Treatment:History,data=systolic)\nsummary(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Df Sum Sq Mean Sq F value   Pr(>F)    \nTreatment          1  330.6   330.6   13.27 0.000841 ***\nHistory            1 1729.2  1729.2   69.42  6.4e-10 ***\nTreatment:History  1  442.2   442.2   17.75 0.000161 ***\nResiduals         36  896.7    24.9                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\netaSquared(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     eta.sq eta.sq.part\nTreatment         0.0972777   0.2693867\nHistory           0.5087789   0.6585203\nTreatment:History 0.1301131   0.3302836\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(emmeans)\nmod1 <- lm(Systolic~Treatment + History + Treatment:History,data=systolic)\nemmeans(mod1,~Treatment:History)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Treatment History emmean   SE df lower.CL upper.CL\n A         No         116 1.58 36      113      119\n B         No         117 1.58 36      114      120\n A         Yes        136 1.58 36      132      139\n B         Yes        123 1.58 36      120      127\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(emmeans(mod1,~Treatment|History))\n```\n\n::: {.cell-output-display}\n![](lecture8_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\nThere is evidence of an interaction between treatment and family history ($\\eta^2_p$=0.33,p=0.0002). Based on the calculated means, the difference between the treatments was higher for those with family history of hypertension compared to those without.\n:::\n\n## Exercise\n\nThe data set `COVID-Zinc-AscorbicAcid.csv` contains data from a clinical trial that tested the efficacy of using high doses of zinc and/or ascorbic acid (vitamin C) on the recovery time for COVID-19. They studied a number of outcome variables, including the time to 50% reduction in symptoms. Those marked with `1` for Zinc and Ascorbic Acid received the treatment, while those marked with `-1` did not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid <- read.csv(\"COVID-Zinc-AscorbicAcid.csv\")\nglimpse(covid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 20\nColumns: 4\n$ obs                     <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,~\n$ AscorbicAcid            <int> -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, ~\n$ Zinc                    <int> -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, -1, -1, -1,~\n$ DaysUntil50PctReduction <dbl> 2.6, 4.4, 14.1, 6.0, 6.4, 13.3, 8.0, 0.8, 3.2,~\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### Question\n\n- Test for an interaction between the Ascorbic Acid and Zinc factors.\n- Is there evidence of efficacy of the two treatments?\n\n### Answer\n\nThe null hypothesis is $H_0:$ there is no interaction between Ascorbic Acid and Zinc treatments and the alternative hypothesis is $H_a$: there is an interaction between between Ascorbic Acid and Zinc treatments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_aov <- aov(DaysUntil50PctReduction~AscorbicAcid + Zinc + AscorbicAcid:Zinc,data=covid)\nsummary(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Df Sum Sq Mean Sq F value Pr(>F)\nAscorbicAcid       1   3.28   3.281   0.192  0.667\nZinc               1   0.84   0.840   0.049  0.827\nAscorbicAcid:Zinc  1   0.76   0.760   0.045  0.836\nResiduals         16 273.17  17.073               \n```\n\n\n:::\n\n```{.r .cell-code}\netaSquared(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       eta.sq eta.sq.part\nAscorbicAcid      0.011798259 0.011866586\nZinc              0.003022843 0.003067423\nAscorbicAcid:Zinc 0.002735125 0.002776272\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(emmeans)\nmod1 <- lm(DaysUntil50PctReduction~AscorbicAcid + Zinc + AscorbicAcid:Zinc,data=covid)\nemmeans(mod1,~AscorbicAcid:Zinc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n AscorbicAcid Zinc emmean   SE df lower.CL upper.CL\n           -1   -1   6.70 1.85 16     2.78    10.62\n            1   -1   5.50 1.85 16     1.58     9.42\n           -1    1   5.90 1.85 16     1.98     9.82\n            1    1   5.48 1.85 16     1.56     9.40\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(emmeans(mod1,~AscorbicAcid|Zinc))\n```\n\n::: {.cell-output-display}\n![](lecture8_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: callout-tip\nIf the `plot(emmeans(mod1,~AscorbicAcid|Zinc))` outputs an error, you might need to reinstall `ggplot2`. Try reinstalling this package using`install.packages(\"ggplot2\")` or `install.packages(\"tidyverse\")` and reload it with `library(tidyverse)`.\n:::\n\n\nThere is no evidence of an interaction between Ascorbic Acid and Zinc ($\\eta^2_p$=0, p=0.84). There is also no evidence of efficacy for Ascorbic Acid ($\\eta^2_p$=0.01, p=0.67) and Zinc ($\\eta^2_p$=0, p=0.83)\n:::",
    "supporting": [
      "lecture8_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}