{
  "hash": "b665b4846fb0c99f8b81c5db88bd59a2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Interval Estimation\"\nsubtitle: Lecture 6\nformat:\n  revealjs:\n    theme: clean.scss\n    scrollable: true\n    footer: \"Lecture 6 - [Back to home](https://madfudolig.quarto.pub/introtobiostats/)\"\n    code-block-bg: true\n    code-block-border-left: \"#31BAE9\"\n    slide-number: true\n    menu: true\n    code-annotations: hover\n    chalkboard: true\n    engine: knitr\n    echo: true\n    code-fold: false\n    \n  pdf: \n    number-sections: true\n    engine: knitr\nbibliography: references.bib\n---\n\n# Outline\n\n- Estimation: Confidence Intervals\n\n- The t-distribution\n\n- Confidence Intervals for different parameters:\n\n  - Population Mean\n  - Difference Between Two Population Means\n  - Population Proportion\n  - Diffrence Between Two Population Proportions\n\n# Estimation\n\n## Statistical Inference\n\n::: callout-note\n**Statistical inference** is the procedure by which we reach a conclusion about a population on the basis of the information contained in a sample drawn from that population.\n:::\n\n::: callout-important\nThe process of estimation entails calculating some statistic from the sample that is offered as an approximation of the corresponding parameter of the population from which the sample was drawn.\n:::\n\n## Point Estimation vs. Interval Estimation\n\n::: {.callout-note title=\"Point Estimation\"}\nPoint estimation is the process of finding a single number to use as our best guess for the value of an unknown population parameter. Point estimates do not provide a measure of uncertainty.\n:::\n\n\n::: {.callout-note title=\"Interval Estimation\"}\nInterval estimation involves estimating two numerical values that define a range of values that, with a specified degree of confidence, most likely includes the parameter being estimated.\n:::\n\n## Point Estimation: Unbiased Estimators\n\n::: callout-note\nThe single computed value has been referred to as an estimate. On the other hand, the rule that tells us how to compute this estimate is referred to as an estimator.\n:::\n\n::: {.callout-important title=\"Unbiasedness\"}\nAn estimator of a parameter $\\Theta$, $T$, is said to be an unbiased estimator of $\\Theta$ if $E(T)=\\Theta$. AN example of an unbiased estimator is the sample mean. The sample mean $\\bar{X}$ is an unbiased estimator of the population mean.\n:::\n\n## Sampled vs. Target Populations\n\n::: {.callout-note title=\"Target Population\"}\nThe target population is the population about which one wishes to make an inference.\n:::\n\n\n::: {.callout-note title=\"Sampled Population\"}\nThe sampled population is the population from which one actually draws a sample.\n:::\n\n::: callout-warning\nIf the sampled population and the target population are different, the researcher can reach conclusions about the target population only on the basis of nonstatistical considerations. Estimation from the sampled population could lead to biased estimates.\n:::\n\n## Random vs. Convenience Sampling\n\nIn most examples in this class, we assume that the data was collected from random samples. However, it is impossible or impractical to use truly random samples.\n\n\n::: {.callout-note title=\"Convenience sampling\"}\nConvenience sampling involves sampling through volunteerism or readily available subjects to record data. While collecting data using convenience sampling is easy, the results might not be generalizable to the target population.\n:::\n\n## Interval Estimation: Confidence Intervals\n\nThere are many variants of interval estimation methods that can be used. One of the more popular interval estimates is the **confidence interval**.\n\n::: {.callout-important title=\"Confidence Interval\"}\nA confidence interval is a random interval that will contain the true value of a parameter with probability $1-\\alpha$. The value $1-\\alpha$ is called the **confidence level** of the interval.\n:::\n\n::: callout-important\nThe confidence interval provides all plausible values of the parameters. The parameter itself is treated as fixed, while the endpoints of the confidence interval are treated as random variables. The endpoints are random because it depends on the data collected.\n:::\n\n::: callout-warning\nThe viewpoint for making a probability statement must be **before** the data are collected, not **after**. \n:::\n\n## Confidence Intervals\n\nFor the following tabs, supposed that the 95% confidence interval for the population mean, $\\mu$, was calculated to be the interval (80,100).\n\n::: panel-tabset\n\n### Misconception 1\n\n::: {.callout-warning title=\"Misconception 1\"}\nMisconception 1: $P(80 < \\mu < 100) = 0.95$\n:::\n\nThis is incorrect. The parameter $\\mu$ is not random, hence there shouldn't be a probability assigned to it. 80 and 100 are also not random because we have already measured them. Either the interval contains the true value of $\\mu$ or not. Hence, the probability interpretation does not make any sense.\n\n### Misconception 2\n\n::: {.callout-warning title=\"Misconception 2\"}\nMisconception 2: 95% of the population lies in the interval (80,100).\n:::\n\nThe confidence interval is for the population mean, not the set of all data values from the population. A confidence interval for the mean will often include only a small fraction of the population.\n\n:::\n\n## Interpretation of Confidence Intervals\n\nThe confidence level is pertaining to the method that we calculated, not the particular interval. In the long run (or infinite repeated sampling), around 95% of the confidence intervals calculated will include $\\mu$.\n\n::: callout-important\nSince our method works 95% of the time, we believe that $\\mu$ is in our 95% confidence interval. We don't have the time and means to calculate all confidence intervals.\n:::\n\n\n# Confidence Intervals\n\n## Confidence Interval Form\n\nThe confidence intervals in this chapter will follow the form:\n\n$$\nestimate \\pm reliability~coefficient*standard~error\n$$\n\n\n\n## Confidence Intervals for Population Means\n\nWe can estimate the population mean by using the mean of a representative sample from the population. \n\n::: callout-warning\nThe method differs for cases with known and unknown population variance. Some approximations can be done when there is a large sample size.\n:::\n\n## CI for Mean: Known Population Variance\n\nCases in which population variances are known are rare. The best example of measurements with known population variances are standardized scales. \n\n::: callout-note\nThe Wechsler Adult Intelligence Scale (WAIS) maintains a standard deviation of 15 points for its full scale IQ scores.\n:::\n\nFor a known population variance $\\sigma^2$, sample mean $\\bar{x}$, and sample size $n$, the 95% confidence limits for the $(1-\\alpha)%$ can be calculated using the following formula:\n\n$$\n\\bar{x} \\pm z_{1-\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}\n$$\n\n## CI for Mean: Notes\n\nConfidence intervals are often written in parentheses notation as such:\n\n$$\n\\left(\\bar{x} - z_{1-\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}, \\bar{x} + z_{1-\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}\\right)\n$$\n\n$z_{1-\\alpha/2}$ is referred to as the reliability coefficient and defined as the following:\n\n$$\nP(Z \\leq z_{1-\\alpha/2}) = 1-\\alpha/2\n$$\n\n::: callout-tip\nRecall that $Z$ follows the standard normal distribution. $z_{1-\\alpha/2}$ can be calculated using  `qnorm(1-alpha/2,mean=0,sd=1).` For a 95% confidence interval, $\\alpha = 0.05$, then it follows that $1-\\alpha/2 = 1-0.05/2 = 0.975$. Therefore, the reliability coefficient for a 95% confidence interval can be calculated as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha=0.05\nqnorm(1-alpha/2,mean=0,sd=1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n:::\n\n:::\n\n## Example\n\nThe file `lec6example.csv` contains simulated values from a normal distribution with a variance of 4. \n\n::: panel-tabset\n\n### Question\n\nCreate a 95% confidence interval for the population mean. Is 1 a plausible value for the population mean?\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# setwd(\"where your file is\")\nexample <- read.csv(\"datasets/lec6example.csv\")\nsdpop <- sqrt(4)\n```\n:::\n\nWe need to calculate the sample mean of the `Sims` column, the sample size, and the reliability coefficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- mean(example$Sims)\nsampsize <- nrow(example) # <1>\nalpha <- 1-0.95\nrelcoeff <- qnorm(1-alpha/2,mean = 0, sd=1) #<2>\n```\n:::\n\n1. `nrow()` calculates the number of rows of the data frame. If dealing with a singular vector, you can use `length()`. `nrow(example)` will yield the same answer as `length(example$Sims)`.\n\n\nWe can now calculate the 95% confidence interval limits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlower <- xbar - relcoeff*sdpop/sqrt(sampsize)\nupper <- xbar + relcoeff*sdpop/sqrt(sampsize)\nlower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6637448\n```\n\n\n:::\n\n```{.r .cell-code}\nupper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.303866\n```\n\n\n:::\n:::\n\nThe resulting 95% confidence interval is (0.66, 1.3). Since 1 is in the confidence interval, then we can claim that 1 is a plausible value for the population mean.\n\n:::\n\n## Exercise\n\nConsider the sleep health data uploaded on Canvas as `SleepHealthData.csv`. Suppose that in the population that this sample represents, the variance of the sleep duration is 0.5.\n\n::: panel-tabset\n### Question \n\nCalculate the 95% confidence interval for the average sleep duration (`sleep_duration`) in the population this sample represents. Is 7 hours a plausible value for the average sleep distribution of the population?\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep <- read.csv(\"SleepHealthData.csv\")\nsdpop <- sqrt(0.5)\nxbar <- mean(sleep$sleep_duration)\nsampsize <- nrow(sleep)\nalpha <- 1-0.95\nrelcoeff <- qnorm(1-alpha/2) \n# not specifying the mean and sd in qnorm assumes standard normal\n\nlower <- xbar - relcoeff*sdpop/sqrt(sampsize)\nlower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.060422\n```\n\n\n:::\n\n```{.r .cell-code}\nupper <- xbar + relcoeff*sdpop/sqrt(sampsize)\nupper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.203749\n```\n\n\n:::\n:::\n\n\nThe 95% confidence interval is (7.06,7.2). 7 is not a plausible value for the average sleep distribution of the population.\n:::\n\n## Precision\n\nThe precision of an interval estimate is related to its width. \n\n::: callout-note\nThe precision, also known as the **margin of error**, can be expressed as the product of the reliability coefficient and the standard error.\n:::\n\nFor the case of the population mean with known population variance,\n\n$$\nprecision = z_{1-\\alpha/2}* \\frac{\\sigma}{\\sqrt{n}} = \\frac{upper-lower}{2}\n$$\n\n::: callout-note\nBecause of the symmetry of the confidence interval, the precision is half the width of the confidence interval.\n:::\n\n## CI for Mean: Unknown Population Variance\n\nIt is more common to not know the population variance when estimating the population mean. Because of this, we are inclined to use the next best thing: an estimate of the population variance from the collected sample. This estimate is the **sample variance**\n\n::: callout-warning\nUsing an approximate value for the population variance implies that our standardized statistic **might not** follow the standard normal distribution. We need a new distribution to calculate reliability coefficients for these confidence intervals.\n:::\n\n## The Student's t-distribution\n\nThe $t$ distribution is symmetric and bell-shaped like the normal distribution, but has heavier tails.\n\n::: callout-note\nHeavier tails mean that the distribution is more likely to produce values that fall farther from the mean compared to the normal distribution. The heavier tails account for the extra uncertainty introduced by using the sample variance to estimate the population variance.\n:::\n\n::: callout-important\nThe t-distribution is defined by the degrees of freedom denoted by $\\nu$ or `df`, and specific t-distributions can be written as $t_{\\nu}$.\n:::\n\n## The t distribution: `R`\n\nThe `R` syntax for the t-distribution with degrees of freedom `df` consists of the following functions:\n\n- PDF: `dt(x,df)`\n- CDF: `pt(x,df)`\n- Quantile: `qt(x,df)`\n- Generate/Simulate `n` t-distribution points: `rt(n,df)`\n\n## CI for Mean: Unknown Population Variance\n\nWhen the population variance is unknown OR the sample from a normally distributed population has a low sample size, the $(1-\\alpha)*100%$ confidence interval can be calculated using the following formula:\n\n$$\n\\bar{x} \\pm t_{\\nu,1-\\alpha/2} \\frac{s}{\\sqrt{n}}\n$$\n\n::: callout-important\n\n$s$ is the sample standard deviation $t_{\\nu,1-\\alpha/2}$ is defined as $P(t<t_{\\nu,1-\\alpha/2}) = 1-\\alpha/2$. The degrees of freedom $\\nu$ can be calculated as $\\nu=n-1$. \n\n:::\n\nThe 95% confidence interval can be written as:\n\n$$\n\\left(\\bar{x} - t_{\\nu,1-\\alpha/2} \\frac{s}{\\sqrt{n}}, \\bar{x} + t_{\\nu,1-\\alpha/2} \\frac{s}{\\sqrt{n}}\\right)\n$$\n\n## Precision\n\nThe precision of an interval estimate is related to its width. \n\n::: callout-note\nThe precision, also known as the **margin of error**, can be expressed as the product of the reliability coefficient and the standard error.\n:::\n\nFor the case of the population mean with unknown population variance,\n\n$$\nprecision = t_{\\nu,1-\\alpha/2} \\frac{s}{\\sqrt{n}}= \\frac{upper-lower}{2}\n$$\n\n::: callout-note\nBecause of the symmetry of the confidence interval, the precision is half the width of the confidence interval.\n:::\n\n\n\n## Example\n\nThe file `lec6example.csv` contains simulated values from a normal distribution. \n\n::: panel-tabset\n\n### Question\n\nSupposed the population variance is unknown. Create a 95% confidence interval for the population mean. Is 1 a plausible value for the population mean?\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# setwd(\"where your file is\")\nexample <- read.csv(\"datasets/lec6example.csv\")\n```\n:::\n\nWe need to calculate the sample mean of the `Sims` column, the sample size, and the reliability coefficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- mean(example$Sims)\nsampsize <- nrow(example) # <1>\nstdev <- sd(example$Sims) # <2>\ndf <- sampsize-1 #<3>\nalpha <- 1-0.95\nrelcoeff <- qt(p=1-alpha/2,df=df) \n```\n:::\n\n1. `nrow()` calculates the number of rows of the data frame. If dealing with a singular vector, you can use `length()`. `nrow(example)` will yield the same answer as `length(example$Sims)`.\n2. We are calculating the sample variance using `sd()`.\n3. Degrees of freedom `df = n-1`.\n\n\nWe can now calculate the 95% confidence interval limits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlower <- xbar - relcoeff*stdev/sqrt(sampsize)\nupper <- xbar + relcoeff*stdev/sqrt(sampsize)\nlower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6642442\n```\n\n\n:::\n\n```{.r .cell-code}\nupper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.303367\n```\n\n\n:::\n:::\n\nThe resulting 95% confidence interval is (0.66, 1.3). Since 1 is in the confidence interval, then we can claim that 1 is a plausible value for the population mean.\n\n:::\n\n## Exercise\n\nConsider the sleep health data uploaded on Canvas as `SleepHealthData.csv`. \n\n::: panel-tabset\n### Question \n\nCalculate the **99%** confidence interval for the average heart rate (`heart_rate`) in bpm in the population this sample represents. Is 65 bpm a plausible value for the average sleep distribution of the population? Calculate the margin of error.\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep <- read.csv(\"SleepHealthData.csv\")\nsdpop <- sd(sleep$heart_rate)\nxbar <- mean(sleep$heart_rate)\nsampsize <- nrow(sleep)\nalpha <- 1-0.99\nrelcoeff <- qt(p=1-alpha/2,df=sampsize-1) \n# not specifying the mean and sd in qnorm assumes standard normal\n\nlower <- xbar - relcoeff*sdpop/sqrt(sampsize)\nlower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 69.6121\n```\n\n\n:::\n\n```{.r .cell-code}\nupper <- xbar + relcoeff*sdpop/sqrt(sampsize)\nupper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70.71945\n```\n\n\n:::\n:::\n\n\nThe 99% confidence interval is (69.61,70.72). 65 is not a plausible value for the average heart rate of the population.\n\nThe margin of error can be calculated as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelcoeff*sdpop/sqrt(sampsize)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5536753\n```\n\n\n:::\n\n```{.r .cell-code}\n(upper-lower)/2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5536753\n```\n\n\n:::\n:::\n\n\n:::\n\n## Confidence Interval for Population Proportions\n\nMany questions of interest to the health worker relate to population proportions. \n\n::: callout-note\nSome questions could be:\n\n- What is the recovery rate of patients for a particular type of treatment?\n- What is the prevalence rate of a disease?\n- What proportion of medical providers agree with current health recommendations?\n:::\n\n## CI: Population Proportions\n\nFor a sample of size $n$ and sample proportion $\\hat{p}$, the $100(1-\\alpha)$% confidence interval for the population proportion $\\pi$ is given by:\n\n$$\n\\hat{p} \\pm z_{1-\\alpha/2} \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}\n$$\n\nSimilar to the CI for means, $z_{1-\\alpha/2}$ is defined as $P(Z \\leq z_{1-\\alpha/2}) = 1-\\alpha/2$.\n\n\n::: callout-important\nThe use of $z_{1-\\alpha/2}$ can be justified using the central limit theorem (CLT). The most common guideline for the CLT to apply to proportions is that $n\\pi$ and $n(1-\\pi)$ are both greater than five.\n:::\n\nThe CI would then be reported as:\n\n$$\n\\left(\\hat{p} - z_{1-\\alpha/2} \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}},\\hat{p} + z_{1-\\alpha/2} \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}} \\right)\n$$\n\n## Example\n\nThe data set `Liver_Steatosis.csv` comes from a retrospective cohort study to estimate the prevalence of liver steatosis (fatty liver disease) in those who had bariatric surgery ([Wu et al, 2012](https://pubmed.ncbi.nlm.nih.gov/21901286/)). The data set also includes other covariates and comorbidities.\n\n::: panel-tabset\n\n### Question\nOne of the comorbidities studied was history of metabolic syndrome (1=Yes, 2=No, `NA` = missing). Calculate a 95% confidence interval for the prevalence of metabolic syndrome based on the data. Only consider **non-missing data** in your analysis.\n\n::: callout-warning\nThis data set was collected from patients who had bariatric surgery at the Cleveland Clinic between 2005 and 2009 and underwent liver biopsy. Is this result generalizable to all US adults who have had bariatric surgery? \n:::\n\n### Answer\n\nWe need to calculate the proportion of patients reported to have metabolic syndrome. \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(summarytools)\nliver <- read.csv(\"datasets/Liver_Steatosis.csv\")\nsummarytools::freq(liver$MET_Syndrome)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrequencies  \nliver$MET_Syndrome  \nType: Integer  \n\n              Freq   % Valid   % Valid Cum.   % Total   % Total Cum.\n----------- ------ --------- -------------- --------- --------------\n          0    144     32.65          32.65     32.51          32.51\n          1    297     67.35         100.00     67.04          99.55\n       <NA>      2                               0.45         100.00\n      Total    443    100.00         100.00    100.00         100.00\n```\n\n\n:::\n:::\n\nBased on `freq`, the proportion of those with metabolic syndrome is 0.6735 out of a sample size of 441 (removed two missing). We now have everything we need to calculate the confidence interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphat <- 297/443\nsampsize <- 441\nalpha <- 1-0.95\nrelcoeff <- qnorm(p=1-alpha/2,mean=0,sd=1)\nse <- sqrt((phat*(1-phat)/sampsize))\n\nlower <- phat - relcoeff*se\nlower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6265577\n```\n\n\n:::\n\n```{.r .cell-code}\nupper <- phat + relcoeff*se\nupper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7143001\n```\n\n\n:::\n:::\n\n\nThe 95% confidence interval for the proportion of patients with metabolic syndrome is (0.6266,0.7143).\n\n::: callout-warning\nCaution should be exercised in generalizing this result to all patients from the country as this is a very specific sample.\n:::\n:::\n\n## Exercise\n\nConsider the sleep health data uploaded on Canvas as `SleepHealthData.csv`.\n\n::: panel-tabset\n### Question\n\nUse the `sleep_disorder` column to do the following:\n\n- Estimate the prevalence rate of sleep apnea in the population this sample represents using the sample proportion.\n- Calculate a 90% confidence interval for the prevalence rate of sleep apnea.\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(sleep$sleep_disorder)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrequencies  \nsleep$_disorder  \nType: Character  \n\n                    Freq   % Valid   % Valid Cum.   % Total   % Total Cum.\n----------------- ------ --------- -------------- --------- --------------\n         Insomnia     77     20.59          20.59     20.59          20.59\n             None    219     58.56          79.14     58.56          79.14\n      Sleep Apnea     78     20.86         100.00     20.86         100.00\n             <NA>      0                               0.00         100.00\n            Total    374    100.00         100.00    100.00         100.00\n```\n\n\n:::\n:::\n\n\nThe proportion of participants who reported sleep apnea is 0.2086. The sample size is 374. We can now calculate a 90% confidence interval for the prevalence rate of sleep apnea based on this sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphat <- 78/374\nsampsize <- 374\nalpha = 1-0.9\nrelcoeff = qnorm(p=1-alpha/2,mean=0,sd=1)\nse <- sqrt((phat*(1-phat)/sampsize))\n\nlower <- phat - relcoeff*se\nlower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.174001\n```\n\n\n:::\n\n```{.r .cell-code}\nupper <- phat + relcoeff*se\nupper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2431113\n```\n\n\n:::\n:::\n\n\nThe 90% confidence interval for the prevalence rate of sleep apnea in the population this sample represents is (0.174,0.2431).\n\n:::\n\n# Sample Size Calculation \n\n## How to determine sample sizes\n\nBefore data are collected, we often need to make a decision about how large of a sample will be required to estimate population parameters. \n\n::: callout-important\nThe sample size depends on the precision/margin of error we would like for our resulting confidence intervals.\n:::\n\n## Sample size for population proportion estimation\n\nSuppose we want our margin of error (MOE) to be equal to $E$ for our planned study. The corresponding estimate for the sample size needed to reach this level of precision is given by\n\n$$\nn = z^2_{1-\\alpha/2} \\frac{ \\hat{\\pi}(1-\\hat{\\pi})}{E^2}\n$$\n\n::: callout-important\nNote that the population proportion AND sample proportion are unknown before data collection. However, we need to have an idea what the expected proportion is for our study, denoted by $\\hat{\\pi}$ in this case. This proportion can be estimated from prior or pilot studies. If there are no prior studies available (which is the case for some pilot studies), we can assume $\\hat{\\pi}=0.5$ to create a conservative confidence interval.\n:::\n\n## Example\n\nSuppose we want to design a pilot study to estimate the proportion of young adults in NV who use anabolic-androgenic steroids for muscle growth. \n\n::: panel-tabset\n\n### Question\nCalculate the sample size required so the resulting 95% confidence interval estimates will have a margin of error of 5%.\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE <- 0.05\npi_hat <-0.5\nalpha <- 1-0.95\nz <- qnorm(p=1-alpha/2)\n\nsampsize <- z^2*pi_hat*(1-pi_hat)/E^2\nsampsize\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 384.1459\n```\n\n\n:::\n:::\n\n\n::: callout-important\nWhen doing sample size calculations, always **round up** your final answer. For this study, you would recommend recruiting 385 participants for the study so that the MOE for the interval estimate of the usage rate of anabolic-androgenic steroids for muscle growth will be approximately 5%.\n:::\n\n:::\n\n## Exercise\n\nSuppose we performed the pilot study on steroid use and we plan to use the results to design a large scale study. \n\n::: panel-tabset\n\n### Question\nThe pilot study yielded an estimated usage rate of 32%. Calculate the sample size required so the resulting 95% confidence interval estimates will have a margin of error of 1%.\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE <- 0.01\npi_hat <-0.32\nalpha <- 1-0.95\nz <- qnorm(p=1-alpha/2)\n\nsampsize <- z^2*pi_hat*(1-pi_hat)/E^2\nsampsize\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8359.014\n```\n\n\n:::\n:::\n\n\n::: callout-important\nFor this study, you would recommend recruiting 8360 participants for the study so that the MOE for the interval estimate of the usage rate of anabolic-androgenic steroids for muscle growth will be approximately 1%.\n:::\n\n:::\n\n## Sample size for population mean estimation\n\nSuppose we want our margin of error (MOE) to be equal to $E$ for our planned study. The corresponding estimate for the sample size needed to reach this level of precision is given by\n\n$$\nn = z^2_{1-\\alpha/2} \\frac{\\hat{\\sigma}^2}{E^2}\n$$\n\nwhere $\\hat{\\sigma}$ is an a priori estimate of the population standard deviation. As with the estimated population proportion, this value can be obtained from prior studies or estimated using pilot studies. \n\n::: callout-tip\nRecall that for a Gaussian distribution, approximately 99% of the population can be found within the range $(\\mu-3\\sigma,\\mu+3\\sigma)$. The width of this region is $6\\sigma$, which could be approximated by the range of the data. Hence, an approximate of the population standard deviation could be expressed as: $\\sigma= R/6$, where $R$ is the range.\n:::\n\n## Example\n\nSuppose we want to estimate the average number of views that health provider social media pages in Nevada receive weekly. \n\n::: panel-tabset\n### Question\n\nIf the range of mean views was estimated to be 300,000, how many social media pages should be sampled so that our 99% confidence interval for the average number of views of Nevada health provider social media pages has a margin of error of 10,000?\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 1-0.99\nz <- qnorm(p=1-alpha/2)\nsigma <- 300000/6\nE <- 10000\nsampsize <-z^2*sigma^2/E^2\nsampsize\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 165.8724\n```\n\n\n:::\n:::\n\n\nWe need to sample 166 to achieve a margin of error of 10,000 for our 99% confidence interval.\n\n:::\n\n## Example\n\nYou designed a study to estimate the average number of views that health provider social media pages in Nevada receive weekly. \n\n::: panel-tabset\n### Question\n\nSuppose your boss was not happy with the margin of error for the 99% confidence interval of 10,000 and wanted to decrease the margin of error to 500. How many samples would be recommended for the study if the range of mean views was estimated to be 300,000.\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 1-0.99\nz <- qnorm(p=1-alpha/2)\nsigma <- 300000/6\nE <- 500\nsampsize <-z^2*sigma^2/E^2\nsampsize\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 66348.97\n```\n\n\n:::\n:::\n\n\nWe need to sample 66349 to achieve a margin of error of 500 for our 99% confidence interval.\n\n:::\n\n\n# Confidence Intervals for Difference in Statistics\n\n## CI for Difference in Statistics\n\nOften, we are more interested in comparing between two groups.\n\n::: callout-note\nRecall that in Chapter 5, we showed how differences between two parameters had a different sampling distribution that individual parameters.\n:::\n\n## CI for Difference in Population Means\n\nFor two groups with known population variances $\\sigma_1$ and $\\sigma_2$, the $100(1-\\alpha)$% can be calculated using the following formula:\n\n$$\n(\\bar{x}_1-\\bar{x}_2) \\pm z_{1-\\alpha/2}\\sqrt{\\sigma_1^2/n_1 + \\sigma_2^2/n_2}\n$$\n\n## CI for Difference in Population Means\n\nFor two groups with unknown population variances, we will still use the sample variances to estimate the population variances of each group. However, we have to consider two cases:\n\n\n::: panel-tabset\n### Equal Pop. Variances\nWhen the population variances are assumed to be equal, we need to introduce a pooled variance to estimate the variance for each group.\n\n$$\ns_p^2 = \\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}\n$$\n\nThis results to the following $100(1-\\alpha)$% confidence interval:\n\n$$\n(\\bar{x}_1-\\bar{x}_2) \\pm t_{1-\\alpha/2,df} \\sqrt{s_p^2\\left(\\frac{1}{n_1} + \\frac{1}{n_2}\\right)}\n$$\n\nwhere $t_{1-\\alpha/2,df}$ has degrees of freedom equal to $df= n_1+n_2-2$.\n\n### Unequal Pop. Variances\n\nWhen the population variances are not equal, then we don't need to pool the variances. However, the t-distribution has to account for the fact that we are using estimated variances for both groups. \n\nWe introduce the **Welch-Satterthwaite** procedure to construct this confidence interval such that the $100(1-\\alpha)$% confidence interval is given by:\n\n\n$$\n(\\bar{x}_1-\\bar{x}_2) \\pm t_{1-\\alpha/2,df}\\sqrt{s_1^2/n_1 + s_2^2/n_2}\n$$\n\nwhere \n\n$$\ndf = \\frac{(s_1^2/n_1 + s_2^2/n_2)^2}{\\left(\\frac{s_1^2}{n_1}\\right)^2/(n_1-1) + \\left(\\frac{s_2^2}{n_2}\\right)^2/(n_2-1)}\n$$\n\n:::\n\n## `R` implementation\n\nWe can use `R` to manually calculate the confidence intervals using the formulas provided. However, there is an `R` function called `t.test(formula,conf.level=conf.level, var.equal=TRUE)` that we can use to calculate these confidence intervals.\n\n::: callout-note\nThis approach will not work with aggregated data (Mean and SD provided). When data is aggregated, you would need to use the formulas.\n:::\n\n::: callout-note\nThe `formula` should be of the form `response_variable~group_variable`. It can also be of the form `x = df$col1, y=df$col2` if the data has two separate columns for the two groups.\n:::\n\n## Example\n\nConsider the sleep health data uploaded on Canvas as `SleepHealthData.csv`.\n\n::: panel-tabset\n\n### Question\nCalculate a 95% confidence interval for the difference in average age of males and females who participated in the study assuming equal population variances.\n\n### Answer\nThe groups are not presented as two separate columns, but rather defined by another column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfidence_int <- t.test(age~gender,\n       data=sleep,\n       var.equal=T,\n       conf.level=0.95)\n\nconfidence_int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  age by gender\nt = 14.329, df = 372, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Female and group Male is not equal to 0\n95 percent confidence interval:\n  8.913564 11.749098\nsample estimates:\nmean in group Female   mean in group Male \n            47.40541             37.07407 \n```\n\n\n:::\n:::\n\n\nThe 95% confidence interval was calculated to be: (8.9136,11.7491)\n:::\n\n## Example\n\nThe file `40yarddash.csv` includes the 40-yard dash times from randomly selected football players from a D1 and D3 university. \n\n::: panel-tabset\n### Question\n\nCalculate a 90% confidence interval for the difference in average 40-yard dash times between the two groups assuming unequal variances.\n\n### Answer\n\nThe groups are presented as two separate columns, hence we cannot use the formula notation. We have to define `x` and `y` in `t.test` to estimate the difference of averages in `x` and `y`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyard<- read.csv(\"40yarddash.csv\")\nconfidence_int <- t.test(x=yard$D1,y=yard$D3,\n       var.equal=F,\n       conf.level=0.9)\n\nconfidence_int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  yard$D1 and yard$D3\nt = -4.5203, df = 41.952, p-value = 4.979e-05\nalternative hypothesis: true difference in means is not equal to 0\n90 percent confidence interval:\n -0.7112031 -0.3254636\nsample estimates:\nmean of x mean of y \n 4.717667  5.236000 \n```\n\n\n:::\n:::\n\n\nThe 90% confidence interval for the difference in 40-yard dash times was calculated to be: (-0.7112,-0.3255)\n:::\n\n## Exercise\n\nConsider the sleep health data uploaded on Canvas as `SleepHealthData.csv`.\n\n::: panel-tabset\n\n### Question\nCalculate a 95% confidence interval for the difference in average sleep duration of males and females who participated in the study assuming equal population variances.\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfidence_int <- t.test(sleep_duration~gender,\n       data=sleep,\n       var.equal=T,\n       conf.level=0.95)\n\nconfidence_int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  sleep_duration by gender\nt = 2.3624, df = 372, p-value = 0.01867\nalternative hypothesis: true difference in means between group Female and group Male is not equal to 0\n95 percent confidence interval:\n 0.03239537 0.35404821\nsample estimates:\nmean in group Female   mean in group Male \n            7.229730             7.036508 \n```\n\n\n:::\n:::\n\n\nThe 95% confidence interval was calculated to be: (0.0324,0.354)\n\n:::\n\n## CI for Difference in Proportions\n\nFor populations with $n_1$ and $n_2$ are large and the population proportions $\\pi_1$ and $\\pi_2$ are not too close to 0 or 1, we can implement the central limit theorem and assume the Gaussian distribution for the sampling distribution of the difference in proportions.\n\nThe resulting $100(1-\\alpha)$% confidence interval for $\\pi_1-\\pi_2$ can be expressed as:\n\n$$\n\\hat{p}_1 - \\hat{p}_2 \\pm z_{1-\\alpha/2} \\sqrt{\\frac{\\hat{p}_1(1-\\hat{p}_1)}{n_1}+\\frac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}}\n$$\n\n::: callout-note\nThis does not include a continuity correction.\n:::\n\n## `R` implementation\n\nThe function `prop.test()` can calculate the confidence intervals for the difference in proportions, even adding the continuity correction. Suppose the successes for each group are denoted by `x1` and `x2`, while the totals for each group are `n1` and `n2`. \n\n```{.r}\nprop.test(x=c(x1,x2), n=c(n1,n2),conf.level=0.95, correct=FALSE)\n```\n\nFor the resulting CI with the continuity correction, set `correct=TRUE`.\n\n\n## Example\n\nConsider the liver steatosis data set. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nliver <- read.csv(\"Liver_Steatosis.csv\")\n```\n:::\n\n\n::: panel-tabset\n\n### Question\n\nCalculate the 95% confidence interval of the difference between the proportion of positive liver steatosis detections using ultrasound (`LS_US=1`) and through biopsy (`LS_Biopsy=1`). Is it plausible that the long-run detection rates for the two methods are equal? Omit missing data and apply the continuity correction.\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(summarytools)\nfreq(liver$LS_US)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrequencies  \nliver$LS_US  \nType: Numeric  \n\n              Freq   % Valid   % Valid Cum.   % Total   % Total Cum.\n----------- ------ --------- -------------- --------- --------------\n          0    122     28.98          28.98     27.54          27.54\n        0.5      4      0.95          29.93      0.90          28.44\n          1    295     70.07         100.00     66.59          95.03\n       <NA>     22                               4.97         100.00\n      Total    443    100.00         100.00    100.00         100.00\n```\n\n\n:::\n\n```{.r .cell-code}\nfreq(liver$LS_Biopsy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrequencies  \nliver$LS_Biopsy  \nType: Numeric  \n\n              Freq   % Valid   % Valid Cum.   % Total   % Total Cum.\n----------- ------ --------- -------------- --------- --------------\n          0    124     27.99          27.99     27.99          27.99\n        0.5      8      1.81          29.80      1.81          29.80\n          1    311     70.20         100.00     70.20         100.00\n       <NA>      0                               0.00         100.00\n      Total    443    100.00         100.00    100.00         100.00\n```\n\n\n:::\n:::\n\n\nThere are 295/421 positive diagnoses for the ultrasound group and 311/443 for the biopsy group. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nptest<- prop.test(x=c(295,311),\n          n=c(443-22,443),\n          conf.level=0.95,\n          correct=TRUE)\n\nptest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(295, 311) out of c(443 - 22, 443)\nX-squared = 1.3976e-29, df = 1, p-value = 1\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.06369117  0.06105315\nsample estimates:\n   prop 1    prop 2 \n0.7007126 0.7020316 \n```\n\n\n:::\n:::\n\n\nThe resulting 95% confidence interval is (-0.0637, 0.0611). 0 is part of the interval, which means it is a plausible value of the difference in detection rates between the two methods. Hence, it is plausible that the long-run detection rates of the two methods do not differ.\n:::\n\n## Exercise\n\nIn a randomized controlled trial, 23 out of 40 participants who received the treatment reported improvement while 14 out of 35 participants who received the placebo reported improvement. \n\n::: panel-tabset\n### Question\n\nCalculate a 99% confidence interval **with and without the continuity correction** for the difference in improvement rate between the treatment and placebo groups.\n\n### Answer\n\nWithout continuity correction,\n\n::: {.cell}\n\n```{.r .cell-code}\nptest<- prop.test(x=c(23,14),\n          n=c(40,35),\n          conf.level=0.99,\n          correct=FALSE)\n\nptest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  c(23, 14) out of c(40, 35)\nX-squared = 2.2871, df = 1, p-value = 0.1305\nalternative hypothesis: two.sided\n99 percent confidence interval:\n -0.1183113  0.4683113\nsample estimates:\nprop 1 prop 2 \n 0.575  0.400 \n```\n\n\n:::\n:::\n\n\nWith the continuity correction,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nptest<- prop.test(x=c(23,14),\n          n=c(40,35),\n          conf.level=0.99,\n          correct=TRUE)\n\nptest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(23, 14) out of c(40, 35)\nX-squared = 1.6405, df = 1, p-value = 0.2003\nalternative hypothesis: two.sided\n99 percent confidence interval:\n -0.145097  0.495097\nsample estimates:\nprop 1 prop 2 \n 0.575  0.400 \n```\n\n\n:::\n:::\n\n\nThe resulting 99% confidence interval with the continuity correction is is (-0.1451, 0.4951). 0 is part of the interval, which means it is a plausible value of the difference in improvement rates between the two groups. Hence, it is plausible that the long-run improvement rate due to the treatment does not differ from the placebo.\n:::\n",
    "supporting": [
      "lecture6_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}